Repository Kernel360/F2_PLAY_BADMINTON_BE, pull requests merged in 2024-12, with the labels that each got.

#498 feat: 도커 빌드 버전 업데이트 및 exception 수정
  api/Dockerfile
  api/build.gradle
  api/src/main/java/org/badminton/api/aws/s3/service/ImageConversionService.java
  domain/src/main/java/org/badminton/domain/common/exception/BadmintonException.java
Labels: beforeLunch🍕

#497 refactor: 동호회에 지원한 회원 리스트 조회 시 페이지네이션 적용
  api/src/main/java/org/badminton/api/application/club/ClubFacade.java
  api/src/main/java/org/badminton/api/interfaces/club/controller/ClubController.java
  domain/src/main/java/org/badminton/domain/domain/club/ClubApplyReader.java
  domain/src/main/java/org/badminton/domain/domain/club/ClubService.java
  domain/src/main/java/org/badminton/domain/domain/club/ClubServiceImpl.java
  domain/src/main/java/org/badminton/domain/domain/club/entity/ClubApply.java
  infrastructure/src/main/java/org/badminton/infrastructure/club/ClubApplyReaderImpl.java
  infrastructure/src/main/java/org/badminton/infrastructure/club/ClubApplyRepository.java
Labels: beforeLunch🍕, refactor✍️

#501 refactor: 대진표 재생성 조건 수정
  domain/src/main/java/org/badminton/domain/common/error/ErrorCode.java
  domain/src/main/java/org/badminton/domain/common/exception/league/CannotStartMatchException.java
  domain/src/main/java/org/badminton/domain/common/exception/match/InvalidLeagueStatusToGenerateBracketException.java
  domain/src/main/java/org/badminton/domain/common/exception/match/MatchAlreadyStartedExceptionWhenBracketGenerationException.java
  domain/src/main/java/org/badminton/domain/common/exception/match/MatchDuplicateException.java
  domain/src/main/java/org/badminton/domain/domain/match/service/AbstractDoublesMatchStrategy.java
  domain/src/main/java/org/badminton/domain/domain/match/service/AbstractSinglesMatchStrategy.java
  domain/src/main/java/org/badminton/domain/domain/match/service/BracketGenerationService.java
  infrastructure/src/main/java/org/badminton/infrastructure/match/service/FreeBracketGenerationServiceImpl.java
  infrastructure/src/main/java/org/badminton/infrastructure/match/service/TournamentBracketGenerationServiceImpl.java
  infrastructure/src/main/java/org/badminton/infrastructure/match/strategy/FreeDoublesMatchStrategy.java
  infrastructure/src/main/java/org/badminton/infrastructure/match/strategy/FreeSinglesMatchStrategy.java
  infrastructure/src/main/java/org/badminton/infrastructure/match/strategy/TournamentDoublesMatchStrategy.java
  infrastructure/src/main/java/org/badminton/infrastructure/match/strategy/TournamentSinglesMatchStrategy.java
Labels: 5PM🌝, refactor✍️

#503 feat: 이메일 인코딩 깨짐 현상 수정
  api/Dockerfile
Labels: 5PM🌝

#504 refactor: 매치 점수 조회 응답을 수정했습니다.
  api/src/main/java/org/badminton/api/interfaces/match/controller/MatchController.java
  api/src/main/java/org/badminton/api/interfaces/match/dto/DoublesMatchResponse.java
  api/src/main/java/org/badminton/api/interfaces/match/dto/DoublesSetResponse.java
  api/src/main/java/org/badminton/api/interfaces/match/dto/MatchDetailsResponse.java
  api/src/main/java/org/badminton/api/interfaces/match/dto/SinglesMatchResponse.java
  api/src/main/java/org/badminton/api/interfaces/match/dto/SinglesSetResponse.java
  domain/src/main/java/org/badminton/domain/domain/match/entity/DoublesMatch.java
  domain/src/main/java/org/badminton/domain/domain/match/entity/SinglesMatch.java
  domain/src/main/java/org/badminton/domain/domain/match/info/DoublesSetInfo.java
  domain/src/main/java/org/badminton/domain/domain/match/info/MatchInfo.java
  domain/src/main/java/org/badminton/domain/domain/match/info/SinglesSetInfo.java
Labels: refactor✍️

#507 feat: 이미지 비동기 처리
  api/src/main/java/org/badminton/api/application/clubImage/ClubImageFacade.java
  api/src/main/java/org/badminton/api/application/member/MemberFacade.java
  api/src/main/java/org/badminton/api/aws/s3/controller/ClubImageController.java
  api/src/main/java/org/badminton/api/aws/s3/event/clubImage/ClubImageEvent.java
  api/src/main/java/org/badminton/api/aws/s3/event/clubImage/ClubImageEventHandler.java
  api/src/main/java/org/badminton/api/aws/s3/event/memeber/MemberImageEvent.java
  api/src/main/java/org/badminton/api/aws/s3/event/memeber/MemberImageEventHandler.java
  api/src/main/java/org/badminton/api/aws/s3/service/AbstractFileUploadService.java
  api/src/main/java/org/badminton/api/aws/s3/service/ClubImageService.java
  api/src/main/java/org/badminton/api/aws/s3/service/ImageConversionService.java
  api/src/main/java/org/badminton/api/aws/s3/service/ImageService.java
  api/src/main/java/org/badminton/api/aws/s3/service/MemberProfileImageService.java
  api/src/main/java/org/badminton/api/interfaces/member/controller/MemberController.java
Labels: 5PM🌝

#511 fix: match retrieve league id confusion
  api/src/main/java/org/badminton/api/application/match/MatchFacade.java
  api/src/main/java/org/badminton/api/interfaces/match/dto/MatchDetailsResponse.java
  domain/src/main/java/org/badminton/domain/domain/statistics/event/CreateClubEventHandler.java
  domain/src/main/java/org/badminton/domain/domain/statistics/event/ReadClubEventHandler.java
  infrastructure/src/main/java/org/badminton/infrastructure/match/service/TournamentBracketGenerationServiceImpl.java
Labels: fix🛠️, now❗️

#512 fix: 대진표 재생성 조건 수정
  api/src/main/java/org/badminton/api/config/security/SecurityConfig.java
  domain/src/main/java/org/badminton/domain/domain/match/service/AbstractDoublesMatchStrategy.java
  domain/src/main/java/org/badminton/domain/domain/match/service/AbstractSinglesMatchStrategy.java
  infrastructure/src/main/java/org/badminton/infrastructure/match/service/FreeBracketGenerationServiceImpl.java
  infrastructure/src/main/java/org/badminton/infrastructure/match/service/TournamentBracketGenerationServiceImpl.java
Labels: fix🛠️, beforeLunch🍕

#513 hotfix: 부전승 로직 수정
  infrastructure/src/main/java/org/badminton/infrastructure/match/strategy/TournamentSinglesMatchStrategy.java
Labels: hotfix🥵

#518 refactor: match policy changes
  domain/src/main/java/org/badminton/domain/common/error/ErrorCode.java
  domain/src/main/java/org/badminton/domain/common/exception/match/LeagueParticipationNotExistInMatchException.java
  domain/src/main/java/org/badminton/domain/common/exception/match/PreviousDetNotFinishedException.java
  domain/src/main/java/org/badminton/domain/common/exception/match/RoundNotFinishedException.java
  domain/src/main/java/org/badminton/domain/domain/match/service/AbstractDoublesMatchStrategy.java
  domain/src/main/java/org/badminton/domain/domain/match/service/AbstractSinglesMatchStrategy.java
  domain/src/main/java/org/badminton/domain/domain/match/store/DoublesMatchReader.java
  infrastructure/src/main/java/org/badminton/infrastructure/match/reader/DoublesMatchReaderImpl.java
  infrastructure/src/main/java/org/badminton/infrastructure/match/repository/DoublesMatchRepository.java
  infrastructure/src/main/java/org/badminton/infrastructure/match/service/RetrieveMatchSet.java
  infrastructure/src/main/java/org/badminton/infrastructure/match/strategy/FreeDoublesMatchStrategy.java
  infrastructure/src/main/java/org/badminton/infrastructure/match/strategy/FreeSinglesMatchStrategy.java
  infrastructure/src/main/java/org/badminton/infrastructure/match/strategy/TournamentDoublesMatchStrategy.java
  infrastructure/src/main/java/org/badminton/infrastructure/match/strategy/TournamentSinglesMatchStrategy.java
Labels: refactor✍️

#519 feat: 경기 모집을 마감하는 API를 추가했습니다.
  api/src/main/java/org/badminton/api/application/league/LeagueFacade.java
  api/src/main/java/org/badminton/api/interfaces/league/controller/LeagueController.java
  api/src/main/java/org/badminton/api/interfaces/league/controller/LeagueDtoMapper.java
  api/src/main/java/org/badminton/api/interfaces/league/dto/LeagueCreateRequest.java
  api/src/main/java/org/badminton/api/interfaces/league/dto/LeagueRecruitingCompleteResponse.java
  api/src/main/java/org/badminton/api/interfaces/league/dto/LeagueUpdateRequest.java
  batch/src/main/java/springproject/badmintonbatch/batch/processor/LeagueStatusProcessor.java
  domain/src/main/java/org/badminton/domain/common/error/ErrorCode.java
  domain/src/main/java/org/badminton/domain/common/exception/league/InvalidDoublesPlayerLimitCountException.java
  domain/src/main/java/org/badminton/domain/common/exception/league/InvalidLeagueParticipantCountException.java
  domain/src/main/java/org/badminton/domain/common/exception/league/InvalidSinglesPlayerLimitCountException.java
  domain/src/main/java/org/badminton/domain/common/exception/league/LeagueRecruitingAlreadyCompletedException.java
  domain/src/main/java/org/badminton/domain/common/exception/league/LeagueRecruitingCompletedException.java
  domain/src/main/java/org/badminton/domain/common/exception/league/PlayerLimitCountMustBeMoreThanFourException.java
  domain/src/main/java/org/badminton/domain/common/exception/league/PlayerLimitCountMustBeMultipleWhenDoublesMatch.java
  domain/src/main/java/org/badminton/domain/domain/league/LeagueParticipantServiceImpl.java
  domain/src/main/java/org/badminton/domain/domain/league/LeagueService.java
  domain/src/main/java/org/badminton/domain/domain/league/LeagueServiceImpl.java
  domain/src/main/java/org/badminton/domain/domain/league/entity/League.java
  domain/src/main/java/org/badminton/domain/domain/league/info/LeagueRecruitingCompleteInfo.java
  infrastructure/src/main/java/org/badminton/infrastructure/match/service/FreeBracketGenerationServiceImpl.java
  infrastructure/src/main/java/org/badminton/infrastructure/match/service/TournamentBracketGenerationServiceImpl.java
Labels: 5PM🌝, refactor✍️

#523 bug: 파일 업로드 에러 수정
  api/src/main/java/org/badminton/api/aws/s3/controller/ClubImageController.java
  api/src/main/java/org/badminton/api/aws/s3/event/clubImage/ClubImageEventHandler.java
  api/src/main/java/org/badminton/api/aws/s3/model/dto/ImageUploadRequest.java
  api/src/main/java/org/badminton/api/aws/s3/service/AbstractFileUploadService.java
  api/src/main/java/org/badminton/api/aws/s3/service/ImageConversionService.java
  api/src/main/java/org/badminton/api/interfaces/member/controller/MemberController.java
Labels: hotfix🥵, beforeLunch🍕

#525 refactor: add a member policy when start match
  api/src/main/java/org/badminton/api/config/security/SecurityConfig.java
  api/src/main/java/org/badminton/api/interfaces/match/controller/MatchController.java
  domain/src/main/java/org/badminton/domain/common/error/ErrorCode.java
  domain/src/main/java/org/badminton/domain/common/exception/match/LeagueParticipantNotDeterminedException.java
  domain/src/main/java/org/badminton/domain/common/exception/match/LeagueParticipantsNotExistsException.java
  domain/src/main/java/org/badminton/domain/common/exception/match/LeagueParticipationNotExistInMatchException.java
  domain/src/main/java/org/badminton/domain/common/policy/ClubMemberPolicy.java
  infrastructure/src/main/java/org/badminton/infrastructure/match/service/RetrieveMatchSet.java
  infrastructure/src/main/java/org/badminton/infrastructure/match/strategy/TournamentDoublesMatchStrategy.java
  infrastructure/src/main/java/org/badminton/infrastructure/match/strategy/TournamentSinglesMatchStrategy.java
Labels: 5PM🌝, refactor✍️

#526 feat: 토너먼트 복식 부전승 로직 구현
  domain/src/main/java/org/badminton/domain/common/error/ErrorCode.java
  domain/src/main/java/org/badminton/domain/common/exception/match/ByeMatchException.java
  domain/src/main/java/org/badminton/domain/common/exception/match/RegisterScoreInByeMatchException.java
  domain/src/main/java/org/badminton/domain/domain/match/entity/DoublesMatch.java
  infrastructure/src/main/java/org/badminton/infrastructure/match/reader/DoublesMatchReaderImpl.java
  infrastructure/src/main/java/org/badminton/infrastructure/match/repository/DoublesMatchRepository.java
  infrastructure/src/main/java/org/badminton/infrastructure/match/strategy/TournamentDoublesMatchStrategy.java
  infrastructure/src/main/java/org/badminton/infrastructure/match/strategy/TournamentSinglesMatchStrategy.java
Labels: feat✨

#528 bug: 이미지 업로드 관련 버그 수정
  api/src/main/java/org/badminton/api/application/clubImage/ClubImageFacade.java
  api/src/main/java/org/badminton/api/application/member/MemberFacade.java
  api/src/main/java/org/badminton/api/aws/s3/event/clubImage/ClubImageEvent.java
  api/src/main/java/org/badminton/api/aws/s3/event/clubImage/ClubImageEventHandler.java
  api/src/main/java/org/badminton/api/aws/s3/event/memeber/MemberImageEvent.java
  api/src/main/java/org/badminton/api/aws/s3/event/memeber/MemberImageEventHandler.java
  api/src/main/java/org/badminton/api/aws/s3/service/AbstractFileUploadService.java
  api/src/main/java/org/badminton/api/aws/s3/service/ClubImageService.java
  api/src/main/java/org/badminton/api/aws/s3/service/ImageConversionService.java
  api/src/main/java/org/badminton/api/aws/s3/service/ImageService.java
  api/src/main/java/org/badminton/api/aws/s3/service/MemberProfileImageService.java
Labels: hotfix🥵

#531 refactor: 스코어보드에서 점수 조회 시 레디스 캐시를 먼저 조회
  api/src/main/java/org/badminton/api/application/match/MatchFacade.java
  api/src/main/java/org/badminton/api/interfaces/match/controller/MatchController.java
  api/src/main/java/org/badminton/api/interfaces/match/dto/MatchSetResponse.java
  domain/src/main/java/org/badminton/domain/common/error/ErrorCode.java
  domain/src/main/java/org/badminton/domain/domain/match/info/MatchSetInfo.java
  domain/src/main/java/org/badminton/domain/domain/match/vo/RedisKey.java
  domain/src/main/java/org/badminton/domain/domain/match/vo/Score.java
  infrastructure/src/main/java/org/badminton/infrastructure/match/repository/SetRepository.java
  infrastructure/src/main/java/org/badminton/infrastructure/match/service/RetrieveMatchSet.java
Labels: 5PM🌝, refactor✍️

#530 refactor : 경기 참가하고 있는 맴버 제재시 처리
  api/src/main/java/org/badminton/api/interfaces/match/dto/MatchTeamResponse.java
  api/src/main/java/org/badminton/api/interfaces/match/dto/Participant.java
  api/src/main/java/org/badminton/api/interfaces/match/dto/SinglesMatchResponse.java
  api/src/main/resources/banner.txt
  domain/src/main/java/org/badminton/domain/domain/clubmember/service/ClubMemberServiceImpl.java
  domain/src/main/java/org/badminton/domain/domain/league/LeagueParticipantCancelProcessor.java
  domain/src/main/java/org/badminton/domain/domain/league/LeagueParticipantReader.java
  domain/src/main/java/org/badminton/domain/domain/league/LeagueParticipantService.java
  domain/src/main/java/org/badminton/domain/domain/league/LeagueParticipantServiceImpl.java
  domain/src/main/java/org/badminton/domain/domain/league/event/LeagueParticipantCancelEvent.java
  domain/src/main/java/org/badminton/domain/domain/league/event/LeagueParticipantCancelEventHandler.java
  domain/src/main/java/org/badminton/domain/domain/match/info/MatchTeamInfo.java
  domain/src/main/java/org/badminton/domain/domain/match/info/SinglesMatchInfo.java
  domain/src/main/java/org/badminton/domain/domain/match/service/AbstractMatchRetrieveService.java
  infrastructure/src/main/java/org/badminton/infrastructure/league/LeagueParticipantReaderImpl.java
  infrastructure/src/main/java/org/badminton/infrastructure/league/LeagueParticipantRepository.java
  infrastructure/src/main/java/org/badminton/infrastructure/match/service/FreeMatchRetrieveServiceImpl.java
  infrastructure/src/main/java/org/badminton/infrastructure/match/service/TournamentMatchRetrieveServiceImpl.java
Labels: refactor✍️

#534 refactor: TournamentMatchStrategy 리팩토링
  domain/src/main/java/org/badminton/domain/common/consts/Constants.java
  domain/src/main/java/org/badminton/domain/domain/league/entity/LeagueParticipant.java
  domain/src/main/java/org/badminton/domain/domain/league/vo/Team.java
  domain/src/main/java/org/badminton/domain/domain/match/entity/DoublesMatch.java
  domain/src/main/java/org/badminton/domain/domain/match/entity/SinglesMatch.java
  domain/src/main/java/org/badminton/domain/domain/match/service/AbstractSinglesMatchStrategy.java
  domain/src/main/java/org/badminton/domain/domain/match/service/MatchStrategy.java
  infrastructure/src/main/java/org/badminton/infrastructure/match/service/FreeMatchProgressServiceImpl.java
  infrastructure/src/main/java/org/badminton/infrastructure/match/service/TournamentBracketGenerationServiceImpl.java
  infrastructure/src/main/java/org/badminton/infrastructure/match/service/TournamentDoublesBracketCreator.java
  infrastructure/src/main/java/org/badminton/infrastructure/match/service/TournamentDoublesEndSetHandler.java
  infrastructure/src/main/java/org/badminton/infrastructure/match/service/TournamentMatchProgressServiceImpl.java
  infrastructure/src/main/java/org/badminton/infrastructure/match/service/TournamentMatchRetrieveServiceImpl.java
  infrastructure/src/main/java/org/badminton/infrastructure/match/service/TournamentSinglesBracketCreator.java
  infrastructure/src/main/java/org/badminton/infrastructure/match/service/TournamentSinglesEndSetHandler.java
  infrastructure/src/main/java/org/badminton/infrastructure/match/strategy/FreeDoublesMatchStrategy.java
  infrastructure/src/main/java/org/badminton/infrastructure/match/strategy/FreeSinglesMatchStrategy.java
  infrastructure/src/main/java/org/badminton/infrastructure/match/strategy/MatchUtils.java
  infrastructure/src/main/java/org/badminton/infrastructure/match/strategy/TournamentDoublesMatchStrategy.java
  infrastructure/src/main/java/org/badminton/infrastructure/match/strategy/TournamentSinglesMatchStrategy.java
Labels: refactor✍️

#536 refactor: 인기 Top 동호회, 활동 Top 동호회, 최근 생성 Top 동호회 조회 성능 개선
  api/src/main/java/org/badminton/api/application/club/ClubRankFacade.java
  api/src/main/java/org/badminton/api/application/club/strategy/ActivityClub.java
  api/src/main/java/org/badminton/api/application/club/strategy/PopularClub.java
  api/src/main/java/org/badminton/api/application/club/strategy/Rank.java
  api/src/main/java/org/badminton/api/config/security/SecurityConfig.java
  api/src/main/java/org/badminton/api/interfaces/club/controller/ClubController.java
  api/src/main/resources/data.sql
  domain/src/main/java/org/badminton/domain/domain/club/ClubReader.java
  domain/src/main/java/org/badminton/domain/domain/club/ClubService.java
  domain/src/main/java/org/badminton/domain/domain/club/ClubServiceImpl.java
  domain/src/main/java/org/badminton/domain/domain/statistics/ClubStatistics.java
  domain/src/main/java/org/badminton/domain/domain/statistics/ClubStatisticsReader.java
  domain/src/main/java/org/badminton/domain/domain/statistics/ClubStatisticsService.java
  domain/src/main/java/org/badminton/domain/domain/statistics/ClubStatisticsServiceImpl.java
  infrastructure/src/main/java/org/badminton/infrastructure/club/ClubReaderImpl.java
  infrastructure/src/main/java/org/badminton/infrastructure/statistics/ClubStatisticsReaderImpl.java
  infrastructure/src/main/java/org/badminton/infrastructure/statistics/ClubStatisticsRepository.java
Labels: 5PM🌝, refactor✍️

#535 refactor : 경기 참가하고 있는 맴버 제재시 처리
  api/src/main/java/org/badminton/api/interfaces/match/dto/MatchTeamResponse.java
  api/src/main/java/org/badminton/api/interfaces/match/dto/Participant.java
  api/src/main/java/org/badminton/api/interfaces/match/dto/SinglesMatchResponse.java
  api/src/main/resources/banner.txt
  domain/src/main/java/org/badminton/domain/domain/clubmember/service/ClubMemberServiceImpl.java
  domain/src/main/java/org/badminton/domain/domain/league/LeagueParticipantCancelService.java
  domain/src/main/java/org/badminton/domain/domain/league/LeagueParticipantCancelServiceImpl.java
  domain/src/main/java/org/badminton/domain/domain/league/LeagueParticipantReader.java
  domain/src/main/java/org/badminton/domain/domain/league/LeagueParticipantService.java
  domain/src/main/java/org/badminton/domain/domain/league/LeagueParticipantServiceImpl.java
  domain/src/main/java/org/badminton/domain/domain/league/event/ClubMemberBanEvent.java
  domain/src/main/java/org/badminton/domain/domain/league/event/ClubMemberBanEventHandler.java
  domain/src/main/java/org/badminton/domain/domain/match/info/MatchTeamInfo.java
  domain/src/main/java/org/badminton/domain/domain/match/info/SinglesMatchInfo.java
  domain/src/main/java/org/badminton/domain/domain/match/service/AbstractMatchRetrieveService.java
  infrastructure/src/main/java/org/badminton/infrastructure/league/LeagueParticipantReaderImpl.java
  infrastructure/src/main/java/org/badminton/infrastructure/league/LeagueParticipantRepository.java
  infrastructure/src/main/java/org/badminton/infrastructure/match/service/FreeMatchRetrieveServiceImpl.java
  infrastructure/src/main/java/org/badminton/infrastructure/match/service/TournamentMatchRetrieveServiceImpl.java
Labels: 5PM🌝

#537 refactor: Club Card Response 정적 팩토리 메서드 파라미터 수정 및 ClubStatistics 메서드 수정
  api/src/main/java/org/badminton/api/application/club/ClubRankFacade.java
  domain/src/main/java/org/badminton/domain/domain/club/ClubPage.java
  domain/src/main/java/org/badminton/domain/domain/club/ClubServiceImpl.java
  domain/src/main/java/org/badminton/domain/domain/club/info/ClubCardInfo.java
  domain/src/main/java/org/badminton/domain/domain/clubmember/service/ClubMemberServiceImpl.java
  domain/src/main/java/org/badminton/domain/domain/statistics/ClubStatistics.java
  domain/src/main/java/org/badminton/domain/domain/statistics/ClubStatisticsReader.java
  domain/src/main/java/org/badminton/domain/domain/statistics/ClubStatisticsServiceImpl.java
  domain/src/main/java/org/badminton/domain/domain/statistics/ClubStatisticsStore.java
  infrastructure/src/main/java/org/badminton/infrastructure/statistics/ClubStatisticsReaderImpl.java
  infrastructure/src/main/java/org/badminton/infrastructure/statistics/ClubStatisticsStoreImpl.java
Labels: 5PM🌝, refactor✍️

#541 bug : isParticipantBanned 에서 오류 발생 해결
  domain/src/main/java/org/badminton/domain/domain/match/info/MatchTeamInfo.java
  domain/src/main/java/org/badminton/domain/domain/match/info/SinglesMatchInfo.java
Labels: hotfix🥵

#543 refactor: redis 사용해 api 응답 속도 최적화
  api/build.gradle
  api/src/main/java/org/badminton/api/application/club/ClubRankFacade.java
  domain/src/main/java/org/badminton/domain/domain/club/vo/ClubRedisKey.java
  domain/src/main/java/org/badminton/domain/domain/statistics/ClubStatisticsReader.java
  domain/src/main/java/org/badminton/domain/domain/statistics/ClubStatisticsService.java
  domain/src/main/java/org/badminton/domain/domain/statistics/ClubStatisticsServiceImpl.java
  infrastructure/build.gradle
  infrastructure/src/main/java/org/badminton/infrastructure/config/RedisConfig.java
  infrastructure/src/main/java/org/badminton/infrastructure/statistics/ClubStatisticsReaderImpl.java
Labels: refactor✍️

#546 refactor: league participant policy
  api/src/main/java/org/badminton/api/interfaces/league/controller/LeagueController.java
  api/src/main/java/org/badminton/api/interfaces/league/dto/LeagueCreateRequest.java
  api/src/main/java/org/badminton/api/interfaces/league/dto/LeagueUpdateRequest.java
  domain/src/main/java/org/badminton/domain/common/consts/Constants.java
  domain/src/main/java/org/badminton/domain/common/error/ErrorCode.java
  domain/src/main/java/org/badminton/domain/common/policy/LeagueParticipantPolicy.java
  domain/src/main/java/org/badminton/domain/domain/league/entity/League.java
Labels: 5PM🌝, refactor✍️

#548 refactor: 최근 활동이 많은 top10 동호회 조회 redis 사용
  api/src/main/java/org/badminton/api/application/club/ClubRankFacade.java
  domain/src/main/java/org/badminton/domain/domain/club/vo/ClubRedisKey.java
  domain/src/main/java/org/badminton/domain/domain/statistics/ClubStatisticsReader.java
  domain/src/main/java/org/badminton/domain/domain/statistics/ClubStatisticsService.java
  domain/src/main/java/org/badminton/domain/domain/statistics/ClubStatisticsServiceImpl.java
  infrastructure/src/main/java/org/badminton/infrastructure/statistics/ClubStatisticsReaderImpl.java
Labels: refactor✍️

#552 hotfix: allClubs 조회 레디스 제거
  api/src/main/java/org/badminton/api/application/club/ClubFacade.java
  api/src/main/java/org/badminton/api/interfaces/club/controller/ClubController.java
  domain/src/main/java/org/badminton/domain/domain/club/ClubReader.java
  domain/src/main/java/org/badminton/domain/domain/club/ClubService.java
  domain/src/main/java/org/badminton/domain/domain/club/ClubServiceImpl.java
  domain/src/main/java/org/badminton/domain/domain/club/event/UpdateClubEventHandler.java
  domain/src/main/java/org/badminton/domain/domain/club/vo/ClubRedisKey.java
  domain/src/main/java/org/badminton/domain/domain/statistics/event/CreateClubEventHandler.java
  infrastructure/src/main/java/org/badminton/infrastructure/club/ClubReaderImpl.java
Labels: hotfix🥵

#551 refactor: 메인 리그 화면에서 현재 진행 중인 점수를 조회할 때 레디스에서 먼저 조회
  api/src/main/java/org/badminton/api/application/match/MatchFacade.java
  api/src/main/java/org/badminton/api/interfaces/match/controller/MatchController.java
  domain/src/main/java/org/badminton/domain/domain/match/entity/DoublesMatch.java
  domain/src/main/java/org/badminton/domain/domain/match/entity/DoublesSet.java
  domain/src/main/java/org/badminton/domain/domain/match/entity/SinglesMatch.java
  domain/src/main/java/org/badminton/domain/domain/match/entity/SinglesSet.java
  domain/src/main/java/org/badminton/domain/domain/match/service/AbstractDoublesMatchStrategy.java
  domain/src/main/java/org/badminton/domain/domain/match/service/AbstractSinglesMatchStrategy.java
  domain/src/main/java/org/badminton/domain/domain/match/vo/LeagueMatchSetRedisKey.java
  domain/src/main/java/org/badminton/domain/domain/match/vo/MatchRedisKey.java
  infrastructure/src/main/java/org/badminton/infrastructure/match/repository/SetRepository.java
  infrastructure/src/main/java/org/badminton/infrastructure/match/service/FreeBracketGenerationServiceImpl.java
  infrastructure/src/main/java/org/badminton/infrastructure/match/service/RetrieveMatchSet.java
  infrastructure/src/main/java/org/badminton/infrastructure/match/service/TournamentBracketGenerationServiceImpl.java
Labels: 5PM🌝, refactor✍️

#554 feat : 파일사이즈 체크
  api/src/main/java/org/badminton/api/application/clubImage/ClubImageFacade.java
  api/src/main/java/org/badminton/api/application/member/MemberFacade.java
  api/src/main/resources/application.yaml
  domain/src/main/java/org/badminton/domain/common/error/ErrorCode.java
Labels: beforeLunch🍕

#557 feat: 토너먼트 세트 종료 제약 조건 추가 및 프리매치 DRAW 로직 추가
  domain/src/main/java/org/badminton/domain/common/error/ErrorCode.java
  domain/src/main/java/org/badminton/domain/common/exception/match/SetScoreNotReachedException.java
  domain/src/main/java/org/badminton/domain/common/exception/match/TieScoreNotAllowedException.java
  domain/src/main/java/org/badminton/domain/domain/match/entity/DoublesMatch.java
  domain/src/main/java/org/badminton/domain/domain/match/entity/SinglesMatch.java
  infrastructure/src/main/java/org/badminton/infrastructure/match/service/TournamentDoublesEndSetHandler.java
  infrastructure/src/main/java/org/badminton/infrastructure/match/service/TournamentSinglesEndSetHandler.java
  infrastructure/src/main/java/org/badminton/infrastructure/match/strategy/FreeDoublesMatchStrategy.java
  infrastructure/src/main/java/org/badminton/infrastructure/match/strategy/FreeSinglesMatchStrategy.java
  infrastructure/src/main/java/org/badminton/infrastructure/match/strategy/MatchUtils.java
Labels: feat✨

#558 refactor: MatchScorePolicy 적용
  api/src/main/java/org/badminton/api/application/match/FreeMatchFacade.java
  api/src/main/java/org/badminton/api/application/match/MatchFacade.java
  api/src/main/java/org/badminton/api/application/match/TournamentMatchFacade.java
  domain/src/main/java/org/badminton/domain/common/error/ErrorCode.java
  domain/src/main/java/org/badminton/domain/common/exception/match/CannotStartMatchException.java
  domain/src/main/java/org/badminton/domain/common/exception/match/PreviousSetNotFinishedException.java
  domain/src/main/java/org/badminton/domain/common/policy/MatchScorePolicy.java
  domain/src/main/java/org/badminton/domain/domain/match/reader/DoublesMatchReader.java
  domain/src/main/java/org/badminton/domain/domain/match/reader/SinglesMatchReader.java
  domain/src/main/java/org/badminton/domain/domain/match/service/AbstractDoublesMatchStrategy.java
  domain/src/main/java/org/badminton/domain/domain/match/service/AbstractSinglesMatchStrategy.java
  infrastructure/src/main/java/org/badminton/infrastructure/match/reader/DoublesMatchReaderImpl.java
  infrastructure/src/main/java/org/badminton/infrastructure/match/reader/SinglesMatchReaderImpl.java
  infrastructure/src/main/java/org/badminton/infrastructure/match/repository/DoublesMatchRepository.java
  infrastructure/src/main/java/org/badminton/infrastructure/match/repository/SinglesMatchRepository.java
  infrastructure/src/main/java/org/badminton/infrastructure/match/service/RetrieveMatchSet.java
  infrastructure/src/main/java/org/badminton/infrastructure/match/service/TournamentDoublesEndSetHandler.java
  infrastructure/src/main/java/org/badminton/infrastructure/match/service/TournamentSinglesEndSetHandler.java
  infrastructure/src/main/java/org/badminton/infrastructure/match/strategy/FreeDoublesMatchStrategy.java
  infrastructure/src/main/java/org/badminton/infrastructure/match/strategy/FreeSinglesMatchStrategy.java
Labels: beforeLunch🍕, refactor✍️

#540 refactor: redis lock 조회수에 적용, 동시성 테스트
  api/src/main/java/org/badminton/api/application/club/ClubFacade.java
  api/src/test/java/org/badminton/api/application/club/ClubFacadeTest.java
  api/src/test/resources/application-test.yaml
  domain/src/main/java/org/badminton/domain/domain/auth/service/AuthServiceImpl.java
  domain/src/main/java/org/badminton/domain/domain/club/info/ClubDetailsInfo.java
  domain/src/main/java/org/badminton/domain/domain/statistics/ClubStatisticsServiceImpl.java
  domain/src/main/java/org/badminton/domain/domain/statistics/DistributedLockProcessor.java
  domain/src/main/java/org/badminton/domain/domain/statistics/event/ReadClubEventHandler.java
  infrastructure/build.gradle
  infrastructure/src/main/java/org/badminton/infrastructure/config/RedisCacheConfig.java
  infrastructure/src/main/java/org/badminton/infrastructure/statistics/ClubStatisticsRepository.java
  infrastructure/src/main/java/org/badminton/infrastructure/statistics/DistributeLockProcessorExecutorImpl.java
Labels: feat✨, test🧈, beforeLunch🍕

#559 refactor: 트랜잭션 어노테이션 추가
  domain/src/main/java/org/badminton/domain/domain/club/ClubServiceImpl.java
  domain/src/main/java/org/badminton/domain/domain/statistics/ClubStatisticsServiceImpl.java
  infrastructure/src/main/java/org/badminton/infrastructure/club/ClubReaderImpl.java
  infrastructure/src/main/java/org/badminton/infrastructure/statistics/ClubStatisticsReaderImpl.java
Labels: beforeLunch🍕

#560 refactor: 클럽 전체 조회 최적화
  infrastructure/src/main/java/org/badminton/infrastructure/club/ClubReaderImpl.java
  infrastructure/src/main/java/org/badminton/infrastructure/club/ClubRepository.java
Labels: 5PM🌝

#561 hotfix: Draw 시 전적 업데이트 되지 않는 이슈
  domain/src/main/java/org/badminton/domain/domain/match/entity/DoublesMatch.java
  domain/src/main/java/org/badminton/domain/domain/match/service/MatchRecordService.java
Labels: hotfix🥵

#563 refactor: JPA N+1 해결
  infrastructure/src/main/java/org/badminton/infrastructure/statistics/ClubStatisticsReaderImpl.java
  infrastructure/src/main/java/org/badminton/infrastructure/statistics/ClubStatisticsRepository.java
Labels: refactor✍️

#564 hotfix: JPA 쿼리 최적화
  domain/src/main/java/org/badminton/domain/domain/club/ClubPage.java
  domain/src/main/java/org/badminton/domain/domain/statistics/ClubStatisticsReader.java
  domain/src/main/java/org/badminton/domain/domain/statistics/ClubStatisticsServiceImpl.java
  infrastructure/src/main/java/org/badminton/infrastructure/club/ClubReaderImpl.java
  infrastructure/src/main/java/org/badminton/infrastructure/statistics/ClubStatisticsReaderImpl.java
  infrastructure/src/main/java/org/badminton/infrastructure/statistics/ClubStatisticsRepository.java
Labels: hotfix🥵

#566 refactor: 대진표 조회 API 쿼리 최적화
  infrastructure/src/main/java/org/badminton/infrastructure/match/reader/DoublesMatchReaderImpl.java
  infrastructure/src/main/java/org/badminton/infrastructure/match/reader/SinglesMatchReaderImpl.java
  infrastructure/src/main/java/org/badminton/infrastructure/match/repository/DoublesMatchRepository.java
  infrastructure/src/main/java/org/badminton/infrastructure/match/repository/SinglesMatchRepository.java
Labels: refactor✍️

#565 refactor: 동호회 조회수 기능에서 레디스락 제거, querydsl 로 직접 수정 쿼리 작성
  domain/src/main/java/org/badminton/domain/domain/statistics/ClubStatistics.java
  domain/src/main/java/org/badminton/domain/domain/statistics/ClubStatisticsRepositoryCustom.java
  domain/src/main/java/org/badminton/domain/domain/statistics/ClubStatisticsServiceImpl.java
  domain/src/main/java/org/badminton/domain/domain/statistics/ClubStatisticsStore.java
  domain/src/main/java/org/badminton/domain/domain/statistics/event/ReadClubEventHandler.java
  infrastructure/src/main/java/org/badminton/infrastructure/statistics/ClubStatisticsRepositoryImpl.java
  infrastructure/src/main/java/org/badminton/infrastructure/statistics/ClubStatisticsStoreImpl.java
Labels: beforeLunch🍕, refactor✍️

#567 hotfix: league id에 해당하는 in progress match 만 조회
  domain/src/main/java/org/badminton/domain/domain/match/vo/LeagueMatchSetRedisKey.java
  infrastructure/build.gradle
  infrastructure/src/main/java/org/badminton/infrastructure/match/repository/SetRepository.java
Labels: hotfix🥵, 5PM🌝

#569 hotfix: 동호회 신청 후 거절 시 다시 가입신청 안되는 이슈 해결
  infrastructure/src/main/java/org/badminton/infrastructure/club/ClubApplyReaderImpl.java
Labels: hotfix🥵

#570 hotfix: 경기 생성시 본인 티어보다 높은 티어의 경기 생성되는 것 검증
  api/src/main/java/org/badminton/api/application/league/LeagueFacade.java
  api/src/main/java/org/badminton/api/interfaces/league/controller/LeagueController.java
  domain/src/main/java/org/badminton/domain/common/error/ErrorCode.java
  domain/src/main/java/org/badminton/domain/common/exception/league/TierLimitException.java
  domain/src/main/java/org/badminton/domain/common/policy/ClubMemberPolicy.java
Labels: hotfix🥵

#571 hotfix: 에러 메시지 변경
  domain/src/main/java/org/badminton/domain/common/error/ErrorCode.java
Labels: hotfix🥵
