Repository Kernel360/F2_PLAY_BADMINTON_BE, pull requests merged in 2024-11, with the labels that each got.

#262 feat: 동호회 가입신청, 승인, 거절 시 메일 전송
  api/build.gradle
  api/src/main/java/org/badminton/api/application/clubMember/ClubMemberFacade.java
  api/src/main/java/org/badminton/api/application/mail/MailService.java
  api/src/main/java/org/badminton/api/config/mail/MailConfig.java
  api/src/main/java/org/badminton/api/config/security/SecurityConfig.java
  api/src/main/resources/application.yaml
  domain/src/main/java/org/badminton/domain/domain/clubmember/ClubMemberReader.java
  infrastructure/src/main/java/org/badminton/infrastructure/clubmember/ClubMemberReaderImpl.java
  infrastructure/src/main/java/org/badminton/infrastructure/clubmember/ClubMemberRepository.java
Labels: feat✨

#264 hotfix: pagination response 변경
  api/src/main/java/org/badminton/api/interfaces/club/controller/ClubController.java
  api/src/main/java/org/badminton/api/interfaces/club/dto/CustomPageResponse.java
Labels: hotfix🥵

#265 feat: 경기 리전 추가 및 validate
  api/src/main/java/org/badminton/api/application/league/LeagueFacade.java
  api/src/main/java/org/badminton/api/application/league/LeagueParticipationFacade.java
  api/src/main/java/org/badminton/api/common/exception/league/RecruitingClosedAtAfterLeagueAtException.java
  api/src/main/java/org/badminton/api/interfaces/league/controller/LeagueController.java
  api/src/main/java/org/badminton/api/interfaces/league/controller/LeagueParticipationController.java
  api/src/main/java/org/badminton/api/interfaces/league/dto/LeagueCreateRequest.java
  api/src/main/java/org/badminton/api/interfaces/league/dto/LeagueCreateResponse.java
  api/src/main/java/org/badminton/api/interfaces/league/dto/LeagueDetailsResponse.java
  api/src/main/java/org/badminton/api/interfaces/league/dto/LeagueReadResponse.java
  api/src/main/java/org/badminton/api/interfaces/league/dto/LeagueUpdateRequest.java
  api/src/main/java/org/badminton/api/interfaces/league/dto/LeagueUpdateResponse.java
  api/src/main/java/org/badminton/api/interfaces/match/dto/SetScoreUpdateRequest.java
  api/src/main/resources/data.sql
  domain/src/main/java/org/badminton/domain/common/consts/Constants.java
  domain/src/main/java/org/badminton/domain/common/error/ErrorCode.java
  domain/src/main/java/org/badminton/domain/common/exception/league/PlayerLimitCountDecreasedNotAllowedException.java
  domain/src/main/java/org/badminton/domain/common/exception/league/PlayerLimitCountMustBeMoreThanFourException.java
  domain/src/main/java/org/badminton/domain/common/exception/league/PlayerLimitCountMustBeMultipleWhenDoublesMatch.java
  domain/src/main/java/org/badminton/domain/domain/club/ClubServiceImpl.java
  domain/src/main/java/org/badminton/domain/domain/club/info/ClubSummaryInfo.java
  domain/src/main/java/org/badminton/domain/domain/league/LeagueParticipantService.java
  domain/src/main/java/org/badminton/domain/domain/league/LeagueParticipantServiceImpl.java
  domain/src/main/java/org/badminton/domain/domain/league/LeagueParticipantStore.java
  domain/src/main/java/org/badminton/domain/domain/league/LeagueService.java
  domain/src/main/java/org/badminton/domain/domain/league/LeagueServiceImpl.java
  domain/src/main/java/org/badminton/domain/domain/league/LeagueStore.java
  domain/src/main/java/org/badminton/domain/domain/league/command/LeagueCancelCommand.java
  domain/src/main/java/org/badminton/domain/domain/league/command/LeagueCreateCommand.java
  domain/src/main/java/org/badminton/domain/domain/league/command/LeagueCreateNoIncludeClubCommand.java
  domain/src/main/java/org/badminton/domain/domain/league/command/LeagueDetailCommand.java
  domain/src/main/java/org/badminton/domain/domain/league/command/LeagueUpdateCommand.java
  domain/src/main/java/org/badminton/domain/domain/league/command/LeagueUpdatedCommand.java
  domain/src/main/java/org/badminton/domain/domain/league/entity/League.java
  domain/src/main/java/org/badminton/domain/domain/league/info/LeagueCancelInfo.java
  domain/src/main/java/org/badminton/domain/domain/league/info/LeagueCreateInfo.java
  domain/src/main/java/org/badminton/domain/domain/league/info/LeagueDetailInfo.java
  domain/src/main/java/org/badminton/domain/domain/league/info/LeagueDetailsInfo.java
  domain/src/main/java/org/badminton/domain/domain/league/info/LeagueSummaryInfo.java
  domain/src/main/java/org/badminton/domain/domain/league/info/LeagueUpdateInfo.java
  domain/src/main/java/org/badminton/domain/domain/league/info/LeagueUpdateInfoWithParticipantCountInfo.java
  domain/src/main/java/org/badminton/domain/domain/league/vo/Address.java
  domain/src/main/java/org/badminton/domain/domain/league/vo/Team.java
  infrastructure/src/main/java/org/badminton/infrastructure/league/LeagueParticipantReaderImpl.java
  infrastructure/src/main/java/org/badminton/infrastructure/league/LeagueParticipantStoreImpl.java
  infrastructure/src/main/java/org/badminton/infrastructure/league/LeagueStoreImpl.java
Labels: 5PM🌝

#268 feat: 메일 기능 중 테이블 저장하기
  api/build.gradle
  api/src/main/java/org/badminton/api/application/clubMember/ClubMemberFacade.java
  api/src/main/java/org/badminton/api/interfaces/member/validator/MemberImageValidatorImpl.java
  batch/build.gradle
  batch/src/main/java/springproject/badmintonbatch/batch/config/BatchConfig.java
  batch/src/main/java/springproject/badmintonbatch/batch/config/MailConfig.java
  batch/src/main/java/springproject/badmintonbatch/batch/processor/MailItemProcessor.java
  batch/src/main/java/springproject/badmintonbatch/batch/processor/MemberItemProcessor.java
  batch/src/main/java/springproject/badmintonbatch/batch/reader/MailItemReader.java
  batch/src/main/java/springproject/badmintonbatch/batch/reader/MemberItemReader.java
  batch/src/main/java/springproject/badmintonbatch/batch/scheduler/BatchScheduler.java
  batch/src/main/java/springproject/badmintonbatch/batch/writer/MailItemWriter.java
  batch/src/main/java/springproject/badmintonbatch/batch/writer/MemberItemWriter.java
  batch/src/main/resources/application.yaml
  domain/src/main/java/org/badminton/domain/domain/mail/MailService.java
  domain/src/main/java/org/badminton/domain/domain/mail/MailServiceImpl.java
  domain/src/main/java/org/badminton/domain/domain/mail/MailStore.java
  domain/src/main/java/org/badminton/domain/domain/mail/entity/Mail.java
  infrastructure/src/main/java/org/badminton/infrastructure/mail/MailRepository.java
  infrastructure/src/main/java/org/badminton/infrastructure/mail/MailStoreImpl.java
Labels: feat✨

#269 feat: league status filtering in league main page
  api/src/main/java/org/badminton/api/interfaces/league/controller/MainLeagueController.java
  api/src/main/java/org/badminton/api/interfaces/league/validation/annotation/LeagueDescriptionValidator.java
  api/src/main/java/org/badminton/api/interfaces/league/validation/annotation/LeagueNameValidator.java
  api/src/main/java/org/badminton/api/interfaces/league/validation/validator/LeagueDescriptionValidatorImpl.java
  api/src/main/java/org/badminton/api/interfaces/league/validation/validator/LeagueNameValidatorImpl.java
  domain/src/main/java/org/badminton/domain/domain/league/LeagueReader.java
  domain/src/main/java/org/badminton/domain/domain/league/LeagueService.java
  domain/src/main/java/org/badminton/domain/domain/league/LeagueServiceImpl.java
  domain/src/main/java/org/badminton/domain/domain/league/enums/AllowedLeagueStatus.java
  domain/src/main/java/org/badminton/domain/domain/league/enums/LeagueStatus.java
  domain/src/main/java/org/badminton/domain/domain/league/enums/Region.java
  infrastructure/src/main/java/org/badminton/infrastructure/league/LeagueReaderImpl.java
  infrastructure/src/main/java/org/badminton/infrastructure/league/LeagueRepository.java
Labels: feat✨

#266 feat: Make list
  api/src/main/java/org/badminton/api/application/club/ClubFacade.java
  api/src/main/java/org/badminton/api/application/clubMember/ClubMemberFacade.java
  api/src/main/java/org/badminton/api/application/member/MemberFacade.java
  api/src/main/java/org/badminton/api/config/security/SecurityConfig.java
  api/src/main/java/org/badminton/api/interfaces/club/controller/ClubController.java
  api/src/main/java/org/badminton/api/interfaces/club/controller/ClubDtoMapper.java
  api/src/main/java/org/badminton/api/interfaces/club/dto/ClubApplicantResponse.java
  api/src/main/java/org/badminton/api/interfaces/club/dto/ClubApplyRequest.java
  api/src/main/java/org/badminton/api/interfaces/clubmember/ClubMemberDtoMapper.java
  api/src/main/java/org/badminton/api/interfaces/clubmember/controller/ClubMemberController.java
  api/src/main/java/org/badminton/api/interfaces/clubmember/dto/ClubApplyResponse.java
  api/src/main/java/org/badminton/api/interfaces/member/MemberDtoMapper.java
  api/src/main/java/org/badminton/api/interfaces/member/controller/MemberController.java
  api/src/main/java/org/badminton/api/interfaces/member/dto/MemberMyPageResponse.java
  domain/src/main/java/org/badminton/domain/domain/club/ClubApplyReader.java
  domain/src/main/java/org/badminton/domain/domain/club/ClubApplyService.java
  domain/src/main/java/org/badminton/domain/domain/club/ClubApplyServiceImpl.java
  domain/src/main/java/org/badminton/domain/domain/club/ClubService.java
  domain/src/main/java/org/badminton/domain/domain/club/ClubServiceImpl.java
  domain/src/main/java/org/badminton/domain/domain/club/command/ClubApplyCommand.java
  domain/src/main/java/org/badminton/domain/domain/club/entity/ClubApply.java
  domain/src/main/java/org/badminton/domain/domain/club/info/ClubApplicantInfo.java
  domain/src/main/java/org/badminton/domain/domain/clubmember/info/ApplyClubInfo.java
  domain/src/main/java/org/badminton/domain/domain/clubmember/service/ClubMemberService.java
  domain/src/main/java/org/badminton/domain/domain/clubmember/service/ClubMemberServiceImpl.java
  domain/src/main/java/org/badminton/domain/domain/member/service/MemberService.java
  infrastructure/src/main/java/org/badminton/infrastructure/club/ClubApplyReaderImpl.java
  infrastructure/src/main/java/org/badminton/infrastructure/club/ClubApplyRepository.java
Labels: feat✨

#271 feat: recently-created-club-list
  api/src/main/java/org/badminton/api/application/club/ClubRankFacade.java
  api/src/main/java/org/badminton/api/interfaces/club/controller/ClubController.java
  api/src/main/resources/data.sql
  domain/src/main/java/org/badminton/domain/domain/club/ClubReader.java
  domain/src/main/java/org/badminton/domain/domain/club/ClubService.java
  domain/src/main/java/org/badminton/domain/domain/club/ClubServiceImpl.java
  infrastructure/src/main/java/org/badminton/infrastructure/club/ClubReaderImpl.java
  infrastructure/src/main/java/org/badminton/infrastructure/club/ClubRepository.java
Labels: feat✨

#274 refactor: league owner cannot cancel league participation
  api/src/main/java/org/badminton/api/application/league/LeagueFacade.java
  api/src/main/java/org/badminton/api/application/league/LeagueParticipationFacade.java
  api/src/main/java/org/badminton/api/interfaces/league/controller/LeagueController.java
  api/src/main/java/org/badminton/api/interfaces/league/dto/LeagueCreateRequest.java
  api/src/main/resources/data.sql
  domain/src/main/java/org/badminton/domain/common/error/ErrorCode.java
  domain/src/main/java/org/badminton/domain/common/exception/league/LeagueCannotBeCanceledWhenIsNotRecruiting.java
  domain/src/main/java/org/badminton/domain/common/exception/league/LeagueOwnerCannotCancelLeagueParticipationException.java
  domain/src/main/java/org/badminton/domain/common/exception/league/LeagueParticipationDuplicateException.java
  domain/src/main/java/org/badminton/domain/domain/clubmember/ClubMemberReader.java
  domain/src/main/java/org/badminton/domain/domain/league/LeagueParticipantServiceImpl.java
  domain/src/main/java/org/badminton/domain/domain/league/LeagueService.java
  domain/src/main/java/org/badminton/domain/domain/league/LeagueServiceImpl.java
  domain/src/main/java/org/badminton/domain/domain/league/command/LeagueCreateCommand.java
  domain/src/main/java/org/badminton/domain/domain/league/command/LeagueUpdatedCommand.java
  domain/src/main/java/org/badminton/domain/domain/league/entity/League.java
  domain/src/main/java/org/badminton/domain/domain/league/info/LeagueCreateInfo.java
  infrastructure/src/main/java/org/badminton/infrastructure/clubmember/ClubMemberReaderImpl.java
  infrastructure/src/main/java/org/badminton/infrastructure/clubmember/ClubMemberRepository.java
Labels: 5PM🌝, refactor✍️

#276 feat: Apply Querydsl
  .gitignore
  api/src/main/java/org/badminton/api/config/jpa/JpaConfig.java
  api/src/main/resources/data.sql
  build.gradle
  domain/build.gradle
  domain/src/main/java/org/badminton/domain/domain/clubmember/ClubMemberReader.java
  domain/src/main/java/org/badminton/domain/domain/match/reader/DoublesMatchRepositoryCustom.java
  domain/src/main/java/org/badminton/domain/domain/match/reader/SinglesMatchRepositoryCustom.java
  domain/src/main/java/org/badminton/domain/domain/match/store/DoublesMatchReader.java
  domain/src/main/java/org/badminton/domain/domain/statistics/ClubStatisticsRepositoryCustom.java
  infrastructure/build.gradle
  infrastructure/src/main/java/org/badminton/infrastructure/clubmember/ClubMemberReaderImpl.java
  infrastructure/src/main/java/org/badminton/infrastructure/clubmember/ClubMemberRepository.java
  infrastructure/src/main/java/org/badminton/infrastructure/match/reader/DoublesMatchReaderImpl.java
  infrastructure/src/main/java/org/badminton/infrastructure/match/reader/SinglesMatchReaderImpl.java
  infrastructure/src/main/java/org/badminton/infrastructure/match/repository/DoublesMatchRepository.java
  infrastructure/src/main/java/org/badminton/infrastructure/match/repository/DoublesMatchRepositoryImpl.java
  infrastructure/src/main/java/org/badminton/infrastructure/match/repository/SinglesMatchRepository.java
  infrastructure/src/main/java/org/badminton/infrastructure/match/repository/SinglesMatchRepositoryImpl.java
  infrastructure/src/main/java/org/badminton/infrastructure/statistics/ClubStatisticsReaderImpl.java
  infrastructure/src/main/java/org/badminton/infrastructure/statistics/ClubStatisticsRepository.java
  infrastructure/src/main/java/org/badminton/infrastructure/statistics/ClubStatisticsRepositoryImpl.java
Labels: feat✨

#277 feat: 403에러 핸들링
  api/src/main/java/org/badminton/api/common/exception/oauth/JwtCookieNotFoundException.java
  api/src/main/java/org/badminton/api/config/security/SecurityConfig.java
  api/src/main/java/org/badminton/api/exceptionhandler/FailedAuthenticationEntryPoint.java
  domain/src/main/java/org/badminton/domain/common/exception/BadmintonException.java
Labels: beforeLunch🍕

#278 feat: 프론트 로그인 세션 확인용 API
  api/src/main/java/org/badminton/api/application/member/MemberFacade.java
  api/src/main/java/org/badminton/api/interfaces/member/MemberDtoMapper.java
  api/src/main/java/org/badminton/api/interfaces/member/controller/MemberController.java
  api/src/main/java/org/badminton/api/interfaces/member/dto/SimpleMemberResponse.java
  domain/src/main/java/org/badminton/domain/domain/member/info/SimpleMemberInfo.java
  domain/src/main/java/org/badminton/domain/domain/member/service/MemberService.java
  domain/src/main/java/org/badminton/domain/domain/member/service/MemberServiceImpl.java
Labels: beforeLunch🍕

#280 bug : 배포 수정파일
  .github/workflows/ci-cd-build.yml
  api/src/main/resources/logback-spring.xml
  batch/src/main/java/springproject/badmintonbatch/config/jpa/JpaConfig.java
  batch/src/main/resources/logback-spring.xml
  docker-compose.yaml
Labels: hotfix🥵, now❗️

#279 refactor: league id 추가 및 data.sql 수정
  api/src/main/java/org/badminton/api/interfaces/league/controller/MainLeagueController.java
  api/src/main/java/org/badminton/api/interfaces/league/dto/OngoingAndUpcomingLeagueResponse.java
  api/src/main/resources/data.sql
  domain/src/main/java/org/badminton/domain/domain/league/info/OngoingAndUpcomingLeagueInfo.java
Labels: now❗️, refactor✍️

#282 fix: Duplicate name. Participate League Contraint
  domain/src/main/java/org/badminton/domain/common/exception/league/ParticipationLimitReachedException.java
  domain/src/main/java/org/badminton/domain/domain/club/ClubReader.java
  domain/src/main/java/org/badminton/domain/domain/club/ClubServiceImpl.java
  domain/src/main/java/org/badminton/domain/domain/league/LeagueParticipantServiceImpl.java
  infrastructure/src/main/java/org/badminton/infrastructure/club/ClubReaderImpl.java
  infrastructure/src/main/java/org/badminton/infrastructure/club/ClubRepository.java
Labels: fix🛠️

#286 feat: 메인페이지 페이지네이션 추가
  api/src/main/java/org/badminton/api/interfaces/league/controller/MainLeagueController.java
  domain/src/main/java/org/badminton/domain/domain/league/LeagueReader.java
  domain/src/main/java/org/badminton/domain/domain/league/LeagueService.java
  domain/src/main/java/org/badminton/domain/domain/league/LeagueServiceImpl.java
  infrastructure/src/main/java/org/badminton/infrastructure/league/LeagueReaderImpl.java
  infrastructure/src/main/java/org/badminton/infrastructure/league/LeagueRepository.java
Labels: feat✨

#289 refactor: 동호회 별 클럽맴버 리턴 값 수정
  api/src/main/java/org/badminton/api/application/club/ClubFacade.java
  api/src/main/java/org/badminton/api/interfaces/club/dto/ClubCardResponse.java
  api/src/main/java/org/badminton/api/interfaces/club/dto/ClubDetailsResponse.java
  domain/src/main/java/org/badminton/domain/domain/club/ClubPage.java
  domain/src/main/java/org/badminton/domain/domain/club/ClubServiceImpl.java
  domain/src/main/java/org/badminton/domain/domain/club/info/ClubCardInfo.java
  domain/src/main/java/org/badminton/domain/domain/club/info/ClubDetailsInfo.java
  domain/src/main/java/org/badminton/domain/domain/clubmember/service/ClubMemberServiceImpl.java
Labels: beforeLunch🍕

#287 feat: 이름 수정 추가
  api/src/main/java/org/badminton/api/application/member/MemberFacade.java
  api/src/main/java/org/badminton/api/interfaces/member/MemberDtoMapper.java
  api/src/main/java/org/badminton/api/interfaces/member/controller/MemberController.java
  api/src/main/java/org/badminton/api/interfaces/member/dto/MemberUpdateRequest.java
  domain/src/main/java/org/badminton/domain/domain/member/command/MemberUpdateCommand.java
  domain/src/main/java/org/badminton/domain/domain/member/entity/Member.java
  domain/src/main/java/org/badminton/domain/domain/member/service/MemberService.java
  domain/src/main/java/org/badminton/domain/domain/member/service/MemberServiceImpl.java
Labels: feat✨

#290 feat: 회원 경기 기록 페이지네이션 추가
  api/src/main/java/org/badminton/api/interfaces/member/controller/MemberController.java
Labels: feat✨

#288 refactor: set status enum
  domain/src/main/java/org/badminton/domain/domain/match/entity/DoublesSet.java
  domain/src/main/java/org/badminton/domain/domain/match/entity/SinglesSet.java
Labels: beforeLunch🍕, refactor✍️

#292 bug: sql-show 수정 및 로그필터 수정
  api/src/main/java/org/badminton/api/filter/LoggerFilter.java
  api/src/main/resources/application.yaml
  batch/src/main/resources/application.yaml
Labels: 5PM🌝

#293 refactor: club 트랜잭션 추가
  api/src/main/java/org/badminton/api/application/club/ClubFacade.java
  api/src/main/java/org/badminton/api/application/club/ClubRankFacade.java
  domain/src/main/java/org/badminton/domain/domain/club/ClubServiceImpl.java
  domain/src/main/java/org/badminton/domain/domain/clubmember/service/ClubMemberServiceImpl.java
  domain/src/main/java/org/badminton/domain/domain/statistics/ClubStatisticsServiceImpl.java
  infrastructure/src/main/java/org/badminton/infrastructure/club/ClubStoreImpl.java
Labels: refactor✍️

#294 docs: response에 스웨거 스키마 추가
  api/src/main/java/org/badminton/api/interfaces/clubmember/dto/ApproveApplyResponse.java
  api/src/main/java/org/badminton/api/interfaces/clubmember/dto/ClubApplyResponse.java
  api/src/main/java/org/badminton/api/interfaces/clubmember/dto/ClubMemberBanRecordResponse.java
  api/src/main/java/org/badminton/api/interfaces/clubmember/dto/ClubMemberBanRequest.java
  api/src/main/java/org/badminton/api/interfaces/clubmember/dto/ClubMemberJoinResponse.java
  api/src/main/java/org/badminton/api/interfaces/clubmember/dto/ClubMemberResponse.java
  api/src/main/java/org/badminton/api/interfaces/clubmember/dto/ClubMemberStatusResponse.java
  api/src/main/java/org/badminton/api/interfaces/clubmember/dto/ClubMemberWithdrawResponse.java
  api/src/main/java/org/badminton/api/interfaces/clubmember/dto/RejectApplyResponse.java
  api/src/main/java/org/badminton/api/interfaces/match/dto/BracketResponse.java
  api/src/main/java/org/badminton/api/interfaces/match/dto/DoublesMatchPlayerResponse.java
  api/src/main/java/org/badminton/api/interfaces/match/dto/DoublesMatchResponse.java
  api/src/main/java/org/badminton/api/interfaces/match/dto/DoublesMatchResultResponse.java
  api/src/main/java/org/badminton/api/interfaces/match/dto/DoublesSetResponse.java
  api/src/main/java/org/badminton/api/interfaces/match/dto/LeagueSetsScoreInProgressResponse.java
  api/src/main/java/org/badminton/api/interfaces/match/dto/MatchDetailsResponse.java
  api/src/main/java/org/badminton/api/interfaces/match/dto/MatchResultResponse.java
  api/src/main/java/org/badminton/api/interfaces/match/dto/MatchSetResponse.java
  api/src/main/java/org/badminton/api/interfaces/match/dto/SetScoreResponse.java
  api/src/main/java/org/badminton/api/interfaces/match/dto/SetScoreUpdateResponse.java
  api/src/main/java/org/badminton/api/interfaces/match/dto/SinglesMatchPlayerResponse.java
  api/src/main/java/org/badminton/api/interfaces/match/dto/SinglesMatchResponse.java
  api/src/main/java/org/badminton/api/interfaces/match/dto/SinglesMatchResultResponse.java
  api/src/main/java/org/badminton/api/interfaces/match/dto/SinglesSetResponse.java
  api/src/main/java/org/badminton/api/interfaces/match/dto/TeamResponse.java
  api/src/main/java/org/badminton/api/interfaces/match/dto/TeamResultResponse.java
  domain/src/main/java/org/badminton/domain/domain/match/info/SetInfo.java
Labels: docs📉, beforeLunch🍕

#296 refactor: member 트랜잭션 추가
  api/src/main/java/org/badminton/api/application/match/MyMatchFacade.java
  api/src/main/java/org/badminton/api/application/member/MemberFacade.java
  api/src/main/java/org/badminton/api/interfaces/clubmember/dto/ClubMemberMyPageResponse.java
  api/src/main/java/org/badminton/api/interfaces/member/MemberDtoMapper.java
  api/src/main/java/org/badminton/api/interfaces/member/controller/MemberController.java
  api/src/main/java/org/badminton/api/interfaces/member/dto/MemberMyPageResponse.java
  domain/src/main/java/org/badminton/domain/domain/clubmember/service/ClubMemberService.java
  domain/src/main/java/org/badminton/domain/domain/clubmember/service/ClubMemberServiceImpl.java
  domain/src/main/java/org/badminton/domain/domain/league/service/LeagueRecordServiceImpl.java
  domain/src/main/java/org/badminton/domain/domain/match/service/MatchResultService.java
  domain/src/main/java/org/badminton/domain/domain/member/info/MemberMyPageInfo.java
  domain/src/main/java/org/badminton/domain/domain/member/service/MemberServiceImpl.java
Labels: 5PM🌝

#297 feat: 토너먼트 경기 관련 로직 구현
  api/src/main/java/org/badminton/api/application/league/LeagueFacade.java
  api/src/main/java/org/badminton/api/application/match/FreeMatchFacade.java
  api/src/main/java/org/badminton/api/application/match/MatchFacade.java
  api/src/main/java/org/badminton/api/application/match/MatchOperationHandler.java
  api/src/main/java/org/badminton/api/application/match/TournamentMatchFacade.java
  api/src/main/java/org/badminton/api/interfaces/league/dto/LeagueCreateRequest.java
  api/src/main/java/org/badminton/api/interfaces/match/controller/MatchController.java
  api/src/main/java/org/badminton/api/interfaces/match/dto/BracketResponse.java
  api/src/main/java/org/badminton/api/interfaces/match/dto/TeamResponse.java
  domain/src/main/java/org/badminton/domain/common/enums/BracketType.java
  domain/src/main/java/org/badminton/domain/common/error/ErrorCode.java
  domain/src/main/java/org/badminton/domain/common/exception/league/LeagueParticipantsCountException.java
  domain/src/main/java/org/badminton/domain/domain/league/LeagueParticipantReader.java
  domain/src/main/java/org/badminton/domain/domain/league/LeagueReader.java
  domain/src/main/java/org/badminton/domain/domain/league/entity/League.java
  domain/src/main/java/org/badminton/domain/domain/match/entity/DoublesMatch.java
  domain/src/main/java/org/badminton/domain/domain/match/entity/SinglesMatch.java
  domain/src/main/java/org/badminton/domain/domain/match/info/BracketInfo.java
  domain/src/main/java/org/badminton/domain/domain/match/info/SinglesMatchInfo.java
  domain/src/main/java/org/badminton/domain/domain/match/info/TeamInfo.java
  domain/src/main/java/org/badminton/domain/domain/match/service/AbstractDoublesMatchStrategy.java
  domain/src/main/java/org/badminton/domain/domain/match/service/AbstractMatchRetrieveService.java
  domain/src/main/java/org/badminton/domain/domain/match/service/AbstractSinglesMatchStrategy.java
  domain/src/main/java/org/badminton/domain/domain/match/service/BracketGenerationService.java
  domain/src/main/java/org/badminton/domain/domain/match/service/MatchRetrieveService.java
  domain/src/main/java/org/badminton/domain/domain/match/service/MatchStrategy.java
  domain/src/main/java/org/badminton/domain/domain/match/store/DoublesMatchReader.java
  domain/src/main/java/org/badminton/domain/domain/match/store/SinglesMatchReader.java
  infrastructure/src/main/java/org/badminton/infrastructure/league/LeagueParticipantReaderImpl.java
  infrastructure/src/main/java/org/badminton/infrastructure/league/LeagueReaderImpl.java
  infrastructure/src/main/java/org/badminton/infrastructure/league/LeagueRepository.java
  infrastructure/src/main/java/org/badminton/infrastructure/match/reader/DoublesMatchReaderImpl.java
  infrastructure/src/main/java/org/badminton/infrastructure/match/reader/SinglesMatchReaderImpl.java
  infrastructure/src/main/java/org/badminton/infrastructure/match/repository/DoublesMatchRepository.java
  infrastructure/src/main/java/org/badminton/infrastructure/match/repository/SinglesMatchRepository.java
  infrastructure/src/main/java/org/badminton/infrastructure/match/service/BracketGenerationServiceImpl.java
  infrastructure/src/main/java/org/badminton/infrastructure/match/service/FreeBracketGenerationServiceImpl.java
  infrastructure/src/main/java/org/badminton/infrastructure/match/service/FreeMatchProgressServiceImpl.java
  infrastructure/src/main/java/org/badminton/infrastructure/match/service/FreeMatchRetrieveServiceImpl.java
  infrastructure/src/main/java/org/badminton/infrastructure/match/service/MatchRetrieveServiceImpl.java
  infrastructure/src/main/java/org/badminton/infrastructure/match/service/TournamentBracketGenerationServiceImpl.java
  infrastructure/src/main/java/org/badminton/infrastructure/match/service/TournamentMatchProgressServiceImpl.java
  infrastructure/src/main/java/org/badminton/infrastructure/match/service/TournamentMatchRetrieveServiceImpl.java
  infrastructure/src/main/java/org/badminton/infrastructure/match/strategy/FreeDoublesMatchStrategy.java
  infrastructure/src/main/java/org/badminton/infrastructure/match/strategy/FreeSinglesMatchStrategy.java
  infrastructure/src/main/java/org/badminton/infrastructure/match/strategy/MatchUtils.java
  infrastructure/src/main/java/org/badminton/infrastructure/match/strategy/TournamentDoublesMatchStrategy.java
  infrastructure/src/main/java/org/badminton/infrastructure/match/strategy/TournamentSinglesMatchStrategy.java
Labels: feat✨

#300 refacotr: response 추가
  api/src/main/java/org/badminton/api/interfaces/match/dto/BracketResponse.java
  api/src/main/java/org/badminton/api/interfaces/match/dto/DoublesMatchResponse.java
  api/src/main/java/org/badminton/api/interfaces/match/dto/SinglesMatchResponse.java
  domain/src/main/java/org/badminton/domain/domain/match/info/BracketInfo.java
  domain/src/main/java/org/badminton/domain/domain/match/info/DoublesMatchInfo.java
  domain/src/main/java/org/badminton/domain/domain/match/info/SinglesMatchInfo.java
Labels: refactor✍️

#301 feat : 경기, 경기 참여 자동 생성기
  batch/src/main/java/springproject/badmintonbatch/batch/config/EmailBatchConfig.java
  batch/src/main/java/springproject/badmintonbatch/batch/config/SqlBotConfig.java
  batch/src/main/java/springproject/badmintonbatch/batch/processor/LeagueItemProcessor.java
  batch/src/main/java/springproject/badmintonbatch/batch/processor/LeagueParticipantProcessor.java
  batch/src/main/java/springproject/badmintonbatch/batch/reader/LeagueParticipantReader.java
  batch/src/main/java/springproject/badmintonbatch/batch/reader/LeagueReader.java
  batch/src/main/java/springproject/badmintonbatch/batch/scheduler/LeagueScheduler.java
  batch/src/main/java/springproject/badmintonbatch/batch/writer/LeagueItemWriter.java
  batch/src/main/java/springproject/badmintonbatch/batch/writer/LeagueParticipantWriter.java
  batch/src/main/java/springproject/badmintonbatch/config/jpa/JpaConfig.java
  batch/src/main/resources/data.sql
  domain/src/main/java/org/badminton/domain/domain/club/ClubReader.java
  infrastructure/src/main/java/org/badminton/infrastructure/club/ClubReaderImpl.java
  infrastructure/src/main/java/org/badminton/infrastructure/clubmember/ClubMemberRepository.java
  infrastructure/src/main/java/org/badminton/infrastructure/league/LeagueParticipantRepository.java
  infrastructure/src/main/java/org/badminton/infrastructure/league/LeagueRepository.java
Labels: 5PM🌝

#302 feat : 경기 상태별, 지역별 조회
  domain/src/main/java/org/badminton/domain/domain/league/LeagueReader.java
  domain/src/main/java/org/badminton/domain/domain/league/LeagueServiceImpl.java
  domain/src/main/java/org/badminton/domain/domain/league/enums/Region.java
  domain/src/main/java/org/badminton/domain/domain/league/vo/LeagueSearchStrategy.java
  infrastructure/src/main/java/org/badminton/infrastructure/league/LeagueReaderImpl.java
  infrastructure/src/main/java/org/badminton/infrastructure/league/LeagueRepository.java
Labels: 5PM🌝

#303 feat: match 완료 시 leagueRecord 업데이트
  api/src/main/java/org/badminton/api/application/match/FreeMatchFacade.java
  api/src/main/java/org/badminton/api/application/match/TournamentMatchFacade.java
  api/src/main/resources/data.sql
  domain/src/main/java/org/badminton/domain/domain/match/service/MatchRecordService.java
Labels: feat✨

#305 feat: check clubMember
  api/src/main/java/org/badminton/api/application/clubMember/ClubMemberFacade.java
  api/src/main/java/org/badminton/api/interfaces/clubmember/ClubMemberDtoMapper.java
  api/src/main/java/org/badminton/api/interfaces/clubmember/controller/ClubMemberController.java
  api/src/main/java/org/badminton/api/interfaces/clubmember/dto/MemberIsClubMemberResponse.java
  domain/src/main/java/org/badminton/domain/domain/clubmember/info/MemberIsClubMemberInfo.java
  domain/src/main/java/org/badminton/domain/domain/clubmember/service/ClubMemberService.java
  domain/src/main/java/org/badminton/domain/domain/clubmember/service/ClubMemberServiceImpl.java
  domain/src/main/java/org/badminton/domain/domain/member/info/MemberIsClubMemberInfo.java
Labels: feat✨

#307 refactor: clubMemberIsDeleted 추가
  infrastructure/src/main/java/org/badminton/infrastructure/clubmember/ClubMemberReaderImpl.java
  infrastructure/src/main/java/org/badminton/infrastructure/clubmember/ClubMemberRepository.java
Labels: fix🛠️

#308 bug : 경기 조회 시 일자 별 조회 버그 수정
  domain/src/main/java/org/badminton/domain/domain/league/LeagueServiceImpl.java
Labels: fix🛠️

#309 fix: edit response
  api/src/main/java/org/badminton/api/interfaces/clubmember/ClubMemberDtoMapper.java
  api/src/main/java/org/badminton/api/interfaces/clubmember/controller/ClubMemberController.java
  api/src/main/java/org/badminton/api/interfaces/clubmember/dto/ClubMemberRoleResponse.java
Labels: fix🛠️

#310 fix: dtoMapper
  api/src/main/java/org/badminton/api/interfaces/clubmember/ClubMemberDtoMapper.java
  api/src/main/java/org/badminton/api/interfaces/clubmember/controller/ClubMemberController.java
  api/src/main/java/org/badminton/api/interfaces/clubmember/dto/ClubMemberRoleResponse.java
Labels: fix🛠️

#311 refactor: doublesMatch, singlesMatch Response 변경
  api/src/main/java/org/badminton/api/config/security/SecurityConfig.java
  api/src/main/java/org/badminton/api/interfaces/match/dto/BracketResponse.java
  api/src/main/java/org/badminton/api/interfaces/match/dto/DoublesMatchResponse.java
  api/src/main/java/org/badminton/api/interfaces/match/dto/MatchTeamResponse.java
  api/src/main/java/org/badminton/api/interfaces/match/dto/Participant.java
  api/src/main/java/org/badminton/api/interfaces/match/dto/SinglesMatchResponse.java
  api/src/main/java/org/badminton/api/interfaces/match/dto/TeamResponse.java
  domain/src/main/java/org/badminton/domain/domain/match/info/BracketInfo.java
  domain/src/main/java/org/badminton/domain/domain/match/info/DoublesMatchInfo.java
  domain/src/main/java/org/badminton/domain/domain/match/info/MatchTeamInfo.java
  domain/src/main/java/org/badminton/domain/domain/match/info/SinglesMatchInfo.java
Labels: refactor✍️

#312 fix: delete file
  api/src/main/java/org/badminton/api/interfaces/match/dto/TeamResponse.java
Labels: fix🛠️

#314 refactor: 동호회 회원 전체 조회시 경기전적과 티어 response에 추가
  api/src/main/java/org/badminton/api/interfaces/clubmember/dto/ClubMemberResponse.java
  domain/src/main/java/org/badminton/domain/domain/clubmember/info/ClubMemberInfo.java
Labels: refactor✍️

#316 fix: 정지 여부, 기간 response에 추가
  api/src/main/java/org/badminton/api/interfaces/clubmember/dto/ClubMemberResponse.java
  domain/src/main/java/org/badminton/domain/domain/clubmember/info/ClubMemberInfo.java
  infrastructure/src/main/java/org/badminton/infrastructure/clubmember/ClubMemberReaderImpl.java
  infrastructure/src/main/java/org/badminton/infrastructure/clubmember/ClubMemberRepository.java
Labels: fix🛠️

#317 feat: 배치 설정 파일
  batch/src/main/resources/application.yaml
  batch/src/main/resources/data.sql
Labels: beforeLunch🍕

#319 refactor: 일별경기 조회 response 변경
  api/src/main/java/org/badminton/api/interfaces/league/controller/LeagueController.java
  api/src/main/java/org/badminton/api/interfaces/league/controller/LeagueDtoMapper.java
  api/src/main/java/org/badminton/api/interfaces/league/dto/LeagueByDateResponse.java
  domain/src/main/java/org/badminton/domain/domain/league/info/LeagueByDateInfo.java
  domain/src/main/java/org/badminton/domain/domain/league/info/LeagueByDateInfoWithParticipantCountInfo.java
Labels: refactor✍️

#320 fix: add use badminton
  batch/src/main/resources/data.sql
Labels: fix🛠️

#321 refactor: data.sql
  api/src/main/java/org/badminton/api/interfaces/league/dto/LeagueCreateRequest.java
  api/src/main/resources/data.sql
Labels: docs📉

#322 refactor: data.sql
  api/src/main/resources/data.sql
Labels: docs📉

#331 bug: 403에러 200으로 핸들링
  api/src/main/java/org/badminton/api/config/security/SecurityConfig.java
Labels: hotfix🥵, beforeLunch🍕

#330 refactor: add custom exception for deleting league
  domain/src/main/java/org/badminton/domain/domain/club/ClubReader.java
  domain/src/main/java/org/badminton/domain/domain/club/ClubServiceImpl.java
  infrastructure/src/main/java/org/badminton/infrastructure/club/ClubReaderImpl.java
  infrastructure/src/main/java/org/badminton/infrastructure/club/ClubRepository.java
Labels: refactor✍️

#332 refactor: swagger-description
  api/src/main/java/org/badminton/api/interfaces/club/dto/ClubApplyRequest.java
  api/src/main/java/org/badminton/api/interfaces/clubmember/controller/ClubMemberController.java
  api/src/main/java/org/badminton/api/interfaces/league/controller/LeagueController.java
  api/src/main/java/org/badminton/api/interfaces/league/controller/MainLeagueController.java
  api/src/main/java/org/badminton/api/interfaces/match/controller/MatchController.java
  api/src/main/java/org/badminton/api/interfaces/member/controller/MemberController.java
  domain/src/main/java/org/badminton/domain/common/consts/Constants.java
Labels: refactor✍️

#333 refactor: league create request schema
  api/src/main/java/org/badminton/api/interfaces/league/dto/LeagueCreateRequest.java
  domain/src/main/java/org/badminton/domain/common/error/ErrorCode.java
  domain/src/main/java/org/badminton/domain/domain/club/entity/Club.java
  domain/src/main/java/org/badminton/domain/domain/league/command/LeagueCreateCommand.java
  domain/src/main/java/org/badminton/domain/domain/league/command/LeagueCreateNoIncludeClubCommand.java
  domain/src/main/java/org/badminton/domain/domain/league/entity/League.java
Labels: refactor✍️

#338 refactor: add exception
  domain/src/main/java/org/badminton/domain/common/error/ErrorCode.java
  domain/src/main/java/org/badminton/domain/common/exception/match/LeagueParticipantsNotExistsException.java
  infrastructure/src/main/java/org/badminton/infrastructure/match/strategy/TournamentDoublesMatchStrategy.java
  infrastructure/src/main/java/org/badminton/infrastructure/match/strategy/TournamentSinglesMatchStrategy.java
Labels: refactor✍️

#339 refactor: block updating canceled league
  domain/build.gradle
  domain/src/main/java/org/badminton/domain/common/error/ErrorCode.java
  domain/src/main/java/org/badminton/domain/common/exception/league/LeagueAlreadyCanceledException.java
  domain/src/main/java/org/badminton/domain/domain/league/LeagueReader.java
  domain/src/main/java/org/badminton/domain/domain/league/LeagueServiceImpl.java
  infrastructure/build.gradle
  infrastructure/src/main/java/org/badminton/infrastructure/league/LeagueReaderImpl.java
  infrastructure/src/main/java/org/badminton/infrastructure/league/LeagueRepository.java
  infrastructure/src/test/java/org/badminton/infrastructure/club/ClubReaderImplTest.java
  infrastructure/src/test/java/org/badminton/infrastructure/club/JdbcTemplateClubRepository.java
  infrastructure/src/test/java/org/badminton/infrastructure/club/TestConfig.java
Labels: refactor✍️

#344 feat: Add match response
  api/src/main/java/org/badminton/api/interfaces/match/dto/MatchTeamResponse.java
  api/src/main/java/org/badminton/api/interfaces/match/dto/Participant.java
  api/src/main/java/org/badminton/api/interfaces/match/dto/SinglesMatchResponse.java
  domain/src/main/java/org/badminton/domain/domain/match/info/MatchTeamInfo.java
  domain/src/main/java/org/badminton/domain/domain/match/info/SinglesMatchInfo.java
  infrastructure/src/main/java/org/badminton/infrastructure/match/strategy/FreeDoublesMatchStrategy.java
  infrastructure/src/main/java/org/badminton/infrastructure/match/strategy/FreeSinglesMatchStrategy.java
  infrastructure/src/main/java/org/badminton/infrastructure/match/strategy/TournamentDoublesMatchStrategy.java
  infrastructure/src/main/java/org/badminton/infrastructure/match/strategy/TournamentSinglesMatchStrategy.java
Labels: feat✨

#345 fix: filter
  api/src/main/java/org/badminton/api/config/security/SecurityConfig.java
Labels: fix🛠️

#346 fix: filter-list
  api/src/main/java/org/badminton/api/config/security/SecurityConfig.java
Labels: fix🛠️

#348 fix:delete-isMemberClub
  api/src/main/java/org/badminton/api/application/club/ClubFacade.java
  api/src/main/java/org/badminton/api/interfaces/club/controller/ClubController.java
  api/src/main/java/org/badminton/api/interfaces/club/dto/ClubDetailsResponse.java
  domain/src/main/java/org/badminton/domain/domain/club/info/ClubDetailsInfo.java
Labels: fix🛠️

#349 feat : 경기 일자가 지난 경기에 대한 종료
  batch/src/main/java/springproject/badmintonbatch/batch/config/LeagueBatchConfig.java
  batch/src/main/java/springproject/badmintonbatch/batch/config/SqlBotConfig.java
  batch/src/main/java/springproject/badmintonbatch/batch/processor/LeagueItemProcessor.java
  batch/src/main/java/springproject/badmintonbatch/batch/processor/LeagueParticipantProcessor.java
  batch/src/main/java/springproject/badmintonbatch/batch/reader/LeagueItemReader.java
  batch/src/main/java/springproject/badmintonbatch/batch/reader/LeagueParticipantReader.java
  batch/src/main/java/springproject/badmintonbatch/batch/reader/LeagueReader.java
  batch/src/main/java/springproject/badmintonbatch/batch/scheduler/BatchScheduler.java
  batch/src/main/java/springproject/badmintonbatch/batch/scheduler/LeagueScheduler.java
  batch/src/main/java/springproject/badmintonbatch/batch/writer/LeagueItemWriter.java
  batch/src/main/java/springproject/badmintonbatch/batch/writer/LeagueParticipantWriter.java
  domain/src/main/java/org/badminton/domain/domain/match/entity/DoublesMatch.java
  domain/src/main/java/org/badminton/domain/domain/match/entity/SinglesMatch.java
  domain/src/main/java/org/badminton/domain/domain/match/entity/SinglesSet.java
  infrastructure/src/main/java/org/badminton/infrastructure/league/LeagueRepository.java
Labels: feat✨

#352 feat : 리그 중복 생성 방지
  api/src/main/java/org/badminton/api/interfaces/league/controller/LeagueController.java
  domain/src/main/java/org/badminton/domain/common/error/ErrorCode.java
  domain/src/main/java/org/badminton/domain/common/exception/league/LeagueCreationWithin3HoursException.java
  domain/src/main/java/org/badminton/domain/domain/league/LeagueReader.java
  domain/src/main/java/org/badminton/domain/domain/league/LeagueServiceImpl.java
  infrastructure/src/main/java/org/badminton/infrastructure/league/LeagueReaderImpl.java
  infrastructure/src/main/java/org/badminton/infrastructure/league/LeagueRepository.java
Labels: beforeLunch🍕

#356 feat : 클럽 오너를 보호하는 로직 추가
  api/src/main/java/org/badminton/api/interfaces/clubmember/controller/ClubMemberController.java
  api/src/main/java/org/badminton/api/interfaces/clubmember/dto/ClubMemberExpelRequest.java
  domain/src/main/java/org/badminton/domain/common/error/ErrorCode.java
  domain/src/main/java/org/badminton/domain/common/exception/clubmember/ClubMemberOwnerException.java
  domain/src/main/java/org/badminton/domain/domain/clubmember/service/ClubMemberServiceImpl.java
Labels: 5PM🌝

#358 refactor : 스웨거 필수 요소 추가
  api/src/main/java/org/badminton/api/interfaces/match/dto/DoublesMatchResponse.java
  api/src/main/java/org/badminton/api/interfaces/match/dto/MatchTeamResponse.java
  api/src/main/java/org/badminton/api/interfaces/match/dto/Participant.java
  api/src/main/java/org/badminton/api/interfaces/match/dto/SinglesMatchResponse.java
Labels: hotfix🥵

#357 feat: modify the logic when the club owner leaves the club
  api/src/main/java/org/badminton/api/application/clubMember/ClubMemberFacade.java
  api/src/main/java/org/badminton/api/interfaces/clubmember/controller/ClubMemberController.java
  domain/src/main/java/org/badminton/domain/common/error/ErrorCode.java
  domain/src/main/java/org/badminton/domain/common/exception/clubmember/ClubOwnerCannotWithdraw.java
  domain/src/main/java/org/badminton/domain/domain/clubmember/ClubMemberReader.java
  domain/src/main/java/org/badminton/domain/domain/clubmember/service/ClubMemberService.java
  domain/src/main/java/org/badminton/domain/domain/clubmember/service/ClubMemberServiceImpl.java
  infrastructure/src/main/java/org/badminton/infrastructure/clubmember/ClubMemberReaderImpl.java
  infrastructure/src/main/java/org/badminton/infrastructure/clubmember/ClubMemberRepository.java
Labels: feat✨, refactor✍️

#363 feat: League Status 변경 배치 변경
  batch/src/main/java/springproject/badmintonbatch/batch/processor/LeagueStatusProcessor.java
  batch/src/main/java/springproject/badmintonbatch/batch/reader/LeagueStatusItemReader.java
  domain/src/main/java/org/badminton/domain/domain/match/store/DoublesMatchReader.java
  domain/src/main/java/org/badminton/domain/domain/match/store/SinglesMatchReader.java
  infrastructure/src/main/java/org/badminton/infrastructure/league/LeagueRepository.java
  infrastructure/src/main/java/org/badminton/infrastructure/match/reader/DoublesMatchReaderImpl.java
  infrastructure/src/main/java/org/badminton/infrastructure/match/reader/SinglesMatchReaderImpl.java
  infrastructure/src/main/java/org/badminton/infrastructure/match/repository/DoublesMatchRepository.java
  infrastructure/src/main/java/org/badminton/infrastructure/match/repository/SinglesMatchRepository.java
Labels: feat✨

#362 feat: save set score in redis
  api/src/main/java/org/badminton/api/BadmintonApplication.java
  api/src/main/java/org/badminton/api/application/match/MatchFacade.java
  api/src/main/java/org/badminton/api/interfaces/league/controller/MainLeagueController.java
  api/src/main/java/org/badminton/api/interfaces/match/controller/MatchController.java
  api/src/main/resources/application.yaml
  domain/src/main/java/org/badminton/domain/domain/match/entity/SinglesMatch.java
  domain/src/main/java/org/badminton/domain/domain/match/info/SetInfo.java
  domain/src/main/java/org/badminton/domain/domain/match/service/AbstractSinglesMatchStrategy.java
  domain/src/main/java/org/badminton/domain/domain/match/service/MatchRetrieveService.java
  domain/src/main/java/org/badminton/domain/domain/match/service/MatchStrategy.java
  infrastructure/build.gradle
  infrastructure/src/main/java/org/badminton/infrastructure/config/RedisCacheConfig.java
  infrastructure/src/main/java/org/badminton/infrastructure/match/repository/SetRepository.java
  infrastructure/src/main/java/org/badminton/infrastructure/match/service/FreeMatchRetrieveServiceImpl.java
  infrastructure/src/main/java/org/badminton/infrastructure/match/service/RetrieveMatchSet.java
  infrastructure/src/main/java/org/badminton/infrastructure/match/service/TournamentMatchRetrieveServiceImpl.java
  infrastructure/src/main/java/org/badminton/infrastructure/match/strategy/FreeDoublesMatchStrategy.java
  infrastructure/src/main/java/org/badminton/infrastructure/match/strategy/FreeSinglesMatchStrategy.java
  infrastructure/src/main/java/org/badminton/infrastructure/match/strategy/TournamentDoublesMatchStrategy.java
  infrastructure/src/main/java/org/badminton/infrastructure/match/strategy/TournamentSinglesMatchStrategy.java
Labels: feat✨, beforeLunch🍕

#367 feat : ci / cd yml 파일 수정
  .github/workflows/release-batch-build.yml
  .github/workflows/release-build.yml
Labels: 5PM🌝

#364 refactor: 세트 점수 수정 및 등록 경기참여자만 가능하게 수정
  api/src/main/java/org/badminton/api/application/match/FreeMatchFacade.java
  api/src/main/java/org/badminton/api/application/match/MatchFacade.java
  api/src/main/java/org/badminton/api/application/match/MatchOperationHandler.java
  api/src/main/java/org/badminton/api/application/match/TournamentMatchFacade.java
  api/src/main/java/org/badminton/api/interfaces/match/controller/MatchController.java
  domain/src/main/java/org/badminton/domain/common/exception/league/LeagueParticipationNotExistException.java
  domain/src/main/java/org/badminton/domain/domain/match/service/MatchProgressService.java
  infrastructure/src/main/java/org/badminton/infrastructure/match/service/FreeMatchProgressServiceImpl.java
  infrastructure/src/main/java/org/badminton/infrastructure/match/service/RetrieveMatchSet.java
  infrastructure/src/main/java/org/badminton/infrastructure/match/service/TournamentMatchProgressServiceImpl.java
Labels: refactor✍️

#368 feat : ci / cd yml 파일 수정
  .github/workflows/release-batch-build.yml
  .github/workflows/release-build.yml
  .github/workflows/test-batch-build.yml
Labels: hotfix🥵, 5PM🌝

#371 refactor: Bracket 재생성 검증 로직 수정
  domain/src/main/java/org/badminton/domain/domain/match/service/AbstractDoublesMatchStrategy.java
  domain/src/main/java/org/badminton/domain/domain/match/service/AbstractSinglesMatchStrategy.java
  domain/src/main/java/org/badminton/domain/domain/match/service/MatchStrategy.java
  domain/src/main/java/org/badminton/domain/domain/match/store/DoublesMatchReader.java
  domain/src/main/java/org/badminton/domain/domain/match/store/SinglesMatchReader.java
  infrastructure/src/main/java/org/badminton/infrastructure/match/reader/DoublesMatchReaderImpl.java
  infrastructure/src/main/java/org/badminton/infrastructure/match/reader/SinglesMatchReaderImpl.java
  infrastructure/src/main/java/org/badminton/infrastructure/match/repository/DoublesMatchRepository.java
  infrastructure/src/main/java/org/badminton/infrastructure/match/repository/SinglesMatchRepository.java
  infrastructure/src/main/java/org/badminton/infrastructure/match/service/FreeBracketGenerationServiceImpl.java
  infrastructure/src/main/java/org/badminton/infrastructure/match/service/TournamentBracketGenerationServiceImpl.java
  infrastructure/src/main/java/org/badminton/infrastructure/match/strategy/FreeDoublesMatchStrategy.java
  infrastructure/src/main/java/org/badminton/infrastructure/match/strategy/FreeSinglesMatchStrategy.java
  infrastructure/src/main/java/org/badminton/infrastructure/match/strategy/TournamentDoublesMatchStrategy.java
  infrastructure/src/main/java/org/badminton/infrastructure/match/strategy/TournamentSinglesMatchStrategy.java
Labels: refactor✍️

#376 refactor: 레디스 배포 서버로 변경
  api/src/main/resources/application.yaml
Labels: refactor✍️

#379 feat: 싱글 세트에 대한 다음 경기 관련 로직 수정
  api/src/main/java/org/badminton/api/application/match/FreeMatchFacade.java
  api/src/main/java/org/badminton/api/application/match/MatchOperationHandler.java
  api/src/main/java/org/badminton/api/application/match/TournamentMatchFacade.java
  api/src/main/java/org/badminton/api/interfaces/league/controller/MainLeagueController.java
  api/src/main/java/org/badminton/api/interfaces/match/controller/MatchController.java
  api/src/main/java/org/badminton/api/interfaces/match/dto/SetScoreFinishResponse.java
  api/src/main/java/org/badminton/api/interfaces/match/dto/SetScoreUpdateResponse.java
  domain/src/main/java/org/badminton/domain/domain/match/service/AbstractDoublesMatchStrategy.java
  domain/src/main/java/org/badminton/domain/domain/match/service/AbstractSinglesMatchStrategy.java
  domain/src/main/java/org/badminton/domain/domain/match/service/MatchProgressService.java
  domain/src/main/java/org/badminton/domain/domain/match/service/MatchStrategy.java
  infrastructure/src/main/java/org/badminton/infrastructure/match/service/FreeMatchProgressServiceImpl.java
  infrastructure/src/main/java/org/badminton/infrastructure/match/service/TournamentMatchProgressServiceImpl.java
  infrastructure/src/main/java/org/badminton/infrastructure/match/strategy/FreeDoublesMatchStrategy.java
  infrastructure/src/main/java/org/badminton/infrastructure/match/strategy/FreeSinglesMatchStrategy.java
  infrastructure/src/main/java/org/badminton/infrastructure/match/strategy/TournamentDoublesMatchStrategy.java
  infrastructure/src/main/java/org/badminton/infrastructure/match/strategy/TournamentSinglesMatchStrategy.java
Labels: beforeLunch🍕

#380 refactor: Score를 VO로 구현했습니다.
  api/src/main/java/org/badminton/api/application/match/MatchFacade.java
  batch/src/main/java/springproject/badmintonbatch/batch/reader/LeagueItemReader.java
  domain/src/main/java/org/badminton/domain/common/error/ErrorCode.java
  domain/src/main/java/org/badminton/domain/common/exception/match/SetScoreNotInCacheException.java
  domain/src/main/java/org/badminton/domain/domain/match/entity/DoublesSet.java
  domain/src/main/java/org/badminton/domain/domain/match/entity/SinglesSet.java
  domain/src/main/java/org/badminton/domain/domain/match/info/BracketInfo.java
  domain/src/main/java/org/badminton/domain/domain/match/info/DoublesMatchInfo.java
  domain/src/main/java/org/badminton/domain/domain/match/info/SinglesMatchInfo.java
  domain/src/main/java/org/badminton/domain/domain/match/reader/DoublesMatchRepositoryCustom.java
  domain/src/main/java/org/badminton/domain/domain/match/reader/SinglesMatchRepositoryCustom.java
  domain/src/main/java/org/badminton/domain/domain/match/service/AbstractDoublesMatchStrategy.java
  domain/src/main/java/org/badminton/domain/domain/match/service/MatchRecordService.java
  domain/src/main/java/org/badminton/domain/domain/match/store/DoublesMatchReader.java
  domain/src/main/java/org/badminton/domain/domain/match/vo/Score.java
  infrastructure/src/main/java/org/badminton/infrastructure/match/reader/SinglesMatchReaderImpl.java
  infrastructure/src/main/java/org/badminton/infrastructure/match/repository/DoublesMatchRepository.java
  infrastructure/src/main/java/org/badminton/infrastructure/match/repository/DoublesMatchRepositoryImpl.java
  infrastructure/src/main/java/org/badminton/infrastructure/match/repository/SetRepository.java
  infrastructure/src/main/java/org/badminton/infrastructure/match/repository/SinglesMatchRepository.java
  infrastructure/src/main/java/org/badminton/infrastructure/match/repository/SinglesMatchRepositoryImpl.java
  infrastructure/src/main/java/org/badminton/infrastructure/match/service/RetrieveMatchSet.java
  infrastructure/src/main/java/org/badminton/infrastructure/match/store/DoublesMatchStoreImpl.java
  infrastructure/src/main/java/org/badminton/infrastructure/match/store/SinglesMatchStoreImpl.java
  infrastructure/src/main/java/org/badminton/infrastructure/match/strategy/TournamentSinglesMatchStrategy.java
Labels: beforeLunch🍕, refactor✍️

#381 refactor: 메인 페이지에 진행 중인 세트 점수 조회 시 매치 아이디 기준으로 정렬
  domain/src/main/java/org/badminton/domain/domain/match/entity/DoublesMatch.java
  domain/src/main/java/org/badminton/domain/domain/match/service/AbstractDoublesMatchStrategy.java
  domain/src/main/java/org/badminton/domain/domain/match/service/AbstractSinglesMatchStrategy.java
Labels: now❗️, refactor✍️

#382 test: Member, Club 관련 단위 테스트
  api/src/test/java/org/badminton/api/application/club/ClubFacadeTest.java
  api/src/test/java/org/badminton/api/application/member/MemberFacadeTest.java
  build.gradle
  domain/src/main/java/org/badminton/domain/domain/club/ClubApplyServiceImpl.java
  domain/src/main/java/org/badminton/domain/domain/club/entity/ClubApply.java
  domain/src/test/java/org/badminton/domain/domain/club/ClubApplyServiceImplTest.java
  domain/src/test/java/org/badminton/domain/domain/club/ClubServiceImplTest.java
  domain/src/test/java/org/badminton/domain/domain/member/service/MemberServiceImplTest.java
Labels: test🧈

#383 refactor: 메인 경기 화면에서 진행 중인 세트 점수를 조회할 때 DB에 저장되지 않아 동기화가 되지 않는 문제 해결
  api/src/main/java/org/badminton/api/config/security/SecurityConfig.java
  api/src/main/java/org/badminton/api/interfaces/match/controller/MatchController.java
  domain/src/main/java/org/badminton/domain/domain/match/service/AbstractDoublesMatchStrategy.java
  domain/src/main/java/org/badminton/domain/domain/match/service/AbstractSinglesMatchStrategy.java
  infrastructure/src/main/java/org/badminton/infrastructure/match/service/RetrieveMatchSet.java
Labels: 5PM🌝, refactor✍️

#385 feat: 세트 점수 등록 시 리그의 모든 매치가 끝났을 때 리그의 상태 완료로 변경
  infrastructure/src/main/java/org/badminton/infrastructure/match/service/FreeBracketGenerationServiceImpl.java
  infrastructure/src/main/java/org/badminton/infrastructure/match/service/FreeMatchProgressServiceImpl.java
  infrastructure/src/main/java/org/badminton/infrastructure/match/service/FreeMatchRetrieveServiceImpl.java
  infrastructure/src/main/java/org/badminton/infrastructure/match/service/TournamentBracketGenerationServiceImpl.java
  infrastructure/src/main/java/org/badminton/infrastructure/match/service/TournamentMatchProgressServiceImpl.java
  infrastructure/src/main/java/org/badminton/infrastructure/match/service/TournamentMatchRetrieveServiceImpl.java
  infrastructure/src/main/java/org/badminton/infrastructure/match/strategy/FreeDoublesMatchStrategy.java
  infrastructure/src/main/java/org/badminton/infrastructure/match/strategy/FreeSinglesMatchStrategy.java
  infrastructure/src/main/java/org/badminton/infrastructure/match/strategy/TournamentDoublesMatchStrategy.java
  infrastructure/src/main/java/org/badminton/infrastructure/match/strategy/TournamentSinglesMatchStrategy.java
Labels: feat✨

#387 refactor: 이미지 검증 변경
  api/src/main/java/org/badminton/api/interfaces/member/validator/MemberImageValidatorImpl.java
Labels: refactor✍️

#389 hotfix: mainLeagueResponse 에 clubToken 추가
  api/src/main/java/org/badminton/api/interfaces/league/dto/OngoingAndUpcomingLeagueResponse.java
  domain/src/main/java/org/badminton/domain/domain/league/info/OngoingAndUpcomingLeagueInfo.java
Labels: hotfix🥵

#392 fix-release-test
  api/src/main/java/org/badminton/api/application/auth/AuthFacade.java
  batch/src/main/java/springproject/badmintonbatch/batch/config/EmailBatchConfig.java
  domain/src/main/java/org/badminton/domain/domain/auth/service/AuthServiceImpl.java
  infrastructure/src/main/java/org/badminton/infrastructure/club/ClubApplyReaderImpl.java
Labels: hotfix🥵

#393 fix: release-build
  .github/workflows/release-build.yml
Labels: fix🛠️

#394 hotfix-releasetest
  api/src/main/java/org/badminton/api/application/auth/AuthFacade.java
  domain/src/main/java/org/badminton/domain/domain/auth/service/AuthServiceImpl.java
  infrastructure/src/main/java/org/badminton/infrastructure/club/ClubApplyReaderImpl.java
Labels: hotfix🥵

#404 hotfix: securityConfig
  api/src/main/java/org/badminton/api/config/security/SecurityConfig.java
Labels: hotfix🥵

#405 refactor: 경기 참여 시 인원이 다 찼는지 확인하고 Recruiting Completed 상태로 변경
  domain/src/main/java/org/badminton/domain/domain/league/LeagueParticipantServiceImpl.java
  domain/src/main/java/org/badminton/domain/domain/league/entity/League.java
  infrastructure/src/main/java/org/badminton/infrastructure/match/repository/SetRepository.java
Labels: beforeLunch🍕, refactor✍️

#407 bug : 이메일 여러번 보내는 버그 해결
  api/src/main/java/org/badminton/api/application/clubMember/ClubMemberFacade.java
  domain/src/main/java/org/badminton/domain/domain/mail/MailService.java
  domain/src/main/java/org/badminton/domain/domain/mail/MailServiceImpl.java
Labels: hotfix🥵

#409 refactor: API 분리
  api/src/main/java/org/badminton/api/application/league/LeagueFacade.java
  api/src/main/java/org/badminton/api/config/security/SecurityConfig.java
  api/src/main/java/org/badminton/api/interfaces/league/controller/LeagueController.java
  api/src/main/java/org/badminton/api/interfaces/league/controller/LeagueDtoMapper.java
  api/src/main/java/org/badminton/api/interfaces/league/dto/IsLeagueParticipantResponse.java
  api/src/main/java/org/badminton/api/interfaces/league/dto/LeagueDetailsResponse.java
  domain/src/main/java/org/badminton/domain/domain/league/LeagueParticipantService.java
  domain/src/main/java/org/badminton/domain/domain/league/LeagueParticipantServiceImpl.java
  domain/src/main/java/org/badminton/domain/domain/league/info/IsLeagueParticipantInfo.java
  domain/src/main/java/org/badminton/domain/domain/league/info/LeagueDetailsInfo.java
Labels: refactor✍️

#413 hotfix: 가입신청 유저 확인 리스폰스 변경
  .gitignore
  api/src/main/java/org/badminton/api/interfaces/club/dto/ClubApplicantResponse.java
  domain/src/main/java/org/badminton/domain/domain/club/info/ClubApplicantInfo.java
  domain/src/test/java/org/badminton/domain/domain/club/ClubServiceImplTest.java
Labels: hotfix🥵

#419 feat: make Admin Module
  .gitignore
  admin/Dockerfile
  admin/build.gradle
  admin/src/main/java/springproject/BadmintonAdminApplication.java
  api/src/main/resources/data.sql
  docker-compose.yaml
  settings.gradle
Labels: feat✨

#421 hotfix: snake_case로 변경
  api/src/main/java/org/badminton/api/exceptionhandler/FailedAuthenticationEntryPoint.java
Labels: hotfix🥵

#414 feat: save set score in redis to db scheculder
  api/src/main/java/org/badminton/api/application/match/MatchFacade.java
  domain/src/main/java/org/badminton/domain/domain/match/vo/RedisKey.java
  infrastructure/src/main/java/org/badminton/infrastructure/match/repository/SetRepository.java
  infrastructure/src/main/java/org/badminton/infrastructure/match/service/RetrieveMatchSet.java
Labels: feat✨, 5PM🌝

#422 refactor: 경기 조회 response에 경기 주인 토큰 추가
  api/src/main/java/org/badminton/api/interfaces/league/dto/LeagueDetailsResponse.java
  api/src/main/resources/data.sql
  domain/src/main/java/org/badminton/domain/domain/league/info/LeagueDetailsInfo.java
  domain/src/main/java/org/badminton/domain/domain/league/info/LeagueSummaryInfo.java
Labels: now❗️, refactor✍️

#441 refactor: 내가 생성한 경기가 아니면 수정 및 삭제 막았습니다
  api/src/main/java/org/badminton/api/application/league/LeagueFacade.java
  api/src/main/java/org/badminton/api/interfaces/league/controller/LeagueController.java
  domain/src/main/java/org/badminton/domain/common/error/ErrorCode.java
  domain/src/main/java/org/badminton/domain/common/exception/league/NotLeagueOwnerException.java
  domain/src/main/java/org/badminton/domain/domain/league/LeagueService.java
  domain/src/main/java/org/badminton/domain/domain/league/LeagueServiceImpl.java
Labels: refactor✍️

#442 refactor: clubMember.size() -> countByClubClubTokenAndDeletedFalse 로 변경
  api/src/main/java/org/badminton/api/application/club/ClubFacade.java
  api/src/main/java/org/badminton/api/application/statistics/ClubStatisticsFacade.java
  domain/src/main/java/org/badminton/domain/domain/clubmember/ClubMemberReader.java
  domain/src/main/java/org/badminton/domain/domain/clubmember/service/ClubMemberService.java
  domain/src/main/java/org/badminton/domain/domain/clubmember/service/ClubMemberServiceImpl.java
  infrastructure/src/main/java/org/badminton/infrastructure/clubmember/ClubMemberReaderImpl.java
Labels: refactor✍️

#443 feat: 동호회 중복 가입 방지
  domain/src/main/java/org/badminton/domain/domain/club/ClubApplyReader.java
  infrastructure/src/main/java/org/badminton/infrastructure/club/ClubApplyReaderImpl.java
  infrastructure/src/main/java/org/badminton/infrastructure/club/ClubApplyRepository.java
Labels: feat✨

#445 refactor: 경기 생성 로직 일반 회원도 실행 가능하게 수정
  api/src/main/java/org/badminton/api/config/security/SecurityConfig.java
Labels: refactor✍️

#447 release
  api/src/main/java/org/badminton/api/config/security/SecurityConfig.java
Labels: refactor✍️

#448 refactor: 모집 중이거나 모집 완료 상태일 때만 경기를 수정할 수 있도록 수정
  domain/src/main/java/org/badminton/domain/common/error/ErrorCode.java
  domain/src/main/java/org/badminton/domain/common/exception/league/LeagueCannotBeUpdated.java
  domain/src/main/java/org/badminton/domain/domain/league/LeagueServiceImpl.java
Labels: beforeLunch🍕, refactor✍️

#449 feat: 배치로 정지시간이 지난 유저 정지 해제
  batch/src/main/java/springproject/badmintonbatch/batch/config/MemberLiftBatchConfig.java
  batch/src/main/java/springproject/badmintonbatch/batch/processor/MemberLiftProcessor.java
  batch/src/main/java/springproject/badmintonbatch/batch/reader/MemberLiftReader.java
  batch/src/main/java/springproject/badmintonbatch/batch/scheduler/BatchScheduler.java
  batch/src/main/java/springproject/badmintonbatch/batch/writer/MemberLiftWriter.java
  domain/src/main/java/org/badminton/domain/domain/clubmember/entity/ClubMemberBanRecord.java
  infrastructure/src/main/java/org/badminton/infrastructure/clubmember/BannedClubMemberRepository.java
Labels: feat✨

#451 refactor: fix match generation condition
  api/src/main/java/org/badminton/api/application/match/FreeMatchFacade.java
  api/src/main/java/org/badminton/api/application/match/MatchOperationHandler.java
  api/src/main/java/org/badminton/api/application/match/TournamentMatchFacade.java
  api/src/main/java/org/badminton/api/interfaces/match/controller/MatchController.java
  api/src/main/java/org/badminton/api/interfaces/match/dto/StartFirstSetScoreCommand.java
  api/src/main/java/org/badminton/api/interfaces/match/dto/StartMatchCommand.java
  domain/src/main/java/org/badminton/domain/common/error/ErrorCode.java
  domain/src/main/java/org/badminton/domain/common/exception/league/NotLeagueOwnerException.java
  domain/src/main/java/org/badminton/domain/domain/match/entity/DoublesSet.java
  domain/src/main/java/org/badminton/domain/domain/match/service/BracketGenerationService.java
  domain/src/main/java/org/badminton/domain/domain/match/service/MatchStrategy.java
  infrastructure/src/main/java/org/badminton/infrastructure/match/service/FreeBracketGenerationServiceImpl.java
  infrastructure/src/main/java/org/badminton/infrastructure/match/service/TournamentBracketGenerationServiceImpl.java
  infrastructure/src/main/java/org/badminton/infrastructure/match/strategy/FreeDoublesMatchStrategy.java
  infrastructure/src/main/java/org/badminton/infrastructure/match/strategy/FreeSinglesMatchStrategy.java
  infrastructure/src/main/java/org/badminton/infrastructure/match/strategy/TournamentDoublesMatchStrategy.java
  infrastructure/src/main/java/org/badminton/infrastructure/match/strategy/TournamentSinglesMatchStrategy.java
Labels: 5PM🌝, refactor✍️

#456 bug: 배치 에러 수정
  batch/src/main/java/springproject/badmintonbatch/batch/config/EmailBatchConfig.java
  batch/src/main/java/springproject/badmintonbatch/batch/config/LeagueBatchConfig.java
  batch/src/main/java/springproject/badmintonbatch/batch/config/LeagueStatusBatchConfig.java
  batch/src/main/java/springproject/badmintonbatch/batch/config/MemberLiftBatchConfig.java
  batch/src/main/java/springproject/badmintonbatch/batch/scheduler/BatchScheduler.java
Labels: beforeLunch🍕

#457 배치 서버 재배포
  batch/src/main/java/springproject/badmintonbatch/batch/config/EmailBatchConfig.java
  batch/src/main/java/springproject/badmintonbatch/batch/config/LeagueBatchConfig.java
  batch/src/main/java/springproject/badmintonbatch/batch/config/LeagueStatusBatchConfig.java
  batch/src/main/java/springproject/badmintonbatch/batch/config/MemberLiftBatchConfig.java
  batch/src/main/java/springproject/badmintonbatch/batch/scheduler/BatchScheduler.java
Labels: beforeLunch🍕

#461 refactor: 배치 관련 스크립트 수정
  .github/workflows/release-batch-build.yml
  batch/src/main/java/springproject/badmintonbatch/batch/scheduler/BatchScheduler.java
Labels: beforeLunch🍕

#465 fix: 경기 참여 신청 시 모집된 인원을 확인하여 경기 상태를 모집 마감으로 변경
  api/src/main/java/org/badminton/api/application/league/LeagueParticipationFacade.java
  domain/src/main/java/org/badminton/domain/common/error/ErrorCode.java
  domain/src/main/java/org/badminton/domain/common/exception/league/LeagueCannotBeCanceledException.java
  domain/src/main/java/org/badminton/domain/common/exception/league/LeagueCannotBeCanceledWhenIsNotRecruiting.java
  domain/src/main/java/org/badminton/domain/domain/league/LeagueParticipantService.java
  domain/src/main/java/org/badminton/domain/domain/league/LeagueParticipantServiceImpl.java
Labels: fix🛠️, 5PM🌝

#468 refactor: 경기 생성, 수정, 삭제 권한 수정
  api/src/main/java/org/badminton/api/config/security/SecurityConfig.java
  domain/src/main/java/org/badminton/domain/domain/club/entity/Club.java
  domain/src/main/java/org/badminton/domain/domain/league/entity/League.java
Labels: 5PM🌝

#466 refactor: 동호회 회원 제제 관련 로직 수정
  api/src/main/java/org/badminton/api/application/clubMember/ClubMemberFacade.java
  api/src/main/java/org/badminton/api/interfaces/clubmember/dto/MemberIsClubMemberResponse.java
  domain/src/main/java/org/badminton/domain/common/error/ErrorCode.java
  domain/src/main/java/org/badminton/domain/common/exception/clubmember/ClubMemberExpelException.java
  domain/src/main/java/org/badminton/domain/domain/club/ClubApplyServiceImpl.java
  domain/src/main/java/org/badminton/domain/domain/clubmember/ClubMemberReader.java
  domain/src/main/java/org/badminton/domain/domain/clubmember/info/MemberIsClubMemberInfo.java
  domain/src/main/java/org/badminton/domain/domain/clubmember/service/ClubMemberServiceImpl.java
  domain/src/main/java/org/badminton/domain/domain/mail/MailServiceImpl.java
  infrastructure/src/main/java/org/badminton/infrastructure/clubmember/ClubMemberReaderImpl.java
  infrastructure/src/main/java/org/badminton/infrastructure/clubmember/ClubMemberRepository.java
Labels: refactor✍️

#469 feat: 조회수 증가 시 이벤트 리스너를 사용하여 비동기 처리
  api/src/main/java/org/badminton/api/application/club/ClubFacade.java
  api/src/test/java/org/badminton/api/application/club/ClubFacadeTest.java
  domain/src/main/java/org/badminton/domain/domain/statistics/event/CreateClubEvent.java
  domain/src/main/java/org/badminton/domain/domain/statistics/event/CreateClubEventHandler.java
  domain/src/main/java/org/badminton/domain/domain/statistics/event/ReadClubEvent.java
  domain/src/main/java/org/badminton/domain/domain/statistics/event/ReadClubEventHandler.java
Labels: feat✨, 5PM🌝

#475 refactor: 경기 취소 시 현재 시각이 경기 시작 시간 이후라면 예외 발생
  domain/src/main/java/org/badminton/domain/common/error/ErrorCode.java
  domain/src/main/java/org/badminton/domain/common/exception/league/LeagueCannotBeCanceled.java
  domain/src/main/java/org/badminton/domain/common/exception/league/LeagueParticipationCannotBeCanceledException.java
  domain/src/main/java/org/badminton/domain/domain/league/LeagueParticipantServiceImpl.java
  domain/src/main/java/org/badminton/domain/domain/league/LeagueServiceImpl.java
Labels: now❗️, refactor✍️

#474 feat: 이미지 webp, avif 로 컨버팅
  api/build.gradle
  api/src/main/java/org/badminton/api/aws/s3/service/AbstractFileUploadService.java
  api/src/main/java/org/badminton/api/aws/s3/service/ClubImageService.java
  api/src/main/java/org/badminton/api/aws/s3/service/ImageConversionService.java
  api/src/main/java/org/badminton/api/aws/s3/service/ImageService.java
  api/src/main/java/org/badminton/api/aws/s3/service/MemberProfileImageService.java
  api/src/main/java/org/badminton/api/common/exception/EmptyFileException.java
  api/src/main/java/org/badminton/api/common/exception/FileSizeOverException.java
  domain/src/main/java/org/badminton/domain/common/error/ErrorCode.java
Labels: beforeLunch🍕

#479 fix: 경기 상태 변경 배치 수정
  batch/src/main/java/springproject/badmintonbatch/batch/processor/LeagueStatusProcessor.java
Labels: fix🛠️

#478 refactor: 경기 참여 검증 추가 및 경기 세부 조회 Response 추가
  api/src/main/java/org/badminton/api/application/league/LeagueFacade.java
  api/src/main/java/org/badminton/api/interfaces/league/controller/LeagueController.java
  api/src/main/java/org/badminton/api/interfaces/league/controller/LeagueDtoMapper.java
  api/src/main/java/org/badminton/api/interfaces/league/dto/LeagueDetailsResponse.java
  api/src/main/java/org/badminton/api/interfaces/league/dto/LeagueParticipantDetailsResponse.java
  api/src/main/java/org/badminton/api/interfaces/league/dto/LeagueParticipantResponse.java
  domain/src/main/java/org/badminton/domain/common/error/ErrorCode.java
  domain/src/main/java/org/badminton/domain/common/exception/league/InvalidDateTimeToParticipateInLeagueException.java
  domain/src/main/java/org/badminton/domain/common/exception/league/LeagueNotRecruitingException.java
  domain/src/main/java/org/badminton/domain/domain/league/LeagueParticipantService.java
  domain/src/main/java/org/badminton/domain/domain/league/LeagueParticipantServiceImpl.java
  domain/src/main/java/org/badminton/domain/domain/league/info/LeagueDetailsInfo.java
  domain/src/main/java/org/badminton/domain/domain/league/info/LeagueParticipantDetailsInfo.java
Labels: 5PM🌝, refactor✍️

#483 test: Edit SecurityConfig
  api/src/main/java/org/badminton/api/config/security/SecurityConfig.java
Labels: refactor✍️

#484 test: SecurityConfig 수정
  api/src/main/java/org/badminton/api/config/security/SecurityConfig.java
Labels: fix🛠️

#485 refactor: SecurityConfig 수정
  api/src/main/java/org/badminton/api/config/security/SecurityConfig.java
Labels: refactor✍️

#486 refactor: 동호회 회원을 조회할 때 제재된 회원과 그렇지 않은 회원을 구분
  api/src/main/java/org/badminton/api/application/clubMember/ClubMemberFacade.java
  api/src/main/java/org/badminton/api/aws/s3/controller/ClubImageController.java
  api/src/main/java/org/badminton/api/interfaces/clubmember/ClubMemberDtoMapper.java
  api/src/main/java/org/badminton/api/interfaces/clubmember/controller/ClubMemberController.java
  api/src/main/java/org/badminton/api/interfaces/match/controller/MatchController.java
  domain/src/main/java/org/badminton/domain/common/policy/ClubMemberPolicy.java
  domain/src/main/java/org/badminton/domain/domain/clubmember/ClubMemberReader.java
  domain/src/main/java/org/badminton/domain/domain/clubmember/service/ClubMemberService.java
  domain/src/main/java/org/badminton/domain/domain/clubmember/service/ClubMemberServiceImpl.java
  domain/src/main/java/org/badminton/domain/domain/match/info/BracketInfo.java
  infrastructure/src/main/java/org/badminton/infrastructure/clubmember/ClubMemberReaderImpl.java
  infrastructure/src/main/java/org/badminton/infrastructure/clubmember/ClubMemberRepository.java
Labels: feat✨, 5PM🌝

#488 refactor: startMatch 메서드 수정 및 검증 추가
  api/src/main/java/org/badminton/api/application/match/FreeMatchFacade.java
  api/src/main/java/org/badminton/api/application/match/MatchOperationHandler.java
  api/src/main/java/org/badminton/api/application/match/TournamentMatchFacade.java
  domain/src/main/java/org/badminton/domain/common/error/ErrorCode.java
  domain/src/main/java/org/badminton/domain/common/exception/league/CannotStartMatchException.java
  domain/src/main/java/org/badminton/domain/domain/match/service/AbstractDoublesMatchStrategy.java
  domain/src/main/java/org/badminton/domain/domain/match/service/AbstractSinglesMatchStrategy.java
  domain/src/main/java/org/badminton/domain/domain/match/service/BracketGenerationService.java
  infrastructure/src/main/java/org/badminton/infrastructure/match/service/FreeBracketGenerationServiceImpl.java
  infrastructure/src/main/java/org/badminton/infrastructure/match/service/TournamentBracketGenerationServiceImpl.java
  infrastructure/src/main/java/org/badminton/infrastructure/match/strategy/FreeDoublesMatchStrategy.java
  infrastructure/src/main/java/org/badminton/infrastructure/match/strategy/FreeSinglesMatchStrategy.java
  infrastructure/src/main/java/org/badminton/infrastructure/match/strategy/TournamentDoublesMatchStrategy.java
  infrastructure/src/main/java/org/badminton/infrastructure/match/strategy/TournamentSinglesMatchStrategy.java
Labels: 5PM🌝, refactor✍️

#489 refactor: 이미지 변환 의존성 변경
  api/build.gradle
  api/src/main/java/org/badminton/api/aws/s3/service/ImageConversionService.java
Labels: refactor✍️

#490 hotfix: 이미지 변환 의존성 추가하고 주석 제거했습니다
  api/build.gradle
  api/src/main/java/org/badminton/api/aws/s3/service/ImageConversionService.java
Labels: hotfix🥵

#492 refactor: 세트 Response에 SetStatus 추가
  api/src/main/java/org/badminton/api/interfaces/match/dto/MatchSetResponse.java
  domain/src/main/java/org/badminton/domain/domain/match/info/MatchSetInfo.java
Labels: 5PM🌝, refactor✍️

#493 refactor: 메일 전송 배치 제거, EventPublisher 를 사용해서 비동기로 처리
  api/src/main/java/org/badminton/api/BadmintonApplication.java
  api/src/main/java/org/badminton/api/application/clubMember/ClubMemberFacade.java
  api/src/main/java/org/badminton/api/interfaces/club/controller/ClubController.java
  batch/build.gradle
  batch/src/main/java/springproject/badmintonbatch/batch/config/EmailBatchConfig.java
  batch/src/main/java/springproject/badmintonbatch/batch/processor/MailItemProcessor.java
  batch/src/main/java/springproject/badmintonbatch/batch/reader/MailItemReader.java
  batch/src/main/java/springproject/badmintonbatch/batch/scheduler/BatchScheduler.java
  batch/src/main/java/springproject/badmintonbatch/batch/writer/MailItemWriter.java
  domain/build.gradle
  domain/src/main/java/org/badminton/domain/common/mail/MailConfig.java
  domain/src/main/java/org/badminton/domain/domain/mail/MailServiceImpl.java
  domain/src/main/java/org/badminton/domain/domain/mail/MailStore.java
  domain/src/main/java/org/badminton/domain/domain/mail/entity/Mail.java
  domain/src/main/java/org/badminton/domain/domain/mail/event/SendApplyEmailEvent.java
  domain/src/main/java/org/badminton/domain/domain/mail/event/SendApplyEmailEventHandler.java
  domain/src/main/java/org/badminton/domain/domain/mail/event/SendResultEmailEvent.java
  domain/src/main/java/org/badminton/domain/domain/mail/event/SendResultEventHandler.java
  infrastructure/src/main/java/org/badminton/infrastructure/mail/MailRepository.java
  infrastructure/src/main/java/org/badminton/infrastructure/mail/MailStoreImpl.java
Labels: refactor✍️
