Repository Kernel360/F2_PLAY_BADMINTON_BE, pull requests merged in 2024-09, with the labels that each got.

#2 docs: 도커 mysql 환경 설정
  docker-compose.yaml
  src/main/resources/application.properties
Labels: docs📉

#3 Update issue templates
  .github/ISSUE_TEMPLATE/기능-구현-시.md
  .github/ISSUE_TEMPLATE/리팩토링-시.md
  .github/ISSUE_TEMPLATE/버그-리포트.md
Labels: 5PM🌝

#5 Create PULL_REQUEST_TEMPLATE
  .github/PULL_REQUEST_TEMPLATE
Labels: 5PM🌝

#9 docs: Update README.md
  README.md
Labels: docs📉

#7 docs: modify gitignore
  .gitignore
  docker-compose.yaml
  src/main/java/com/final2/odiya/OdiyaApplication.java
  src/main/resources/application.properties
Labels: docs📉

#10 docs: change project
  .run/BadmintonApplication.run.xml
  settings.gradle
  src/main/java/com/final2/badminton/BadmintonApplication.java
  src/test/java/com/final2/badminton/BadmintonApplicationTests.java
Labels: now❗️

#12 docs: add swagger dependency
  build.gradle
  src/main/java/com/final2/badminton/config/SwaggerConfig.java
Labels: now❗️

#13 Update issue templates
  .github/ISSUE_TEMPLATE/기능-구현-시.md
  .github/ISSUE_TEMPLATE/리팩토링-시.md
  .github/ISSUE_TEMPLATE/버그-리포트.md
Labels: docs📉, 5PM🌝

#20 refactor: jpa config 수정 및 ObjectMapperConfig 수정
  badminton-api/src/main/java/org/badminton/api/BadmintonApplication.java
  badminton-api/src/main/java/org/badminton/api/config/jpa/JpaConfig.java
  badminton-api/src/main/java/org/badminton/api/config/objectmapper/ObjectMapperConfig.java
  badminton-api/src/main/java/org/badminton/api/filter/LoggerFilter.java
  build.gradle
  settings.gradle
Labels: docs📉, 5PM🌝

#22 feat: league create 추가
  badminton-api/src/main/java/org/badminton/api/league/LeagueController.java
  badminton-api/src/main/java/org/badminton/api/league/model/dto/LeagueCreateRequest.java
  badminton-api/src/main/java/org/badminton/api/league/service/LeagueService.java
  badminton-domain/src/main/java/org/badminton/domain/league/entity/LeagueEntity.java
  badminton-domain/src/main/java/org/badminton/domain/league/repository/LeagueRepository.java
Labels: feat✨

#19 feat: club entity 추가
  badminton-api/src/main/java/org/badminton/api/club/ClubController.java
  badminton-api/src/main/java/org/badminton/api/club/controller/ClubController.java
  badminton-api/src/main/java/org/badminton/api/club/model/dto/ClubAddRequest.java
  badminton-api/src/main/java/org/badminton/api/club/model/dto/ClubAddResponse.java
  badminton-api/src/main/java/org/badminton/api/club/service/ClubAddService.java
  badminton-api/src/main/java/org/badminton/api/club/validator/ClubValidator.java
  badminton-api/src/main/java/org/badminton/api/config/jpa/JpaConfig.java
  badminton-domain/src/main/java/org/badminton/domain/club/entity/ClubEntity.java
  badminton-domain/src/main/java/org/badminton/domain/club/repository/ClubRepository.java
  badminton-domain/src/main/java/org/badminton/domain/common/BaseTimeEntity.java
Labels: feat✨, 5PM🌝

#24 feat: oAuth login
  badminton-api/build.gradle
  badminton-api/src/main/java/org/badminton/api/config/security/SecurityConfig.java
  badminton-api/src/main/java/org/badminton/api/member/MemberController.java
  badminton-api/src/main/java/org/badminton/api/member/jwt/JwtFilter.java
  badminton-api/src/main/java/org/badminton/api/member/jwt/JwtUtil.java
  badminton-api/src/main/java/org/badminton/api/member/model/dto/CustomOAuth2Member.java
  badminton-api/src/main/java/org/badminton/api/member/model/dto/GoogleResponse.java
  badminton-api/src/main/java/org/badminton/api/member/model/dto/KakaoResponse.java
  badminton-api/src/main/java/org/badminton/api/member/model/dto/MemberRequest.java
  badminton-api/src/main/java/org/badminton/api/member/model/dto/MemberResponse.java
  badminton-api/src/main/java/org/badminton/api/member/model/dto/NaverResponse.java
  badminton-api/src/main/java/org/badminton/api/member/model/dto/OAuthResponse.java
  badminton-api/src/main/java/org/badminton/api/member/oauth2/CustomSuccessHandler.java
  badminton-api/src/main/java/org/badminton/api/member/service/CustomOAuth2MemberService.java
  badminton-api/src/main/java/org/badminton/api/member/validator/MemberValidator.java
  badminton-api/src/main/resources/application.properties
  badminton-domain/build.gradle
  badminton-domain/src/main/java/org/badminton/domain/member/entity/MemberEntity.java
  badminton-domain/src/main/java/org/badminton/domain/member/entity/MemberRole.java
  badminton-domain/src/main/java/org/badminton/domain/member/repository/MemberRepository.java
Labels: feat✨

#28 refactor: env 세팅 추가 및 yaml로 변경
  .gitignore
  badminton-api/build.gradle
  badminton-api/src/main/resources/application.properties
  badminton-api/src/main/resources/application.yaml
Labels: 5PM🌝

#30 빌드 실행파일 추가
  gradlew
Labels: 5PM🌝

#26 refactor: change field name
  badminton-api/src/main/java/org/badminton/api/config/jpa/JpaConfig.java
  badminton-api/src/main/java/org/badminton/api/config/security/SecurityConfig.java
  badminton-api/src/main/java/org/badminton/api/member/MemberController.java
  badminton-api/src/main/java/org/badminton/api/member/jwt/JwtFilter.java
  badminton-api/src/main/java/org/badminton/api/member/jwt/JwtUtil.java
  badminton-api/src/main/java/org/badminton/api/member/model/dto/CustomOAuth2Member.java
  badminton-api/src/main/java/org/badminton/api/member/model/dto/MemberRequest.java
  badminton-api/src/main/java/org/badminton/api/member/model/dto/MemberResponse.java
  badminton-api/src/main/java/org/badminton/api/member/oauth2/CustomSuccessHandler.java
  badminton-api/src/main/java/org/badminton/api/member/service/CustomOAuth2MemberService.java
  badminton-domain/src/main/java/org/badminton/domain/member/entity/MemberAuthorization.java
  badminton-domain/src/main/java/org/badminton/domain/member/entity/MemberEntity.java
Labels: 5PM🌝, refactor✍️

#32 feat: error code interface 정의 및 exception, exception handler 추가
  badminton-api/src/main/java/org/badminton/api/club/validator/ClubValidator.java
  badminton-api/src/main/java/org/badminton/api/common/error/ClubErrorCode.java
  badminton-api/src/main/java/org/badminton/api/common/error/ErrorCode.java
  badminton-api/src/main/java/org/badminton/api/common/error/ErrorCodeIfs.java
  badminton-api/src/main/java/org/badminton/api/common/exception/BadmintonException.java
  badminton-api/src/main/java/org/badminton/api/common/exception/BadmintonExceptionIfs.java
  badminton-api/src/main/java/org/badminton/api/exceptionhandler/BadmintonExceptionHandler.java
  badminton-api/src/main/java/org/badminton/api/exceptionhandler/GlobalExceptionHandler.java
Labels: docs📉, 5PM🌝

#33 docs: git-ignore 수정
  .gitignore
Labels: docs📉

#43 feat: member 관련 CRUD 구현
  badminton-api/src/main/java/org/badminton/api/config/swagger/SwaggerConfig.java
  badminton-api/src/main/java/org/badminton/api/member/MemberController.java
  badminton-api/src/main/java/org/badminton/api/member/jwt/JwtFilter.java
  badminton-api/src/main/java/org/badminton/api/member/jwt/JwtUtil.java
  badminton-api/src/main/java/org/badminton/api/member/model/dto/CustomOAuth2Member.java
  badminton-api/src/main/java/org/badminton/api/member/model/dto/GoogleResponse.java
  badminton-api/src/main/java/org/badminton/api/member/model/dto/KakaoResponse.java
  badminton-api/src/main/java/org/badminton/api/member/model/dto/MemberRequest.java
  badminton-api/src/main/java/org/badminton/api/member/model/dto/MemberResponse.java
  badminton-api/src/main/java/org/badminton/api/member/model/dto/MemberUpdateRequest.java
  badminton-api/src/main/java/org/badminton/api/member/model/dto/NaverResponse.java
  badminton-api/src/main/java/org/badminton/api/member/model/dto/OAuthResponse.java
  badminton-api/src/main/java/org/badminton/api/member/oauth2/CustomSuccessHandler.java
  badminton-api/src/main/java/org/badminton/api/member/service/CustomOAuth2MemberService.java
  badminton-api/src/main/java/org/badminton/api/member/service/MemberService.java
  badminton-api/src/main/resources/application.yaml
  badminton-domain/src/main/java/org/badminton/domain/member/entity/MemberEntity.java
  badminton-domain/src/main/java/org/badminton/domain/member/repository/MemberRepository.java
Labels: feat✨

#41 docs: error code 및 exception 수정
  badminton-api/src/main/java/org/badminton/api/club/controller/ClubController.java
  badminton-api/src/main/java/org/badminton/api/club/model/dto/ClubCreateRequest.java
  badminton-api/src/main/java/org/badminton/api/club/model/dto/ClubCreateResponse.java
  badminton-api/src/main/java/org/badminton/api/club/model/dto/ClubDeleteResponse.java
  badminton-api/src/main/java/org/badminton/api/club/model/dto/ClubReadResponse.java
  badminton-api/src/main/java/org/badminton/api/club/model/dto/ClubUpdateRequest.java
  badminton-api/src/main/java/org/badminton/api/club/model/dto/ClubUpdateResponse.java
  badminton-api/src/main/java/org/badminton/api/club/service/ClubAddService.java
  badminton-api/src/main/java/org/badminton/api/club/service/ClubService.java
  badminton-api/src/main/java/org/badminton/api/club/validator/ClubValidator.java
  badminton-api/src/main/java/org/badminton/api/common/error/ClubErrorCode.java
  badminton-api/src/main/java/org/badminton/api/common/error/ErrorCode.java
  badminton-api/src/main/java/org/badminton/api/common/error/ErrorCodeIfs.java
  badminton-api/src/main/java/org/badminton/api/common/exception/BadmintonException.java
  badminton-api/src/main/java/org/badminton/api/common/exception/BadmintonExceptionIfs.java
  badminton-api/src/main/java/org/badminton/api/common/exception/DuplicationException.java
  badminton-api/src/main/java/org/badminton/api/common/response/ExceptionResponse.java
  badminton-api/src/main/java/org/badminton/api/exceptionhandler/BadmintonExceptionHandler.java
  badminton-api/src/main/java/org/badminton/api/exceptionhandler/GlobalExceptionHandler.java
  badminton-domain/src/main/java/org/badminton/domain/club/entity/ClubEntity.java
Labels: docs📉, 5PM🌝

#45 refactor: record로 변경
  badminton-api/src/main/java/org/badminton/api/club/controller/ClubController.java
  badminton-api/src/main/java/org/badminton/api/club/model/dto/ClubCreateRequest.java
  badminton-api/src/main/java/org/badminton/api/club/model/dto/ClubCreateResponse.java
  badminton-api/src/main/java/org/badminton/api/club/model/dto/ClubDeleteResponse.java
  badminton-api/src/main/java/org/badminton/api/club/model/dto/ClubReadResponse.java
  badminton-api/src/main/java/org/badminton/api/club/model/dto/ClubUpdateRequest.java
  badminton-api/src/main/java/org/badminton/api/club/model/dto/ClubUpdateResponse.java
  badminton-api/src/main/java/org/badminton/api/club/service/ClubService.java
  badminton-api/src/main/java/org/badminton/api/club/validator/ClubValidator.java
  badminton-api/src/main/java/org/badminton/api/common/exception/ResourceNotFoundException.java
  badminton-domain/src/main/java/org/badminton/domain/club/repository/ClubRepository.java
Labels: feat✨, beforeLunch🍕

#49 refactor: error code 및 custom exception 수정
  badminton-api/build.gradle
  badminton-api/src/main/java/org/badminton/api/club/validator/ClubValidator.java
  badminton-api/src/main/java/org/badminton/api/common/error/ErrorCode.java
  badminton-api/src/main/java/org/badminton/api/common/exception/BadmintonException.java
  badminton-api/src/main/java/org/badminton/api/common/exception/club/ClubNameDuplicateException.java
  badminton-api/src/main/java/org/badminton/api/common/exception/club/ClubNotExistException.java
  badminton-api/src/main/java/org/badminton/api/common/response/ExceptionResponse.java
  badminton-api/src/main/java/org/badminton/api/exceptionhandler/BadmintonExceptionHandler.java
  badminton-domain/build.gradle
  build.gradle
Labels: beforeLunch🍕, refactor✍️

#46 feat: exception 로직 구현, JsessionId 삭제
  badminton-api/src/main/java/org/badminton/api/common/error/ErrorCode.java
  badminton-api/src/main/java/org/badminton/api/common/exception/DuplicationException.java
  badminton-api/src/main/java/org/badminton/api/common/exception/ResourceNotFoundException.java
  badminton-api/src/main/java/org/badminton/api/common/exception/member/MemberNotExistException.java
  badminton-api/src/main/java/org/badminton/api/common/exception/oauth/JwtCookieNotFoundException.java
  badminton-api/src/main/java/org/badminton/api/member/MemberController.java
  badminton-api/src/main/java/org/badminton/api/member/jwt/JwtFilter.java
  badminton-api/src/main/java/org/badminton/api/member/jwt/JwtUtil.java
  badminton-api/src/main/java/org/badminton/api/member/model/dto/MemberDeleteResponse.java
  badminton-api/src/main/java/org/badminton/api/member/model/dto/MemberLogoutResponse.java
  badminton-api/src/main/java/org/badminton/api/member/model/dto/MemberRequest.java
  badminton-api/src/main/java/org/badminton/api/member/model/dto/MemberUpdateRequest.java
  badminton-api/src/main/java/org/badminton/api/member/model/dto/MemberUpdateResponse.java
  badminton-api/src/main/java/org/badminton/api/member/oauth2/CustomSuccessHandler.java
  badminton-api/src/main/java/org/badminton/api/member/oauth2/dto/CustomOAuth2Member.java
  badminton-api/src/main/java/org/badminton/api/member/oauth2/dto/GoogleResponse.java
  badminton-api/src/main/java/org/badminton/api/member/oauth2/dto/KakaoResponse.java
  badminton-api/src/main/java/org/badminton/api/member/oauth2/dto/NaverResponse.java
  badminton-api/src/main/java/org/badminton/api/member/oauth2/dto/OAuthResponse.java
  badminton-api/src/main/java/org/badminton/api/member/service/CustomOAuth2MemberService.java
  badminton-api/src/main/java/org/badminton/api/member/service/MemberService.java
  badminton-api/src/main/java/org/badminton/api/member/validator/MemberValidator.java
  badminton-domain/src/main/java/org/badminton/domain/member/repository/MemberRepository.java
Labels: feat✨, 5PM🌝

#50 doc: Create ci-cd-build
  .github/workflows/ci-cd-build
Labels: docs📉, beforeLunch🍕

#54 feat: member join club
  badminton-api/src/main/java/org/badminton/api/clubmember/controller/ClubMemberController.java
  badminton-api/src/main/java/org/badminton/api/clubmember/model/dto/ClubMemberJoinResponse.java
  badminton-api/src/main/java/org/badminton/api/clubmember/service/ClubMemberService.java
  badminton-api/src/main/java/org/badminton/api/common/error/ErrorCode.java
  badminton-api/src/main/java/org/badminton/api/common/exception/clubmember/ClubMemberExistInClubException.java
  badminton-domain/src/main/java/org/badminton/domain/club/repository/ClubRepository.java
  badminton-domain/src/main/java/org/badminton/domain/clubmember/entity/ClubMemberEntity.java
  badminton-domain/src/main/java/org/badminton/domain/clubmember/repository/ClubMemberRepository.java
Labels: feat✨, now❗️

#55 refactor: member not exist exception 수정
  badminton-api/src/main/java/org/badminton/api/clubmember/service/ClubMemberService.java
  badminton-api/src/main/java/org/badminton/api/common/exception/member/MemberNotExistException.java
Labels: fix🛠️, now❗️

#53 feat: league crud exception 반영
  Dockerfile
  badminton-api/src/main/java/org/badminton/api/common/exception/league/LeagueNotExistException.java
  badminton-api/src/main/java/org/badminton/api/league/model/dto/LeagueCreateRequest.java
  badminton-api/src/main/java/org/badminton/api/league/model/dto/LeagueStatusUpdateRequest.java
  badminton-api/src/main/java/org/badminton/api/league/service/LeagueService.java
  badminton-api/src/main/java/org/badminton/api/league/validator/LeagueValidator.java
  badminton-api/src/main/resources/application.yaml
  badminton-domain/build.gradle
  badminton-domain/src/main/java/org/badminton/domain/league/entity/LeagueEntity.java
Labels: feat✨, 5PM🌝

#57 refactor: error code 수정
  badminton-api/src/main/java/org/badminton/api/club/service/ClubService.java
  badminton-api/src/main/java/org/badminton/api/club/validator/ClubValidator.java
  badminton-api/src/main/java/org/badminton/api/clubmember/service/ClubMemberService.java
  badminton-api/src/main/java/org/badminton/api/common/error/ErrorCode.java
  badminton-api/src/main/java/org/badminton/api/common/exception/BadmintonException.java
  badminton-api/src/main/java/org/badminton/api/common/exception/club/ClubNameDuplicateException.java
  badminton-api/src/main/java/org/badminton/api/common/exception/club/ClubNotExistException.java
  badminton-api/src/main/java/org/badminton/api/common/exception/clubmember/ClubMemberExistInClubException.java
  badminton-api/src/main/java/org/badminton/api/common/exception/league/LeagueNotExistException.java
  badminton-api/src/main/java/org/badminton/api/common/exception/member/MemberNotExistException.java
  badminton-api/src/main/java/org/badminton/api/common/exception/oauth/JwtCookieNotFoundException.java
  badminton-api/src/main/java/org/badminton/api/league/service/LeagueService.java
  badminton-api/src/main/java/org/badminton/api/member/jwt/JwtUtil.java
  badminton-api/src/main/java/org/badminton/api/member/validator/MemberValidator.java
Labels: fix🛠️, 5PM🌝

#61 feat: 멀티모듈 ci/cd를 위한 세팅
  .github/workflows/ci-cd-build
  .github/workflows/ci-cd-build.yml
Labels: feat✨

#72 feat: batch 로직 구현
  badminton-api/src/main/java/org/badminton/api/member/oauth2/CustomSuccessHandler.java
  badminton-batch/build.gradle
  badminton-batch/src/main/java/springproject/badmintonbatch/batch/config/BatchConfig.java
  badminton-batch/src/main/java/springproject/badmintonbatch/batch/processor/MemberItemProcessor.java
  badminton-batch/src/main/java/springproject/badmintonbatch/batch/reader/MemberItemReader.java
  badminton-batch/src/main/java/springproject/badmintonbatch/batch/scheduler/BatchScheduler.java
  badminton-batch/src/main/java/springproject/badmintonbatch/batch/writer/MemberItemWriter.java
  badminton-batch/src/main/java/springproject/badmintonbatch/config/jpa/JpaConfig.java
Labels: feat✨

#77 feat: cookie 설정 변경
  badminton-api/src/main/java/org/badminton/api/config/security/SecurityConfig.java
  badminton-api/src/main/java/org/badminton/api/member/oauth2/CustomSuccessHandler.java
Labels: feat✨
