Repository Kernel360/F2_PLAY_BADMINTON_BE, pull requests merged in 2024-10, with the labels that each got.

#86 feat: accessToken, refreshToken 구현
  badminton-api/src/main/java/org/badminton/api/config/security/SecurityConfig.java
  badminton-api/src/main/java/org/badminton/api/config/swagger/SwaggerConfig.java
  badminton-api/src/main/java/org/badminton/api/member/MemberController.java
  badminton-api/src/main/java/org/badminton/api/member/controller/MemberController.java
  badminton-api/src/main/java/org/badminton/api/member/jwt/JwtFilter.java
  badminton-api/src/main/java/org/badminton/api/member/jwt/JwtUtil.java
  badminton-api/src/main/java/org/badminton/api/member/model/dto/MemberLogoutResponse.java
  badminton-api/src/main/java/org/badminton/api/member/model/dto/MemberResponse.java
  badminton-api/src/main/java/org/badminton/api/member/oauth2/CustomSuccessHandler.java
  badminton-api/src/main/java/org/badminton/api/member/oauth2/dto/CustomOAuth2Member.java
  badminton-api/src/main/java/org/badminton/api/member/service/CustomOAuth2MemberService.java
  badminton-api/src/main/java/org/badminton/api/member/service/MemberService.java
  badminton-api/src/main/java/org/badminton/api/member/validator/MemberValidator.java
  badminton-domain/src/main/java/org/badminton/domain/clubmember/repository/ClubMemberRepository.java
  badminton-domain/src/main/java/org/badminton/domain/member/entity/MemberEntity.java
Labels: feat✨, now❗️

#90 feat: save image to aws s3
  badminton-api/build.gradle
  badminton-api/src/main/java/org/badminton/api/aws/s3/controller/ClubImageController.java
  badminton-api/src/main/java/org/badminton/api/aws/s3/model/config/MultipartJackson2HttpMessageConverter.java
  badminton-api/src/main/java/org/badminton/api/aws/s3/model/dto/ClubImageUploadRequest.java
  badminton-api/src/main/java/org/badminton/api/aws/s3/service/ClubImageService.java
  badminton-api/src/main/java/org/badminton/api/common/error/ErrorCode.java
  badminton-api/src/main/java/org/badminton/api/common/exception/EmptyFileException.java
  badminton-api/src/main/java/org/badminton/api/config/s3/AwsS3Config.java
  badminton-api/src/main/resources/application.yaml
  badminton-api/src/test/java/org/badminton/api/league/service/LeagueServiceTest.java
Labels: feat✨, now❗️

#96 feat: 서비스 회원 마이페이지 조회
  badminton-api/src/main/java/org/badminton/api/clubmember/model/dto/ClubMemberInfoResponse.java
  badminton-api/src/main/java/org/badminton/api/member/controller/MemberController.java
  badminton-api/src/main/java/org/badminton/api/member/model/dto/MemberDetailResponse.java
  badminton-api/src/main/java/org/badminton/api/member/model/dto/MemberInfoResponse.java
  badminton-api/src/main/java/org/badminton/api/member/oauth2/CustomSuccessHandler.java
  badminton-api/src/main/java/org/badminton/api/member/service/MemberService.java
  badminton-api/src/main/resources/application.yaml
  badminton-domain/src/main/java/org/badminton/domain/clubmember/repository/ClubMemberRepository.java
Labels: feat✨, beforeLunch🍕

#89 refactor: 대진표가 한 번만 생성되도록 수정
  badminton-api/src/main/java/org/badminton/api/common/error/ErrorCode.java
  badminton-api/src/main/java/org/badminton/api/common/exception/match/MatchDuplicateException.java
  badminton-api/src/main/java/org/badminton/api/match/controller/MatchController.java
  badminton-api/src/main/java/org/badminton/api/match/model/dto/DoublesMatchResponse.java
  badminton-api/src/main/java/org/badminton/api/match/model/dto/MatchResponse.java
  badminton-api/src/main/java/org/badminton/api/match/model/dto/SinglesMatchResponse.java
  badminton-api/src/main/java/org/badminton/api/match/model/dto/TeamResponse.java
  badminton-api/src/main/java/org/badminton/api/match/service/MatchService.java
  badminton-domain/src/main/java/org/badminton/domain/common/enums/MatchType.java
  badminton-domain/src/main/java/org/badminton/domain/match/repository/DoublesMatchRepository.java
  badminton-domain/src/main/java/org/badminton/domain/match/repository/SinglesMatchRepository.java
Labels: 5PM🌝, refactor✍️

#103 refactor: 대진표 생성 이후 response에 회원의 닉네임과 이미지를 포함
  badminton-api/src/main/java/org/badminton/api/match/model/dto/MatchDetailsResponse.java
  badminton-api/src/main/java/org/badminton/api/match/model/dto/MatchResponse.java
  badminton-api/src/main/java/org/badminton/api/match/model/dto/SinglesMatchResponse.java
  badminton-api/src/main/java/org/badminton/api/match/model/dto/TeamResponse.java
  badminton-api/src/main/resources/data.sql
  badminton-domain/src/main/java/org/badminton/domain/common/consts/Constants.java
  badminton-domain/src/main/java/org/badminton/domain/league/entity/LeagueParticipantEntity.java
  badminton-domain/src/main/java/org/badminton/domain/match/model/entity/DoublesSetEntity.java
Labels: beforeLunch🍕, refactor✍️

#106 feat: 스웨거 파일 및 설정 파일 수정
  badminton-api/src/main/java/org/badminton/api/config/swagger/SwaggerConfig.java
  badminton-api/src/main/resources/application.yaml
Labels: 5PM🌝

#107 feat: CustomSuccessHandler 하드 코딩 부분 수정
  badminton-api/src/main/java/org/badminton/api/member/oauth2/CustomSuccessHandler.java
  badminton-api/src/main/resources/application.yaml
Labels: 5PM🌝

#109 feat: SecurityConfig 하드 코딩 부분 수정
  badminton-api/src/main/java/org/badminton/api/config/security/SecurityConfig.java
Labels: now❗️, 5PM🌝

#104 feat: 동호회 전체 조회, 필터 수정
  badminton-api/src/main/java/org/badminton/api/HomeController.java
  badminton-api/src/main/java/org/badminton/api/club/controller/ClubController.java
  badminton-api/src/main/java/org/badminton/api/club/model/dto/ClubsReadResponse.java
  badminton-api/src/main/java/org/badminton/api/club/service/ClubService.java
  badminton-api/src/main/java/org/badminton/api/clubmember/controller/ClubMemberController.java
  badminton-api/src/main/java/org/badminton/api/clubmember/model/dto/ClubMemberInfoResponse.java
  badminton-api/src/main/java/org/badminton/api/clubmember/service/ClubMemberService.java
  badminton-api/src/main/java/org/badminton/api/config/security/SecurityConfig.java
  badminton-api/src/main/java/org/badminton/api/config/security/SecurityUtil.java
  badminton-api/src/main/java/org/badminton/api/filter/ClubMembershipFilter.java
  badminton-api/src/main/java/org/badminton/api/filter/JwtAuthenticationFilter.java
  badminton-api/src/main/java/org/badminton/api/league/model/dto/LeagueCreateRequest.java
  badminton-api/src/main/java/org/badminton/api/league/service/LeagueService.java
  badminton-api/src/main/java/org/badminton/api/leaguerecord/service/LeagueRecordService.java
  badminton-domain/src/main/java/org/badminton/domain/club/repository/ClubRepository.java
  badminton-domain/src/main/java/org/badminton/domain/clubmember/repository/ClubMemberRepository.java
  badminton-domain/src/main/java/org/badminton/domain/leaguerecord/repository/LeagueRecordRepository.java
Labels: fix🛠️, feat✨, beforeLunch🍕

#112 feat: 동호회 회원 전체 조회 기능 구현
  badminton-api/src/main/java/org/badminton/api/clubmember/controller/ClubMemberController.java
  badminton-api/src/main/java/org/badminton/api/clubmember/model/dto/ClubMemberResponse.java
  badminton-api/src/main/java/org/badminton/api/clubmember/service/ClubMemberService.java
  badminton-api/src/main/java/org/badminton/api/match/model/dto/SinglesMatchResponse.java
  badminton-api/src/main/resources/data.sql
  badminton-domain/src/main/java/org/badminton/domain/clubmember/repository/ClubMemberRepository.java
  badminton-domain/src/main/java/org/badminton/domain/match/model/entity/SinglesSetEntity.java
Labels: feat✨, 5PM🌝

#114 refactor: League에 장소 추가
  badminton-api/src/main/java/org/badminton/api/league/model/dto/LeagueCreateRequest.java
  badminton-api/src/main/java/org/badminton/api/league/model/dto/LeagueCreateResponse.java
  badminton-api/src/main/java/org/badminton/api/league/model/dto/LeagueReadResponse.java
  badminton-api/src/main/java/org/badminton/api/league/model/dto/LeagueStatusUpdateResponse.java
  badminton-api/src/main/java/org/badminton/api/league/model/dto/LeagueUpdateRequest.java
  badminton-api/src/main/java/org/badminton/api/league/service/LeagueService.java
  badminton-api/src/main/resources/data.sql
  badminton-domain/src/main/java/org/badminton/domain/league/entity/LeagueEntity.java
Labels: 5PM🌝, refactor✍️

#116 feat: SecurityConfig 도메인 추가
  badminton-api/src/main/java/org/badminton/api/config/security/SecurityConfig.java
Labels: now❗️

#118 feat: 로그아웃 시 oAuth 연결끊기 구현
  badminton-api/src/main/java/org/badminton/api/club/model/dto/ClubsReadResponse.java
  badminton-api/src/main/java/org/badminton/api/config/jpa/JpaConfig.java
  badminton-api/src/main/java/org/badminton/api/filter/JwtAuthenticationFilter.java
  badminton-api/src/main/java/org/badminton/api/member/jwt/JwtUtil.java
  badminton-api/src/main/java/org/badminton/api/member/oauth2/CustomSuccessHandler.java
  badminton-api/src/main/java/org/badminton/api/member/oauth2/dto/CustomOAuth2Member.java
  badminton-api/src/main/java/org/badminton/api/member/service/CustomOAuth2MemberService.java
  badminton-api/src/main/java/org/badminton/api/member/service/MemberService.java
  badminton-api/src/main/resources/application.yaml
Labels: feat✨

#125 feat: 특정 년, 월을 통한 조회 기능 추가
  badminton-api/src/main/java/org/badminton/api/common/exception/league/InvalidDateTimeException.java
  badminton-api/src/main/java/org/badminton/api/league/controller/LeagueController.java
  badminton-api/src/main/java/org/badminton/api/league/service/LeagueService.java
  badminton-domain/src/main/java/org/badminton/domain/league/repository/LeagueRepository.java
Labels: feat✨

#127 feat: S3 이미지 업로드 인터페이스, 회원 프로필 사진 수정 시 S3 연결
  badminton-api/src/main/java/org/badminton/api/aws/s3/controller/ClubImageController.java
  badminton-api/src/main/java/org/badminton/api/aws/s3/model/dto/ImageUploadRequest.java
  badminton-api/src/main/java/org/badminton/api/aws/s3/service/AbstractFileUploadService.java
  badminton-api/src/main/java/org/badminton/api/aws/s3/service/ClubImageService.java
  badminton-api/src/main/java/org/badminton/api/aws/s3/service/ImageService.java
  badminton-api/src/main/java/org/badminton/api/aws/s3/service/MemberProfileImageService.java
  badminton-api/src/main/java/org/badminton/api/league/model/dto/LeagueCreateRequest.java
  badminton-api/src/main/java/org/badminton/api/member/controller/MemberController.java
  badminton-api/src/main/java/org/badminton/api/member/service/MemberService.java
Labels: feat✨

#129 feat: 현재 사용자의 동호회 조회 로직 구현
  badminton-api/src/main/java/org/badminton/api/club/controller/ClubController.java
  badminton-api/src/main/java/org/badminton/api/club/service/ClubService.java
  badminton-api/src/main/java/org/badminton/api/common/error/ErrorCode.java
  badminton-api/src/main/java/org/badminton/api/common/exception/member/MemberNotJoinedClubException.java
  badminton-api/src/main/java/org/badminton/api/config/security/SecurityConfig.java
Labels: feat✨

#131 feat: 동호회 검색 기능 구현
  badminton-api/src/main/java/org/badminton/api/club/controller/ClubController.java
  badminton-api/src/main/java/org/badminton/api/club/service/ClubService.java
  badminton-api/src/main/java/org/badminton/api/config/security/SecurityConfig.java
  badminton-api/src/main/resources/data.sql
  badminton-domain/src/main/java/org/badminton/domain/club/repository/ClubRepository.java
  badminton-domain/src/main/java/org/badminton/domain/leaguerecord/repository/LeagueRecordRepository.java
Labels: feat✨

#144 refactor: 회원 프로필 사진 등록, 변경 api 분리
  badminton-api/src/main/java/org/badminton/api/aws/s3/service/MemberProfileImageService.java
  badminton-api/src/main/java/org/badminton/api/config/security/SecurityConfig.java
  badminton-api/src/main/java/org/badminton/api/member/controller/MemberController.java
  badminton-api/src/main/java/org/badminton/api/member/service/MemberService.java
  badminton-domain/src/main/java/org/badminton/domain/member/entity/MemberEntity.java
Labels: refactor✍️

#145 refactor: MatchGenerationType Enum 생성
  badminton-api/src/main/java/org/badminton/api/league/model/dto/LeagueCreateRequest.java
  badminton-api/src/main/java/org/badminton/api/league/model/dto/LeagueCreateResponse.java
  badminton-api/src/main/java/org/badminton/api/league/model/dto/LeagueReadResponse.java
  badminton-api/src/main/java/org/badminton/api/league/model/dto/LeagueStatusUpdateResponse.java
  badminton-api/src/main/java/org/badminton/api/league/model/dto/LeagueUpdateRequest.java
  badminton-api/src/main/java/org/badminton/api/league/service/LeagueService.java
  badminton-api/src/main/resources/data.sql
  badminton-domain/src/main/java/org/badminton/domain/common/enums/MatchGenerationType.java
  badminton-domain/src/main/java/org/badminton/domain/league/entity/LeagueEntity.java
Labels: refactor✍️

#146 feat: 개발, 로컬 환경 로그 분리
  .github/workflows/ci-cd-build.yml
  .gitignore
  badminton-api/build.gradle
  badminton-api/src/main/resources/application.yaml
  badminton-api/src/main/resources/logback-spring.xml
  badminton-batch/build.gradle
  badminton-batch/src/main/resources/application.yaml
  badminton-batch/src/main/resources/logback-spring.xml
  build.gradle
Labels: 5PM🌝

#147 refactor: 동호회 중복 생성 방지
  badminton-api/src/main/java/org/badminton/api/club/controller/ClubController.java
  badminton-api/src/main/java/org/badminton/api/club/service/ClubService.java
  badminton-api/src/main/java/org/badminton/api/clubmember/service/ClubMemberService.java
  badminton-api/src/main/java/org/badminton/api/common/error/ErrorCode.java
  badminton-api/src/main/java/org/badminton/api/common/exception/member/MemberAlreadyExistInClubException.java
  badminton-api/src/main/java/org/badminton/api/league/model/dto/LeagueCreateRequest.java
  badminton-api/src/main/java/org/badminton/api/league/model/dto/LeagueUpdateRequest.java
  badminton-api/src/main/resources/data.sql
  badminton-domain/src/main/java/org/badminton/domain/clubmember/entity/ClubMemberBanEntity.java
  badminton-domain/src/main/java/org/badminton/domain/clubmember/entity/ClubMemberEntity.java
  badminton-domain/src/main/java/org/badminton/domain/clubmember/repository/ClubMemberRepository.java
Labels: 5PM🌝, refactor✍️

#148 feat: 프로덕션 환경을 위한 ci/cd 파일 수정
  .github/workflows/ci-cd-build.yml
Labels: feat✨, 5PM🌝

#153 refactor: 동호회 상세 조회에 티어별 회원수 추가
  badminton-api/src/main/java/org/badminton/api/club/controller/ClubController.java
  badminton-api/src/main/java/org/badminton/api/club/model/dto/ClubCardResponse.java
  badminton-api/src/main/java/org/badminton/api/club/model/dto/ClubDetailsResponse.java
  badminton-api/src/main/java/org/badminton/api/club/model/dto/ClubMemberCountByTier.java
  badminton-api/src/main/java/org/badminton/api/club/model/dto/ClubReadResponse.java
  badminton-api/src/main/java/org/badminton/api/club/service/ClubService.java
  badminton-domain/src/main/java/org/badminton/domain/club/entity/ClubEntity.java
Labels: 5PM🌝, refactor✍️

#156 refactor: 클럽멤버의 role 도 추가 명시
  badminton-api/src/main/java/org/badminton/api/clubmember/controller/ClubMemberController.java
  badminton-api/src/main/java/org/badminton/api/clubmember/model/Comparator/ClubMemberRoleComparator.java
  badminton-api/src/main/java/org/badminton/api/clubmember/model/dto/ClubMemberResponse.java
  badminton-api/src/main/java/org/badminton/api/clubmember/service/ClubMemberService.java
  badminton-api/src/main/java/org/badminton/api/league/model/enums/EndDateType.java
  badminton-api/src/main/java/org/badminton/api/league/model/enums/StartDateType.java
  badminton-api/src/main/java/org/badminton/api/league/service/LeagueService.java
Labels: beforeLunch🍕

#159 refactor: club card 조회 response 정렬 및 값 타입 수정
  .gitignore
  badminton-api/src/main/java/org/badminton/api/club/model/dto/ClubCardResponse.java
  badminton-api/src/main/java/org/badminton/api/club/model/dto/ClubMemberCountByTier.java
  badminton-api/src/main/java/org/badminton/api/clubmember/controller/ClubMemberController.java
  badminton-api/src/main/java/org/badminton/api/clubmember/model/dto/ClubMemberResponse.java
  badminton-api/src/main/java/org/badminton/api/leaguerecord/service/LeagueRecordService.java
  badminton-api/src/main/resources/data.sql
  badminton-domain/src/main/java/org/badminton/domain/club/entity/ClubEntity.java
Labels: refactor✍️

#162 feat: 세트별 경기 종료 후 db에 점수 저장하는 기능 구현
  badminton-api/src/main/java/org/badminton/api/club/service/ClubService.java
  badminton-api/src/main/java/org/badminton/api/match/DoublesMatchProgress.java
  badminton-api/src/main/java/org/badminton/api/match/SinglesMatchProgress.java
  badminton-api/src/main/java/org/badminton/api/match/controller/MatchController.java
  badminton-api/src/main/java/org/badminton/api/match/model/dto/SetScoreUpdateRequest.java
  badminton-api/src/main/java/org/badminton/api/match/model/dto/SetScoreUpdateResponse.java
  badminton-api/src/main/java/org/badminton/api/member/service/MemberService.java
  badminton-domain/src/main/java/org/badminton/domain/common/enums/MatchGenerationType.java
  badminton-domain/src/main/java/org/badminton/domain/member/entity/MemberEntity.java
Labels: feat✨, 5PM🌝

#167 refactor: League Status를 모집 중, 모집 완료 상태로 변경
  badminton-api/src/main/java/org/badminton/api/league/model/dto/LeagueCreateRequest.java
  badminton-api/src/main/java/org/badminton/api/league/model/dto/LeagueUpdateRequest.java
  badminton-api/src/main/java/org/badminton/api/league/service/LeagueService.java
  badminton-api/src/main/java/org/badminton/api/match/service/MatchCreateService.java
  badminton-api/src/main/resources/data.sql
  badminton-domain/src/main/java/org/badminton/domain/league/entity/LeagueEntity.java
  badminton-domain/src/main/java/org/badminton/domain/league/enums/LeagueStatus.java
Labels: refactor✍️

#168 feat: 동호회 Owner 가 동호회원 관리 로직 구현
  badminton-api/src/main/java/org/badminton/api/clubmember/AbstractClubMemberBanStrategy.java
  badminton-api/src/main/java/org/badminton/api/clubmember/BanStrategy.java
  badminton-api/src/main/java/org/badminton/api/clubmember/ClubMemberPenaltyStrategy.java
  badminton-api/src/main/java/org/badminton/api/clubmember/ExpelStrategy.java
  badminton-api/src/main/java/org/badminton/api/clubmember/controller/ClubMemberController.java
  badminton-api/src/main/java/org/badminton/api/clubmember/model/dto/ClubMemberBanRequest.java
  badminton-api/src/main/java/org/badminton/api/clubmember/model/dto/ClubMemberExpelRequest.java
  badminton-api/src/main/java/org/badminton/api/clubmember/model/dto/ClubMemberRoleUpdateRequest.java
  badminton-api/src/main/java/org/badminton/api/clubmember/model/dto/clubMemberBanRecordResponse.java
  badminton-api/src/main/java/org/badminton/api/clubmember/service/ClubMemberService.java
  badminton-api/src/main/java/org/badminton/api/common/error/ErrorCode.java
  badminton-api/src/main/java/org/badminton/api/common/exception/clubmember/ClubMemberAlreadyBannedException.java
  badminton-api/src/main/java/org/badminton/api/config/security/SecurityConfig.java
  badminton-domain/src/main/java/org/badminton/domain/clubmember/entity/BannedType.java
  badminton-domain/src/main/java/org/badminton/domain/clubmember/entity/ClubMemberBanRecordEntity.java
  badminton-domain/src/main/java/org/badminton/domain/clubmember/entity/ClubMemberEntity.java
  badminton-domain/src/main/java/org/badminton/domain/clubmember/repository/BannedClubMemberRepository.java
  badminton-domain/src/main/java/org/badminton/domain/clubmember/repository/ClubMemberRepository.java
Labels: feat✨

#169 fix: clubMember 조회 시 delete 한 clubMember 조회하지 못하게 수정
  badminton-api/src/main/java/org/badminton/api/club/service/ClubService.java
  badminton-api/src/main/java/org/badminton/api/filter/JwtAuthenticationFilter.java
  badminton-api/src/main/java/org/badminton/api/member/controller/MemberController.java
  badminton-api/src/main/java/org/badminton/api/member/oauth2/dto/CustomOAuth2Member.java
  badminton-api/src/main/java/org/badminton/api/member/service/MemberService.java
  badminton-domain/src/main/java/org/badminton/domain/clubmember/entity/ClubMemberEntity.java
  badminton-domain/src/main/java/org/badminton/domain/clubmember/repository/ClubMemberRepository.java
Labels: fix🛠️

#170 fix: 동호회 생성, 삭제 후 회원이 동호회에 가입되어있는지 확인 로직 에러 수정
  badminton-api/src/main/java/org/badminton/api/clubmember/service/ClubMemberService.java
  badminton-api/src/main/java/org/badminton/api/member/service/MemberService.java
  badminton-domain/src/main/java/org/badminton/domain/clubmember/repository/ClubMemberRepository.java
Labels: fix🛠️

#173 refactor: 경기 모집 인원이 다 차면 League Status를 COMPLETED로 변경
  badminton-api/src/main/java/org/badminton/api/common/error/ErrorCode.java
  badminton-api/src/main/java/org/badminton/api/common/exception/league/InvalidPlayerCountException.java
  badminton-api/src/main/java/org/badminton/api/common/exception/league/LeagueRecruitingCompletedException.java
  badminton-api/src/main/java/org/badminton/api/config/security/SecurityConfig.java
  badminton-api/src/main/java/org/badminton/api/league/service/LeagueParticipationService.java
  badminton-api/src/main/java/org/badminton/api/match/service/MatchCreateService.java
  badminton-domain/src/main/java/org/badminton/domain/league/entity/LeagueEntity.java
  badminton-domain/src/main/java/org/badminton/domain/league/enums/LeagueStatus.java
Labels: 5PM🌝, refactor✍️

#174 refactor: club response에 club id 추가
  badminton-api/src/main/java/org/badminton/api/club/model/dto/ClubCreateResponse.java
  badminton-api/src/main/java/org/badminton/api/club/model/dto/ClubDetailsResponse.java
  badminton-api/src/main/java/org/badminton/api/club/model/dto/ClubUpdateResponse.java
  badminton-api/src/main/java/org/badminton/api/club/service/ClubService.java
Labels: feat✨, 5PM🌝

#172 feat: 경기 신청 시 티어 검증 로직 추가
  badminton-api/src/main/java/org/badminton/api/clubmember/model/dto/ClubMemberMyPageResponse.java
  badminton-api/src/main/java/org/badminton/api/clubmember/service/ClubMemberService.java
  badminton-api/src/main/java/org/badminton/api/common/error/ErrorCode.java
  badminton-api/src/main/java/org/badminton/api/common/exception/league/InsufficientTierException.java
  badminton-api/src/main/java/org/badminton/api/league/service/LeagueParticipationService.java
  badminton-api/src/main/java/org/badminton/api/leaguerecord/dto/LeagueRecordInfoResponse.java
  badminton-api/src/main/java/org/badminton/api/leaguerecord/service/LeagueRecordService.java
  badminton-api/src/main/java/org/badminton/api/member/model/dto/MemberMyPageResponse.java
  badminton-api/src/main/java/org/badminton/api/member/service/MemberService.java
  badminton-api/src/main/resources/data.sql
  badminton-domain/src/main/java/org/badminton/domain/club/entity/ClubEntity.java
  badminton-domain/src/main/java/org/badminton/domain/clubmember/entity/ClubMemberEntity.java
  badminton-domain/src/main/java/org/badminton/domain/leaguerecord/entity/LeagueRecordEntity.java
  badminton-domain/src/main/java/org/badminton/domain/leaguerecord/repository/LeagueRecordRepository.java
Labels: feat✨, refactor✍️

#176 refactor: 배포 서버에서 로그아웃시 쿠키가 삭제되지 않는 이슈 해결
  badminton-api/src/main/java/org/badminton/api/member/service/MemberService.java
Labels: refactor✍️

#178 refactor: readClub response에 club에 가입되어 있는 사용자인지 boolean 값 추가
  badminton-api/src/main/java/org/badminton/api/club/controller/ClubController.java
  badminton-api/src/main/java/org/badminton/api/club/model/dto/ClubDetailsResponse.java
  badminton-api/src/main/java/org/badminton/api/club/service/ClubService.java
  badminton-api/src/main/java/org/badminton/api/config/security/SecurityConfig.java
  badminton-api/src/main/java/org/badminton/api/member/model/dto/MemberResponse.java
  badminton-api/src/main/java/org/badminton/api/member/oauth2/dto/CustomOAuth2Member.java
Labels: refactor✍️

#179 feat: validation 어노테이션
  badminton-api/build.gradle
  badminton-api/src/main/java/org/badminton/api/club/model/dto/ClubCreateRequest.java
  badminton-api/src/main/java/org/badminton/api/club/validation/ClubNameValidator.java
  badminton-api/src/main/java/org/badminton/api/club/validation/ClubNameValidatorImpl.java
  badminton-api/src/main/java/org/badminton/api/clubmember/model/dto/ClubMemberResponse.java
  badminton-api/src/main/java/org/badminton/api/common/error/ErrorCode.java
  badminton-api/src/main/java/org/badminton/api/common/response/ExceptionResponse.java
  badminton-api/src/main/java/org/badminton/api/exceptionhandler/BadmintonExceptionHandler.java
Labels: feat✨

#186 fix: Patch mapping CORS 에러 해결
  badminton-api/src/main/java/org/badminton/api/club/service/ClubService.java
  badminton-api/src/main/java/org/badminton/api/config/security/SecurityConfig.java
Labels: feat✨, beforeLunch🍕

#187 feat: get daily league schedule by date and month
  badminton-api/src/main/java/org/badminton/api/league/controller/LeagueController.java
  badminton-api/src/main/java/org/badminton/api/league/model/dto/LeagueByDateResponse.java
  badminton-api/src/main/java/org/badminton/api/league/service/LeagueService.java
Labels: feat✨, beforeLunch🍕

#188 feat: test 전용 서버를 위한 세팅
  .github/workflows/test-build.yml
  .gitignore
Labels: beforeLunch🍕

#189 feat: 동호회 회원, 동호회 관련 Validation 어노테이션 구현
  badminton-api/src/main/java/org/badminton/api/club/controller/ClubController.java
  badminton-api/src/main/java/org/badminton/api/club/model/dto/ClubCreateRequest.java
  badminton-api/src/main/java/org/badminton/api/club/model/dto/ClubUpdateRequest.java
  badminton-api/src/main/java/org/badminton/api/club/validation/ClubDescriptionValidator.java
  badminton-api/src/main/java/org/badminton/api/club/validation/ClubDescriptionValidatorImpl.java
  badminton-api/src/main/java/org/badminton/api/club/validation/ClubImageValidator.java
  badminton-api/src/main/java/org/badminton/api/club/validation/ClubImageValidatorImpl.java
  badminton-api/src/main/java/org/badminton/api/clubmember/controller/ClubMemberController.java
  badminton-api/src/main/java/org/badminton/api/clubmember/model/dto/ClubMemberBanRequest.java
  badminton-api/src/main/java/org/badminton/api/clubmember/model/dto/ClubMemberExpelRequest.java
  badminton-api/src/main/java/org/badminton/api/clubmember/validation/ReasonValidator.java
  badminton-api/src/main/java/org/badminton/api/clubmember/validation/ReasonValidatorImpl.java
  badminton-api/src/main/java/org/badminton/api/member/controller/MemberController.java
  badminton-api/src/main/java/org/badminton/api/member/model/dto/MemberUpdateRequest.java
  badminton-api/src/main/java/org/badminton/api/member/service/MemberService.java
  badminton-api/src/main/java/org/badminton/api/member/validator/MemberImageValidator.java
  badminton-api/src/main/java/org/badminton/api/member/validator/MemberImageValidatorImpl.java
  badminton-api/src/main/java/org/badminton/api/member/validator/MemberValidator.java
Labels: feat✨

#192 feat: 대진표 상세 조회, 대진별 세트 스코어 조회 api 추가
  badminton-api/src/main/java/org/badminton/api/common/error/ErrorCode.java
  badminton-api/src/main/java/org/badminton/api/common/exception/match/MatchDetailsNotExistException.java
  badminton-api/src/main/java/org/badminton/api/league/model/dto/LeagueAndParticipantResponse.java
  badminton-api/src/main/java/org/badminton/api/league/model/dto/LeagueByDateResponse.java
  badminton-api/src/main/java/org/badminton/api/league/model/dto/LeagueCreateResponse.java
  badminton-api/src/main/java/org/badminton/api/league/model/dto/LeagueStatusUpdateResponse.java
  badminton-api/src/main/java/org/badminton/api/league/service/LeagueParticipationService.java
  badminton-api/src/main/java/org/badminton/api/league/service/LeagueService.java
  badminton-api/src/main/java/org/badminton/api/match/DoublesMatchProgress.java
  badminton-api/src/main/java/org/badminton/api/match/MatchProgress.java
  badminton-api/src/main/java/org/badminton/api/match/SinglesMatchProgress.java
  badminton-api/src/main/java/org/badminton/api/match/controller/MatchController.java
  badminton-api/src/main/java/org/badminton/api/match/model/dto/DoublesMatchResponse.java
  badminton-api/src/main/java/org/badminton/api/match/model/dto/MatchDetailsResponse.java
  badminton-api/src/main/java/org/badminton/api/match/model/dto/MatchResponse.java
  badminton-api/src/main/java/org/badminton/api/match/model/dto/SetScoreResponse.java
  badminton-api/src/main/java/org/badminton/api/match/model/dto/SinglesMatchResponse.java
  badminton-api/src/main/java/org/badminton/api/match/model/dto/SinglesSetResponse.java
  badminton-api/src/main/java/org/badminton/api/match/service/MatchInitService.java
  badminton-api/src/main/resources/data.sql
  badminton-domain/src/main/java/org/badminton/domain/league/entity/LeagueEntity.java
  badminton-domain/src/main/java/org/badminton/domain/league/entity/LeagueParticipantEntity.java
  badminton-domain/src/main/java/org/badminton/domain/league/repository/LeagueParticipantRepository.java
  badminton-domain/src/main/java/org/badminton/domain/match/model/entity/DoublesMatchEntity.java
  badminton-domain/src/main/java/org/badminton/domain/match/model/entity/SinglesSetEntity.java
Labels: feat✨, 5PM🌝

#198 refactor: 경기에 참여했는지 여부를 경기 상세 조회 response에 추가
  badminton-api/src/main/java/org/badminton/api/config/security/SecurityConfig.java
  badminton-api/src/main/java/org/badminton/api/league/controller/LeagueController.java
  badminton-api/src/main/java/org/badminton/api/league/service/LeagueService.java
  badminton-domain/src/main/java/org/badminton/domain/league/repository/LeagueParticipantRepository.java
Labels: now❗️, refactor✍️

#199 fix: ban된 동호회 회원 총 회원 수에 추가
  badminton-api/src/main/java/org/badminton/api/club/controller/ClubController.java
  badminton-api/src/main/java/org/badminton/api/club/model/dto/ClubDetailsResponse.java
  badminton-api/src/main/java/org/badminton/api/club/service/ClubService.java
  badminton-domain/src/main/java/org/badminton/domain/club/entity/ClubEntity.java
  badminton-domain/src/main/java/org/badminton/domain/clubmember/repository/ClubMemberRepository.java
Labels: fix🛠️

#203 fix: 경기 조회 시 여러 개의 League Participant 반환하여 생기는 문제 해결
  badminton-api/src/main/java/org/badminton/api/club/service/ClubService.java
  badminton-api/src/main/java/org/badminton/api/clubmember/AbstractClubMemberBanStrategy.java
  badminton-api/src/main/java/org/badminton/api/clubmember/ClubMemberPenaltyStrategy.java
  badminton-api/src/main/java/org/badminton/api/clubmember/controller/ClubMemberController.java
  badminton-api/src/main/java/org/badminton/api/clubmember/model/dto/ClubMemberBanRecordResponse.java
  badminton-api/src/main/java/org/badminton/api/clubmember/model/dto/ClubMemberWithdrawResponse.java
  badminton-api/src/main/java/org/badminton/api/clubmember/service/ClubMemberService.java
  badminton-api/src/main/java/org/badminton/api/league/service/LeagueService.java
  badminton-domain/src/main/java/org/badminton/domain/clubmember/entity/ClubMemberEntity.java
  badminton-domain/src/main/java/org/badminton/domain/league/repository/LeagueParticipantRepository.java
Labels: fix🛠️, now❗️

#204 fix: 경기 조회 시 경기 참여 여부를 나타내는 필드가 항상 true로 나타나는 문제 해결
  badminton-api/src/main/java/org/badminton/api/league/service/LeagueService.java
  badminton-domain/src/main/java/org/badminton/domain/league/repository/LeagueParticipantRepository.java
Labels: fix🛠️, now❗️

#205 fix: 경기 참여 신청 및 취소 시 경기 모집 인원 카운트 update
  badminton-api/src/main/java/org/badminton/api/league/service/LeagueService.java
  badminton-domain/src/main/java/org/badminton/domain/league/repository/LeagueParticipantRepository.java
Labels: fix🛠️, now❗️

#206 fix: 경기 참여 신청과 취소를 반복적으로 수행했을 때 경기 조회 시 모집 인원 카운트에 발생하는 문제 해결
  badminton-api/src/main/java/org/badminton/api/config/security/SecurityConfig.java
  badminton-api/src/main/java/org/badminton/api/league/model/dto/LeagueUpdateRequest.java
  badminton-api/src/main/java/org/badminton/api/league/service/LeagueParticipationService.java
  badminton-domain/src/main/java/org/badminton/domain/league/entity/LeagueParticipantEntity.java
  badminton-domain/src/main/java/org/badminton/domain/league/repository/LeagueParticipantRepository.java
Labels: fix🛠️, now❗️

#207 feat: 회원이 본인의 Match 기록을 확인 할 수 있는 기능 구현
  badminton-api/src/main/java/org/badminton/api/aws/s3/service/MemberProfileImageService.java
  badminton-api/src/main/java/org/badminton/api/config/security/SecurityConfig.java
  badminton-api/src/main/java/org/badminton/api/match/model/dto/DoublesMatchResultResponse.java
  badminton-api/src/main/java/org/badminton/api/match/model/dto/MatchResultResponse.java
  badminton-api/src/main/java/org/badminton/api/match/model/dto/SinglesMatchResultResponse.java
  badminton-api/src/main/java/org/badminton/api/match/model/dto/TeamResultResponse.java
  badminton-api/src/main/java/org/badminton/api/match/service/MatchResultService.java
  badminton-api/src/main/java/org/badminton/api/member/controller/MemberController.java
  badminton-domain/src/main/java/org/badminton/domain/match/repository/DoublesMatchRepository.java
  badminton-domain/src/main/java/org/badminton/domain/match/repository/SinglesMatchRepository.java
Labels: feat✨, now❗️

#211 bug: 버킷 네임 우회 및 저장 방식 통일
  badminton-api/src/main/java/org/badminton/api/aws/s3/controller/ClubImageController.java
  badminton-api/src/main/java/org/badminton/api/aws/s3/service/AbstractFileUploadService.java
  badminton-api/src/main/java/org/badminton/api/aws/s3/service/ClubImageService.java
  badminton-api/src/main/java/org/badminton/api/aws/s3/service/MemberProfileImageService.java
  badminton-api/src/main/resources/data.sql
Labels: hotfix🥵, now❗️

#213 feat: withdraw club member from club
  badminton-api/src/main/java/org/badminton/api/club/model/dto/ClubCreateRequest.java
  badminton-api/src/main/java/org/badminton/api/clubmember/controller/ClubMemberController.java
  badminton-api/src/main/java/org/badminton/api/clubmember/service/ClubMemberService.java
  badminton-api/src/main/java/org/badminton/api/config/security/SecurityConfig.java
  badminton-api/src/main/java/org/badminton/api/league/controller/LeagueController.java
  badminton-api/src/main/java/org/badminton/api/league/model/dto/LeagueCancelResponse.java
  badminton-api/src/main/java/org/badminton/api/league/model/dto/LeagueCreateRequest.java
  badminton-api/src/main/java/org/badminton/api/league/model/dto/LeagueDetailsResponse.java
  badminton-api/src/main/java/org/badminton/api/league/service/LeagueService.java
  badminton-api/src/main/java/org/badminton/api/member/service/MemberService.java
  badminton-api/src/test/java/org/badminton/api/league/service/LeagueServiceTest.java
Labels: feat✨, now❗️

#214 feat: 대진표가 생성되지 않았을 때 isMatchedCreated 필드를 false로 반환.
  badminton-api/src/main/java/org/badminton/api/league/model/dto/LeagueDetailsResponse.java
  badminton-api/src/main/java/org/badminton/api/league/service/LeagueService.java
Labels: hotfix🥵, now❗️

#215 fix: 동호회 이미지, 회원 이미지 수정 validation 수정
  badminton-api/src/main/java/org/badminton/api/club/controller/ClubController.java
  badminton-api/src/main/java/org/badminton/api/club/validation/ClubImageValidatorImpl.java
  badminton-api/src/main/java/org/badminton/api/member/controller/MemberController.java
  badminton-api/src/main/java/org/badminton/api/member/validator/MemberImageValidatorImpl.java
Labels: fix🛠️

#223 bug : clubToken 가져오기 수정
  badminton-api/src/main/java/org/badminton/api/config/security/SecurityConfig.java
  badminton-api/src/main/java/org/badminton/api/filter/ClubMembershipFilter.java
Labels: 5PM🌝

#226 refactoring: memberController,Service에서 jwtUtil 설정과 oAuth 관련 메서드 분리
  badminton-api/src/main/java/org/badminton/api/application/auth/AuthFacade.java
  badminton-api/src/main/java/org/badminton/api/application/auth/CustomOAuth2MemberService.java
  badminton-api/src/main/java/org/badminton/api/application/club/ClubFacade.java
  badminton-api/src/main/java/org/badminton/api/config/security/ClubPermissionEvaluator.java
  badminton-api/src/main/java/org/badminton/api/config/security/SecurityConfig.java
  badminton-api/src/main/java/org/badminton/api/filter/ClubMembershipFilter.java
  badminton-api/src/main/java/org/badminton/api/filter/JwtAuthenticationFilter.java
  badminton-api/src/main/java/org/badminton/api/interfaces/auth/AuthDtoMapper.java
  badminton-api/src/main/java/org/badminton/api/interfaces/auth/controller/AuthController.java
  badminton-api/src/main/java/org/badminton/api/interfaces/auth/dto/CustomOAuth2Member.java
  badminton-api/src/main/java/org/badminton/api/interfaces/auth/dto/GoogleAttributeDto.java
  badminton-api/src/main/java/org/badminton/api/interfaces/auth/dto/GoogleResponse.java
  badminton-api/src/main/java/org/badminton/api/interfaces/auth/dto/KakaoAccountDto.java
  badminton-api/src/main/java/org/badminton/api/interfaces/auth/dto/KakaoAttributeDto.java
  badminton-api/src/main/java/org/badminton/api/interfaces/auth/dto/KakaoProfileDto.java
  badminton-api/src/main/java/org/badminton/api/interfaces/auth/dto/KakaoResponse.java
  badminton-api/src/main/java/org/badminton/api/interfaces/auth/dto/MemberDeleteResponse.java
  badminton-api/src/main/java/org/badminton/api/interfaces/auth/dto/NaverAttributeDto.java
  badminton-api/src/main/java/org/badminton/api/interfaces/auth/dto/NaverResponse.java
  badminton-api/src/main/java/org/badminton/api/interfaces/auth/dto/OAuthResponse.java
  badminton-api/src/main/java/org/badminton/api/interfaces/auth/jwt/JwtUtil.java
  badminton-api/src/main/java/org/badminton/api/interfaces/auth/successhandler/CustomSuccessHandler.java
  badminton-api/src/main/java/org/badminton/api/interfaces/club/controller/ClubController.java
  badminton-api/src/main/java/org/badminton/api/interfaces/clubmember/controller/ClubMemberController.java
  badminton-api/src/main/java/org/badminton/api/interfaces/member/MemberDtoMapper.java
  badminton-api/src/main/java/org/badminton/api/interfaces/member/controller/MemberController.java
  badminton-api/src/main/java/org/badminton/api/interfaces/member/dto/MemberDeleteResponse.java
  badminton-api/src/main/java/org/badminton/api/interfaces/oauth/dto/GoogleResponse.java
  badminton-api/src/main/java/org/badminton/api/interfaces/oauth/dto/KakaoResponse.java
  badminton-api/src/main/java/org/badminton/api/interfaces/oauth/dto/NaverResponse.java
  badminton-api/src/main/java/org/badminton/api/interfaces/oauth/dto/OAuthResponse.java
  badminton-api/src/main/java/org/badminton/api/interfaces/oauth/jwt/JwtUtil.java
  badminton-api/src/main/java/org/badminton/api/interfaces/oauth/successhandler/CustomSuccessHandler.java
  badminton-domain/src/main/java/org/badminton/domain/domain/auth/info/MemberDeleteInfo.java
  badminton-domain/src/main/java/org/badminton/domain/domain/auth/service/AuthService.java
  badminton-domain/src/main/java/org/badminton/domain/domain/auth/service/AuthServiceImpl.java
Labels: refactor✍️

#227 refactor: clubId 파라미터 clubToken으로 변경
  badminton-api/src/main/java/org/badminton/api/interfaces/match/controller/MatchController.java
Labels: refactor✍️

#229 refactor: MatchEntity -> Match, matchId -> id 이름 변경
  badminton-api/src/main/java/org/badminton/api/application/match/MyMatchFacade.java
  badminton-api/src/main/java/org/badminton/api/interfaces/match/dto/DoublesMatchResultResponse.java
  badminton-api/src/main/java/org/badminton/api/interfaces/match/dto/MatchResultResponse.java
  badminton-api/src/main/java/org/badminton/api/interfaces/match/dto/SinglesMatchResultResponse.java
  badminton-api/src/main/java/org/badminton/api/interfaces/match/dto/TeamResultResponse.java
  badminton-api/src/main/java/org/badminton/api/interfaces/member/controller/MemberController.java
  badminton-api/src/main/java/org/badminton/api/service/match/MatchResultService.java
  badminton-domain/src/main/java/org/badminton/domain/domain/match/entity/DoublesMatch.java
  badminton-domain/src/main/java/org/badminton/domain/domain/match/entity/DoublesSetEntity.java
  badminton-domain/src/main/java/org/badminton/domain/domain/match/entity/SinglesMatch.java
  badminton-domain/src/main/java/org/badminton/domain/domain/match/entity/SinglesMatchEntity.java
  badminton-domain/src/main/java/org/badminton/domain/domain/match/entity/SinglesSetEntity.java
  badminton-domain/src/main/java/org/badminton/domain/domain/match/info/BracketInfo.java
  badminton-domain/src/main/java/org/badminton/domain/domain/match/info/DoublesMatchInfo.java
  badminton-domain/src/main/java/org/badminton/domain/domain/match/info/DoublesMatchResultInfo.java
  badminton-domain/src/main/java/org/badminton/domain/domain/match/info/MatchInfo.java
  badminton-domain/src/main/java/org/badminton/domain/domain/match/info/MatchResultInfo.java
  badminton-domain/src/main/java/org/badminton/domain/domain/match/info/SinglesMatchInfo.java
  badminton-domain/src/main/java/org/badminton/domain/domain/match/info/SinglesMatchResultInfo.java
  badminton-domain/src/main/java/org/badminton/domain/domain/match/info/TeamInfo.java
  badminton-domain/src/main/java/org/badminton/domain/domain/match/info/TeamPlayerNameInfo.java
  badminton-domain/src/main/java/org/badminton/domain/domain/match/reader/DoublesMatchStore.java
  badminton-domain/src/main/java/org/badminton/domain/domain/match/reader/SinglesMatchStore.java
  badminton-domain/src/main/java/org/badminton/domain/domain/match/service/MatchResultService.java
  badminton-domain/src/main/java/org/badminton/domain/domain/match/service/MatchResultServiceImpl.java
  badminton-domain/src/main/java/org/badminton/domain/domain/match/service/MatchRetrieveService.java
  badminton-domain/src/main/java/org/badminton/domain/domain/match/service/MatchStrategy.java
  badminton-domain/src/main/java/org/badminton/domain/domain/match/store/DoublesMatchReader.java
  badminton-domain/src/main/java/org/badminton/domain/domain/match/store/SinglesMatchReader.java
  badminton-domain/src/main/java/org/badminton/domain/infrastructures/match/reader/DoublesMatchReaderImpl.java
  badminton-domain/src/main/java/org/badminton/domain/infrastructures/match/reader/SinglesMatchReaderImpl.java
  badminton-domain/src/main/java/org/badminton/domain/infrastructures/match/repository/DoublesMatchRepository.java
  badminton-domain/src/main/java/org/badminton/domain/infrastructures/match/repository/SinglesMatchRepository.java
  badminton-domain/src/main/java/org/badminton/domain/infrastructures/match/service/MatchRetrieveServiceImpl.java
  badminton-domain/src/main/java/org/badminton/domain/infrastructures/match/store/DoublesMatchStoreImpl.java
  badminton-domain/src/main/java/org/badminton/domain/infrastructures/match/store/SinglesMatchStoreImpl.java
  badminton-domain/src/main/java/org/badminton/domain/infrastructures/match/strategy/FreeDoublesMatchStrategy.java
  badminton-domain/src/main/java/org/badminton/domain/infrastructures/match/strategy/FreeSinglesMatchStrategy.java
Labels: 5PM🌝, refactor✍️

#232 refactor : ClubStatistics 구성 요소 추가 및 AbstractBaseTime 명명
  badminton-api/src/main/java/org/badminton/api/application/club/ClubFacade.java
  badminton-domain/src/main/java/org/badminton/domain/common/AbstractBaseTime.java
  badminton-domain/src/main/java/org/badminton/domain/domain/club/entity/Club.java
  badminton-domain/src/main/java/org/badminton/domain/domain/club/info/ClubCreateInfo.java
  badminton-domain/src/main/java/org/badminton/domain/domain/clubmember/entity/ClubMember.java
  badminton-domain/src/main/java/org/badminton/domain/domain/clubmember/entity/ClubMemberBanRecord.java
  badminton-domain/src/main/java/org/badminton/domain/domain/league/entity/League.java
  badminton-domain/src/main/java/org/badminton/domain/domain/league/entity/LeagueParticipant.java
  badminton-domain/src/main/java/org/badminton/domain/domain/league/entity/LeagueRecord.java
  badminton-domain/src/main/java/org/badminton/domain/domain/match/entity/DoublesMatch.java
  badminton-domain/src/main/java/org/badminton/domain/domain/match/entity/DoublesSetEntity.java
  badminton-domain/src/main/java/org/badminton/domain/domain/match/entity/SinglesMatch.java
  badminton-domain/src/main/java/org/badminton/domain/domain/match/entity/SinglesSetEntity.java
  badminton-domain/src/main/java/org/badminton/domain/domain/member/entity/Member.java
  badminton-domain/src/main/java/org/badminton/domain/domain/statistics/ClubStatistics.java
  badminton-domain/src/main/java/org/badminton/domain/domain/statistics/ClubStatisticsReader.java
  badminton-domain/src/main/java/org/badminton/domain/domain/statistics/ClubStatisticsService.java
  badminton-domain/src/main/java/org/badminton/domain/domain/statistics/ClubStatisticsServiceImpl.java
  badminton-domain/src/main/java/org/badminton/domain/domain/statistics/ClubStatisticsStore.java
  badminton-domain/src/main/java/org/badminton/domain/infrastructures/statistics/ClubStatisticsReaderImpl.java
  badminton-domain/src/main/java/org/badminton/domain/infrastructures/statistics/ClubStatisticsRepository.java
  badminton-domain/src/main/java/org/badminton/domain/infrastructures/statistics/ClubStatisticsStoreImpl.java
Labels: refactor✍️

#242 241 bug bug when deploy by test api
  .github/workflows/ci-cd-build.yml
  .github/workflows/test-build.yml
  api/Dockerfile
  api/src/main/java/org/badminton/api/BadmintonApplication.java
  api/src/main/java/org/badminton/api/application/clubMember/ClubMemberFacade.java
  api/src/main/java/org/badminton/api/application/statistics/ClubStatisticsFacade.java
  api/src/main/java/org/badminton/api/interfaces/clubmember/ClubMemberDtoMapper.java
  api/src/main/java/org/badminton/api/interfaces/clubmember/controller/ClubMemberController.java
  api/src/main/java/org/badminton/api/interfaces/clubmember/dto/ClubMemberStatusResponse.java
  api/src/main/java/org/badminton/api/interfaces/statistics/ClubStatisticsController.java
  batch/Dockerfile
  batch/src/main/java/springproject/badmintonbatch/config/jpa/JpaConfig.java
  batch/src/main/resources/application.yaml
  docker-compose.yaml
  domain/src/main/java/org/badminton/domain/domain/clubmember/ClubMemberReader.java
  domain/src/main/java/org/badminton/domain/domain/clubmember/command/ClubMemberMyPageCommand.java
  domain/src/main/java/org/badminton/domain/domain/clubmember/command/ClubMemberStatusCommand.java
  domain/src/main/java/org/badminton/domain/domain/clubmember/entity/BannedType.java
  domain/src/main/java/org/badminton/domain/domain/clubmember/entity/ClubMember.java
  domain/src/main/java/org/badminton/domain/domain/clubmember/info/ClubMemberDetailInfo.java
  domain/src/main/java/org/badminton/domain/domain/clubmember/info/ClubMemberStatusInfo.java
  domain/src/main/java/org/badminton/domain/domain/clubmember/service/ClubMemberService.java
  domain/src/main/java/org/badminton/domain/domain/clubmember/service/ClubMemberServiceImpl.java
  domain/src/main/java/org/badminton/domain/domain/statistics/ClubStatistics.java
  domain/src/main/java/org/badminton/domain/domain/statistics/ClubStatisticsReader.java
  domain/src/main/java/org/badminton/domain/domain/statistics/ClubStatisticsService.java
  domain/src/main/java/org/badminton/domain/domain/statistics/ClubStatisticsServiceImpl.java
  domain/src/main/java/org/badminton/domain/domain/statistics/ClubStatisticsStore.java
  infrastructure/build.gradle
  infrastructure/src/main/java/org/badminton/infrastructure/clubmember/ClubMemberReaderImpl.java
  infrastructure/src/main/java/org/badminton/infrastructure/clubmember/ClubMemberRepository.java
  infrastructure/src/main/java/org/badminton/infrastructure/statistics/ClubStatisticsReaderImpl.java
  infrastructure/src/main/java/org/badminton/infrastructure/statistics/ClubStatisticsRepository.java
  infrastructure/src/main/java/org/badminton/infrastructure/statistics/ClubStatisticsStoreImpl.java
Labels: hotfix🥵

#235 feat: 리프레시 토큰 구현
  api/src/main/java/org/badminton/api/application/auth/AuthFacade.java
  api/src/main/java/org/badminton/api/common/exception/member/MemberNotExistException.java
  api/src/main/java/org/badminton/api/filter/JwtAuthenticationFilter.java
  api/src/main/java/org/badminton/api/interfaces/auth/controller/AuthController.java
  api/src/main/java/org/badminton/api/interfaces/auth/dto/CustomOAuth2Member.java
  api/src/main/java/org/badminton/api/interfaces/auth/jwt/JwtUtil.java
  api/src/main/java/org/badminton/api/interfaces/auth/successhandler/CustomSuccessHandler.java
  domain/src/main/java/org/badminton/domain/domain/auth/service/AuthServiceImpl.java
  domain/src/main/java/org/badminton/domain/domain/member/MemberReader.java
  infrastructure/src/main/java/org/badminton/infrastructure/member/MemberReaderImpl.java
Labels: feat✨

#244 hotfix: change expireTime
  api/src/main/java/org/badminton/api/interfaces/auth/jwt/JwtUtil.java
Labels: hotfix🥵

#245 feat : 경기 생성 통계 추가
  api/src/main/java/org/badminton/api/application/statistics/ClubStatisticsFacade.java
  api/src/main/resources/data.sql
  domain/src/main/java/org/badminton/domain/domain/league/LeagueReader.java
  domain/src/main/java/org/badminton/domain/domain/league/LeagueService.java
  domain/src/main/java/org/badminton/domain/domain/league/LeagueServiceImpl.java
  domain/src/main/java/org/badminton/domain/domain/statistics/ClubStatistics.java
  domain/src/main/java/org/badminton/domain/domain/statistics/ClubStatisticsService.java
  domain/src/main/java/org/badminton/domain/domain/statistics/ClubStatisticsServiceImpl.java
  infrastructure/src/main/java/org/badminton/infrastructure/league/LeagueReaderImpl.java
  infrastructure/src/main/java/org/badminton/infrastructure/league/LeagueRepository.java
Labels: beforeLunch🍕

#248 feat : 인기순, 활동순으로 정렬
  api/src/main/java/org/badminton/api/application/club/ClubRankFacade.java
  api/src/main/java/org/badminton/api/application/club/strategy/ActivityClub.java
  api/src/main/java/org/badminton/api/application/club/strategy/PopularClub.java
  api/src/main/java/org/badminton/api/application/club/strategy/Rank.java
  api/src/main/java/org/badminton/api/interfaces/club/controller/ClubController.java
  domain/src/main/java/org/badminton/domain/domain/club/ClubReader.java
  domain/src/main/java/org/badminton/domain/domain/club/ClubService.java
  domain/src/main/java/org/badminton/domain/domain/club/ClubServiceImpl.java
  domain/src/main/java/org/badminton/domain/domain/statistics/ClubStatistics.java
  domain/src/main/java/org/badminton/domain/domain/statistics/ClubStatisticsReader.java
  domain/src/main/java/org/badminton/domain/domain/statistics/ClubStatisticsService.java
  domain/src/main/java/org/badminton/domain/domain/statistics/ClubStatisticsServiceImpl.java
  domain/src/main/java/org/badminton/domain/domain/statistics/command/ClubStatisticsCommand.java
  infrastructure/src/main/java/org/badminton/infrastructure/club/ClubReaderImpl.java
  infrastructure/src/main/java/org/badminton/infrastructure/club/ClubRepository.java
  infrastructure/src/main/java/org/badminton/infrastructure/statistics/ClubStatisticsReaderImpl.java
Labels: 5PM🌝

#251 234 feat add current match result response in main page
  api/src/main/java/org/badminton/api/application/match/MatchFacade.java
  api/src/main/java/org/badminton/api/config/security/SecurityConfig.java
  api/src/main/java/org/badminton/api/interfaces/league/controller/MainLeagueController.java
  api/src/main/java/org/badminton/api/interfaces/match/dto/DoublesMatchPlayerResponse.java
  api/src/main/java/org/badminton/api/interfaces/match/dto/DoublesSetResponse.java
  api/src/main/java/org/badminton/api/interfaces/match/dto/LeagueSetsScoreInProgressResponse.java
  api/src/main/java/org/badminton/api/interfaces/match/dto/SinglesMatchPlayerResponse.java
  api/src/main/resources/data.sql
  domain/src/main/java/org/badminton/domain/domain/league/LeagueServiceImpl.java
  domain/src/main/java/org/badminton/domain/domain/match/entity/DoublesMatch.java
  domain/src/main/java/org/badminton/domain/domain/match/entity/DoublesSet.java
  domain/src/main/java/org/badminton/domain/domain/match/entity/SinglesMatch.java
  domain/src/main/java/org/badminton/domain/domain/match/entity/SinglesSet.java
  domain/src/main/java/org/badminton/domain/domain/match/info/DoublesMatchPlayerInfo.java
  domain/src/main/java/org/badminton/domain/domain/match/info/DoublesSetInfo.java
  domain/src/main/java/org/badminton/domain/domain/match/info/LeagueSetsScoreInProgressInfo.java
  domain/src/main/java/org/badminton/domain/domain/match/info/SetInfo.java
  domain/src/main/java/org/badminton/domain/domain/match/info/SinglesMatchPlayerInfo.java
  domain/src/main/java/org/badminton/domain/domain/match/service/MatchRetrieveService.java
  domain/src/main/java/org/badminton/domain/domain/match/service/MatchStrategy.java
  infrastructure/src/main/java/org/badminton/infrastructure/match/service/MatchRetrieveServiceImpl.java
  infrastructure/src/main/java/org/badminton/infrastructure/match/strategy/FreeDoublesMatchStrategy.java
  infrastructure/src/main/java/org/badminton/infrastructure/match/strategy/FreeSinglesMatchStrategy.java
Labels: now❗️, beforeLunch🍕

#253 feat: 배포 시 모듈별로 실행
  .github/workflows/ci-cd-build.yml
  .github/workflows/test-build.yml
  api/Dockerfile
  api/src/main/resources/data.sql
  batch/Dockerfile
Labels: 5PM🌝

#255 feat: 252 feat club application
  api/src/main/java/org/badminton/api/application/auth/AuthFacade.java
  api/src/main/java/org/badminton/api/application/clubMember/ClubMemberFacade.java
  api/src/main/java/org/badminton/api/interfaces/club/controller/ClubController.java
  api/src/main/java/org/badminton/api/interfaces/clubmember/ClubMemberDtoMapper.java
  api/src/main/java/org/badminton/api/interfaces/clubmember/controller/ClubMemberController.java
  api/src/main/java/org/badminton/api/interfaces/clubmember/dto/ApplyClubResponse.java
  api/src/main/java/org/badminton/api/interfaces/clubmember/dto/ApproveApplyResponse.java
  api/src/main/java/org/badminton/api/interfaces/clubmember/dto/RejectApplyResponse.java
  domain/src/main/java/org/badminton/domain/common/error/ErrorCode.java
  domain/src/main/java/org/badminton/domain/common/exception/clubmember/MemberAlreadyApplyClubException.java
  domain/src/main/java/org/badminton/domain/common/exception/member/MemberAlreadyExistInClubException.java
  domain/src/main/java/org/badminton/domain/domain/club/ClubApplyReader.java
  domain/src/main/java/org/badminton/domain/domain/club/ClubApplyService.java
  domain/src/main/java/org/badminton/domain/domain/club/ClubApplyServiceImpl.java
  domain/src/main/java/org/badminton/domain/domain/club/ClubApplyStore.java
  domain/src/main/java/org/badminton/domain/domain/club/ClubRegistrationReader.java
  domain/src/main/java/org/badminton/domain/domain/club/ClubRegistrationService.java
  domain/src/main/java/org/badminton/domain/domain/club/ClubRegistrationServiceImpl.java
  domain/src/main/java/org/badminton/domain/domain/club/ClubRegistrationStore.java
  domain/src/main/java/org/badminton/domain/domain/club/command/ApproveRegistrationCommand.java
  domain/src/main/java/org/badminton/domain/domain/club/command/RegistrationClubCommand.java
  domain/src/main/java/org/badminton/domain/domain/club/command/RejectRegistrationCommand.java
  domain/src/main/java/org/badminton/domain/domain/club/entity/ClubApply.java
  domain/src/main/java/org/badminton/domain/domain/clubmember/info/ApplyClubInfo.java
  domain/src/main/java/org/badminton/domain/domain/clubmember/info/ApproveApplyInfo.java
  domain/src/main/java/org/badminton/domain/domain/clubmember/info/RejectApplyInfo.java
  domain/src/main/java/org/badminton/domain/domain/clubmember/service/ClubMemberService.java
  domain/src/main/java/org/badminton/domain/domain/clubmember/service/ClubMemberServiceImpl.java
  infrastructure/src/main/java/org/badminton/infrastructure/club/ClubApplyReaderImpl.java
  infrastructure/src/main/java/org/badminton/infrastructure/club/ClubApplyRepository.java
  infrastructure/src/main/java/org/badminton/infrastructure/club/ClubApplyStoreImpl.java
  infrastructure/src/main/java/org/badminton/infrastructure/club/ClubRegistrationReaderImpl.java
  infrastructure/src/main/java/org/badminton/infrastructure/club/ClubRegistrationRepository.java
  infrastructure/src/main/java/org/badminton/infrastructure/club/ClubRegistrationStoreImpl.java
Labels: feat✨

#260 hotfix: filter return 추가
  api/src/main/java/org/badminton/api/application/statistics/ClubStatisticsFacade.java
  api/src/main/java/org/badminton/api/filter/JwtAuthenticationFilter.java
  api/src/main/java/org/badminton/api/interfaces/club/controller/ClubDtoMapper.java
  api/src/main/java/org/badminton/api/interfaces/club/dto/ClubDeleteResponse.java
  api/src/main/java/org/badminton/api/interfaces/league/controller/LeagueDtoMapper.java
  api/src/main/java/org/badminton/api/interfaces/league/controller/LeagueParticipationController.java
  api/src/main/java/org/badminton/api/interfaces/league/dto/LeagueParticipantResponse.java
  api/src/main/java/org/badminton/api/interfaces/match/dto/SinglesSetResponse.java
  api/src/main/java/org/badminton/api/interfaces/member/dto/MemberIsClubMemberResponse.java
  domain/src/main/java/org/badminton/domain/domain/club/entity/ClubApply.java
  domain/src/main/java/org/badminton/domain/domain/club/info/ClubDeleteInfo.java
  domain/src/main/java/org/badminton/domain/domain/clubmember/ClubMemberReader.java
  domain/src/main/java/org/badminton/domain/domain/clubmember/service/ClubMemberService.java
  domain/src/main/java/org/badminton/domain/domain/clubmember/service/ClubMemberServiceImpl.java
  domain/src/main/java/org/badminton/domain/domain/league/info/LeagueParticipantInfo.java
  infrastructure/src/main/java/org/badminton/infrastructure/clubmember/ClubMemberReaderImpl.java
Labels: hotfix🥵

#261 feat: match sets core board 조회 기능 구현
  api/src/main/java/org/badminton/api/application/match/MatchFacade.java
  api/src/main/java/org/badminton/api/interfaces/match/controller/MatchController.java
  api/src/main/java/org/badminton/api/interfaces/match/dto/MatchSetResponse.java
  domain/src/main/java/org/badminton/domain/domain/match/entity/DoublesMatch.java
  domain/src/main/java/org/badminton/domain/domain/match/entity/SinglesMatch.java
  domain/src/main/java/org/badminton/domain/domain/match/info/DoublesMatchPlayerInfo.java
  domain/src/main/java/org/badminton/domain/domain/match/info/MatchSetInfo.java
  domain/src/main/java/org/badminton/domain/domain/match/info/SinglesMatchPlayerInfo.java
  domain/src/main/java/org/badminton/domain/domain/match/service/MatchRetrieveService.java
  domain/src/main/java/org/badminton/domain/domain/match/service/MatchStrategy.java
  infrastructure/src/main/java/org/badminton/infrastructure/match/service/MatchRetrieveServiceImpl.java
  infrastructure/src/main/java/org/badminton/infrastructure/match/strategy/FreeDoublesMatchStrategy.java
  infrastructure/src/main/java/org/badminton/infrastructure/match/strategy/FreeSinglesMatchStrategy.java
Labels: feat✨, 5PM🌝
